### ISSUE TITLE
[feedback] another movement shortcuts

### ISSUE THREAD

**Issue by BogusCurry** [tentone/nunuStudio#100]
Hi there ;D
I am very positive suprise over your programm, but with on thin I have a problem, that is the movement. That was a very tricky. I think is was better to move with the keys or WASD and rotate with picture up and down on the keyboard.

Have a nice Day ;D

Bogus

**Comment by tentone** [comment]
Hello

Nice to hear that the program was helpful! Messages like this really makes my day. Thanks a lot!.

Some of those are just example you can easily change iteration code to work as you it! 

Thanks a lot!

Cumps
