### ISSUE TITLE
Toggle sidebar

### ISSUE THREAD

**Issue by fabiomaia** [tentone/nunuStudio#109]
It would be nice if the user could toggle the visibility of the sidebar. Sometimes the extra horizontal space is nice.

**Comment by faviouz** [comment]
And, while you're at it, toggling the material/cli boxes at the bottom would be nice too

**Comment by tentone** [comment]
Hi

Totally agree, on the future im planning to move to a more dynamic layout, where everything is a tab and can be moved around and reorganised (#30).

Adding the ability to collapse tab would be a great addition.

Thanks a lot for the suggestion.

Cumps

**Comment by faviouz** [comment]
Sounds good!

**Comment by tentone** [comment]
Sidebar now attached to the scene editor tab!
