### ISSUE TITLE
Update not immediate when changing attributes with mouse scroll

### ISSUE THREAD

**Issue by user1713952** [tentone/nunuStudio#11]
Hi

I am not sure whether this is a bug or a feature :)

Steps:
1) add a basic shape (ex a plane)
2) double click on it so that the object panel gets updated with its properties
3) click inside the box of any property in the object panel, ex "Size W"
4) use the scroll to change the value
5) nothing happens in the Editor Area
6) click outside the box => object gets updated

**Comment by tentone** [comment]
Hi @user1713952 

This is actually related to the way the browser calls the onchange code, the only solution is to implement my own slider, checkbox etc.

Cumps
