### ISSUE TITLE
No mouse interaction in main window

### ISSUE THREAD

**Issue by pwkey** [tentone/nunuStudio#121]
# Limited mouse interaction

##### Description
I have recently downloaded and installed nunuStudio on my Surface Pro. I am very keen to play with it and believe it will be a great tool to help create technical eLearning material.

However, I cannot get the mouse left or right button to interact at all in the main 3D workspace (except it does work on the 3D/2D icon at the top right). The mouse centre scroll wheel does work, moving in the direction into and out of the screen.

The mouse left button works OK on all the menu selection panels.

I am not sure if this is a reason for the problem, but can you please clarify exactly where/how to implement nwjs, as I am not clear under what directory to place it.

##### Version
 0.92 beta

##### Platform
Windows 10 Pro 64 bit

**Comment by tentone** [comment]
Hi

There was a problem with touch enabled devices, it should be fixed now, try to download it again from Github please (https://github.com/tentone/nunuStudio/archive/master.zip).

NWJS has to be downloaded from https://nwjs.io/ and placed in [nunuStudio]/nwjs/win, (nw.exe should be at [nunuStudio]/nwjs/win/nw.exe)

Thanks a lot for reporting this issue.

Cumps

**Comment by pwkey** [comment]
Hi,

Excellent, that did the trick! ☺

I will keep playing with it. I am very much looking forward to your implementation of the ‘Timeliner’, as I think this will make it much easier for laymen to create more complicated 3D animations. As far as I can find, this will be one of the only HTML5 3D editors that has this feature – well done!

When do you think V 0.9.3 will be up?

Regards,

Peter

**Comment by tentone** [comment]
Nice, thanks a lot for the feedback.

I expect to release version 0.9.3 by the end of this month. I'm also really excited to add animations to the editor, i think that will be a really useful feature.

Thanks a lot for your help.

Cumps

**Comment by pwkey** [comment]
Since we are talking, I will describe my intended use case to you, because I really believe there is a niche (but significant) market out there for technical documentation:


  1.  I am preparing 3D models of structural steel components, such as bolted connections. In addition, I am in process of preparing a 3D model of an infographic such as similar to the one attached illustrating the process of steel making.
  2.  I am utilising SketchUp to create the 3D models. SketchUp exports in Collanda (dae) format, which appears to come into your software OK. I am just working out now how best to structure/group/name components to result in a sensibly structured model in your software.
  3.  I intend to record a voice over for each animation, and then sequence/time the animation  to match the voice over timing.
  4.  My intention is to present the viewer with a scripted animation of a 3D assembly that illustrates, via the 3D and the voice over, particular technical details, and then, at the end of the animated sequence, allow the viewer to interact with the 3D scene to explore particular aspects of what they have just viewed.
  5.  The 3D interaction will be the usual navigation, but also potential to click on elements and have a information box (‘billboard’) come up, or a video to start in a billboard, or URL links to other info etc

Thanks for your time in addressing my issues. I look forward to the end of the month! ☺

Peter
