### ISSUE TITLE
Cannot select some objects in imported model

### ISSUE THREAD

**Issue by pwkey** [tentone/nunuStudio#123]
# Cannot select some objects in imported model

##### Description
I am developing a 3D model of the steel manufacturing process, using Sketchup as the modeller and exporting it as .dae file into nunuStudio. See attached image of current model from Sketchup.
After importing it into nunuStudio, there are some objects that I cannot select/highlight with the mouse pick in the 3D window. These are the objects named 'Sinter plant', 'sinter pile' and 'coke pile'.

Other objects I can select.

I suspect the issue is something to do with the fact that these objects in Sketchup are 'components' (which I downloaded from Sketchup 3D warehouse, whilst other selectable objects are groups I have created in Sketchup. Regardless, it is important to understand why they can be seen but not selected in nunuStudio.....

I have attached the zipped dae file.

##### Version
 - 0.8.2 beta

##### Platform
 Windows 10 on Surface Pro
![infographic - iron and steel making process v0](https://user-images.githubusercontent.com/32823354/32529290-d258f910-c48b-11e7-8dc0-da12252907c0.jpg)
[Infographic - iron and steel making process V0.zip](https://github.com/tentone/nunuStudio/files/1452445/Infographic.-.iron.and.steel.making.process.V0.zip)

**Comment by tentone** [comment]
Hi

I loaded your model, im able to select the objects but they dont get highlighted i have to check what is hapenning.

Thanks a lot for reporting this issue.

Cumps

**Comment by tentone** [comment]
Should be fixed now!

**Comment by pwkey** [comment]
Thanks!

How you going with contemplating putting in sound track/editing? ☺

Peter
