### ISSUE TITLE
Scripting clarifications

### ISSUE THREAD

**Issue by pwkey** [tentone/nunuStudio#125]
# Scripting clarifications

##### Description
Excuse me if this is a silly question :)
I am gong through your tutorials and am on Tutorial 2 for scripting.
At one point you say: 
"To move an object we start by attaching that object as a children of the script object, we can do that by dragging the desired object to the script object, in this tutorial we will use the cube object on the default scene."
It is not obvious to me how you attach a child by dragging. I tried dragging in the object hierarchy view but all that allows me to do is change the order of objects shown, not create a parent/child relationship.

How do you do this?

BTW, you cannot drag an object to the end of the list, only to locations in between other objects. You should be able to place it at the end also!

##### Version
 0.9.3 (as provided to me for download previously)

##### Platform
 Surface Pro on Windows 10 Pro

**Comment by tentone** [comment]
Hi 

Thanks a lot for your feedback dragging objects in the tree in still not as intuitive as i would like to you can basically if you drag to the "center" of another object it is attached as children if you drag to the top it is placed above and if you drag to the bottom it gets placed bellow.


Example of dragging an object to become children of another

![a](https://user-images.githubusercontent.com/9158354/32682902-76949c8e-c66f-11e7-976e-69e1d910a70e.JPG)
![b](https://user-images.githubusercontent.com/9158354/32682848-436869bc-c66f-11e7-9cd1-53fa5536e18b.JPG)


Example of placing an object in the bottom

![c](https://user-images.githubusercontent.com/9158354/32682859-4b03c14e-c66f-11e7-80b4-a85c3b5025fd.JPG)
![d](https://user-images.githubusercontent.com/9158354/32682860-4b80e070-c66f-11e7-84b5-f5729aaedd43.JPG)

**Comment by pwkey** [comment]
Hi,

I actually did try the approach you mentioned previously, and have tried it again, but it just does not work, no matter what I try!
If I drag an object around the tree it is clearly indicated by a horizontal line appearing when it is appropriate to drop the object between other objects. However, that line does not appear when I take the object to the end of the list, and I cannot place the object at the end of the list.
There is no visible ‘marking’ appearing when the object is ‘on top of’ another object and it just will not drop into the tree as a child of that object when I try….

Regards,

Peter
