### ISSUE TITLE
The "About" tab is accessible from 2 places

### ISSUE THREAD

**Issue by user1713952** [tentone/nunuStudio#13]
The about is in the top bar but also inside the settings which makes the interface unintuitive

![image](https://cloud.githubusercontent.com/assets/3883114/23450934/ee5c3e78-fe5d-11e6-87a2-d356e63ff9ce.png)

**Comment by tentone** [comment]
@user1713952 

Hmm you're right the question here is what is the best place, the top bar or the settings menu? 

Thanks in advance!

**Comment by user1713952** [comment]
I am not sure, but I can suggest: https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/MenuBarMenus.html
and 
https://msdn.microsoft.com/en-us/library/windows/desktop/dn742392(v=vs.85).aspx

as reference :)

**Comment by bit2shift** [comment]
Menu bar, end of discussion.
Next...

**Comment by tentone** [comment]
Removed the about tab from the settings menu!
