### ISSUE TITLE
Navigation in 3D view

### ISSUE THREAD

**Issue by pwkey** [tentone/nunuStudio#131]
# Navigation in 3D view

##### Description
1. Is there any convenient way to switch from the FPS style navigation currently in nunustudio to the style of navigation where the world is moved, rather than the camera (as is in three.js)? Whilst I agree FPS is appropriate for a game scenario, it is not as natural for other types of useage, such as my planned 3D animated and interactive technical manuals.

2. I have used Sketchup for 3D modelling for some time now. It has very convenient navigation, in particular the ability to move in/out using the centre scroll wheel, with the point that is being moved to as the current cursor location. In nunustudio currently, moving in/out always moves towards the point at the centre of the screen, which means you need to have an additional panning movement to move to other locations than the centre of the screen. The Sketchup approach is much more efficient....

##### Version
 - 0.9.3

##### Platform
 - Windows 10 on Surface Pro

**Comment by tentone** [comment]
Hi

Its possible to change the navigation method in the settings panel, nunuStudio features an Orbit mode that works similarly to the navigation in sketchup.

I it helps a bit, thank you.

Cumps

**Comment by pwkey** [comment]
Excellent, thank you for the response! Sorry I did not realise this prior ☺
