### ISSUE TITLE
Data received by onAppData is always undefined

### ISSUE THREAD

**Issue by Octavector** [tentone/nunuStudio#134]
Apologies if this isn't the right place for this sort of matter.

My JS script will send the element id of a clicked button to my nunu app using **app.sendData(data)**. nunu listens to this with **onAppData(data)**. Despite the communication between the two seemingly working as it should, the data I receive is always undefined.

Here is the relevant extract from my JS file:
```
    function clickMenu(e){
        e.preventDefault();
        if(e.target.classList.contains('btn')){
            let data = e.target.id;    //'data' is the ID of the .btn element
            console.log(`Sending data: ${data}`);
            app.sendData(data);    //sendData method visible here
        }
    }
```

Here is script within my nunu app:

```
function onAppData(data)
{
	console.log(`Data received: ${data}`); 
	if(typeof data === 'string'){
		settings.currentMat = data;
	}
}
```

When I click a menu button, this is what appears in the console:
```
Sending data: mat_cement
Data received: undefined
```

So they seem to talk but the data is lost?
I've tried sending objects but I receive the same results. 
Am I doing something stupid :) ?

**Comment by tentone** [comment]
Hi @Octavector 

Thanks a lot for reporting this, you are doing it right, this is a bug.

I have found it and fixed it already i will just complete a bit the communication tutorial.

When i push the fix to the repo i will let you know (probably ~30m).

Thanks

**Comment by tentone** [comment]
Implemented! ;)

**Comment by Octavector** [comment]
Super, thanks!
