### ISSUE TITLE
call external js 

### ISSUE THREAD

**Issue by jyy1082** [tentone/nunuStudio#135]
May I ask you that how should I call or import external js files when I writing nunustudio scripts? Thank you!

**Comment by tentone** [comment]
Hi

To import a external JS file into a script, you need to first import that JS file into your project (AssetExplorer/Include/Text), and inside your script use the import method.

```
import("lib.js");

function initialize()
{
....
}
```

This will be changed soon so that is also possible to call import with an URl as parameter.

Cumps

**Comment by jyy1082** [comment]
Hi 

I followed your guide using import("lib.js");, but it showed errors. 

![image](https://user-images.githubusercontent.com/8751908/33789912-f1b4a48c-dc49-11e7-847c-44cb775ca5e6.png)

![image](https://user-images.githubusercontent.com/8751908/33789945-59372dd2-dc4a-11e7-97fb-58bc521a764e.png)

![image](https://user-images.githubusercontent.com/8751908/33789948-634d6d22-dc4a-11e7-9607-ad7b593e7e4f.png)

![image](https://user-images.githubusercontent.com/8751908/33789964-84267c32-dc4a-11e7-9d77-ae17e5e23d7a.png)

**Comment by tentone** [comment]
in your case your resource is called lib try `import("lib");`

**Comment by jyy1082** [comment]
I changed to import("lib");. It still has the same issue. Also, the editor indicates errors in the script. 

![image](https://user-images.githubusercontent.com/8751908/33790105-6242cd5e-dc4b-11e7-8103-d496202158be.png)

**Comment by tentone** [comment]
The myyy method is private inside your javascript file if you change the declaration to 

```
window.myyy = function(a, b)
{
	return a + b;
}
```

it will becoma available globally and it will work but i do have to rethink this a bit to find an alternative for these cases.

**Comment by jyy1082** [comment]
I still have the trouble. However, I will wait your final enhancement about this and try again. If we can import and call any JS file, there will be a lot of third parts JS plugs we can use to build projects. I am looking forward for your works.

**Comment by tentone** [comment]
Im still trying to figure out the best way to really do this, the only way for it to work in cases like the one you have is to append the code before evaluation.

That will also cause some some problems in other cases.

Im thinking about adding a mode option for libs in the script object.

Evaluate mode - Libraries are evaluated on runtime
Append mode - Libraries are appended on top of the script code

What do you think about this approach?

**Comment by tentone** [comment]
![asdsad](https://user-images.githubusercontent.com/9158354/33796002-1dfaf632-dce4-11e7-9db3-e2e8da97a267.JPG)

Added the possibility to change the mode in the script object panel.

I hope this approach can solve the problem.

Thanks a lot for your feedback!

**Comment by jyy1082** [comment]
Great! I saw your updating of the script tutorial to introduce libraries, and I tried your example, that works well to import and run a third party JS file using Evaluate mode. In this approach, we can easily to implement complex functions based on others' libraries. Thanks very much for you work!

Just one suggestion, if you can add an example about Append mode, that will great for users to understanding about the difference of these two modes.

**Comment by tentone** [comment]
I will update the learning guide soon to include an explanation about these!

Thanks a lot! I will probably still experiment a bit for a couple more days!
