### ISSUE TITLE
Highlight selected model in project explorer

### ISSUE THREAD

**Issue by jyy1082** [tentone/nunuStudio#137]
If I have a lot of models(imported from .dae) in the scene, I can not easily find the selected model in the project explorer. so if it can automatically highlight and scrolling to focus on selected mode in the project explorer, that will easy to use. 

 Version
 - 0.9.3

 Platform
 - Web Version [X]

**Comment by tentone** [comment]
Thanks a lot for the suggestion i think that would be a good addition to the editor.

I have to study the best way to do this.

**Comment by tentone** [comment]
It is now implemented, on selection the tree scrolls to the selected object
