### ISSUE TITLE
Disable showing selected model icon

### ISSUE THREAD

**Issue by jyy1082** [tentone/nunuStudio#138]
Can I disable showing this "cube" once I selected one model?

![image](https://user-images.githubusercontent.com/8751908/33817219-6ddfef44-de0c-11e7-8d04-826e662b662b.png)

 Version
 - 0.9.3
 Platform
 - Web Version [X]

**Comment by tentone** [comment]
Hi

I can add an option to disable them, but i could also change them for them to rescale dynamically so that they dont look big when youre close to them.

Cumps

**Comment by jyy1082** [comment]
How do you think using highlighted edges instead of a icon to indicated that?

![image](https://user-images.githubusercontent.com/8751908/33842473-a2364c78-de68-11e7-982f-ce56bc515d08.png)

**Comment by tentone** [comment]
Icons automatically rescale to keep they screen size.
