### ISSUE TITLE
Center Pivot tool in the selected object 

### ISSUE THREAD

**Issue by jyy1082** [tentone/nunuStudio#139]
Description

When I selected one of model imported from .dae, the pivot tool always shows in the center of the scene. How about make this pivot tool in the center of a selected model?

Additionally, if there is one function that can enable user to move pivot tool, that will be really nice to rotate the object. 

Version
 - <0.9.3> 

Platform
 - Web Version [X]

![image](https://user-images.githubusercontent.com/8751908/33862662-e3e642c4-deb1-11e7-9ea8-45e86b2c625c.png)

**Comment by tentone** [comment]
Hi.

This might be a little trickier to implement, i have to study it a bit.

Thanks a lot for the suggestion

Cumps
