### ISSUE TITLE
The panel group is difficult to distinguish from the menu

### ISSUE THREAD

**Issue by user1713952** [tentone/nunuStudio#14]
When tabs are opened, they kind of merge into the top menu bar giving the whole interface a confusing appearance. The effect is strongest when the settings tab is also opened.

I believe this is a matter of colors :)

![image](https://cloud.githubusercontent.com/assets/3883114/23450992/39f740bc-fe5e-11e6-9f30-432ff9fee233.png)

**Comment by tentone** [comment]
Hi @user1713952 

True. i will revise this when i implement the "new" theming system with CSS.

But i will until the first beta.

Cumps
