### ISSUE TITLE
Lock the ratio for scale input

### ISSUE THREAD

**Issue by jyy1082** [tentone/nunuStudio#140]
Description
When I manually input the scale of one model, is it possible to have a option to lock/unlock the ratio of the scale? Since sometimes changing the scale in the Editor Area is not good to control, we have to use manual input with keeping the ratio of scale. 

![image](https://user-images.githubusercontent.com/8751908/33863529-312c948a-deb6-11e7-8291-612ef62e6c89.png)

Version
 - <0.9.3> 

Platform
 - Web Version [X]

**Comment by tentone** [comment]
Hi

Hmm nice yep i think i could add this, in the panel!.

Thanks a lot for the suggestion.

Cumps

**Comment by tentone** [comment]
![capture](https://user-images.githubusercontent.com/9158354/34232035-63db30cc-e5d6-11e7-8b12-659fd588258d.JPG)
 Implemented!

**Comment by jyy1082** [comment]
Nice! Thank you!
