### ISSUE TITLE
Status of 0.9.3

### ISSUE THREAD

**Issue by pwkey** [tentone/nunuStudio#141]
# Status of 0.9.3

Any idea when 0.9.3 will be out? I am looking forward to test driving the new 'timeliner' functionality! :)

**Comment by tentone** [comment]
Hi im trying to finish it before the end of the year but cant say a date.

Thanks a lot!

Cumps

**Comment by pwkey** [comment]
Hi,

Thanks for the response. I felt bad to ask about it, as you are working so hard ☺

Regards,

Peter
