### ISSUE TITLE
Integration with timeliner                         

### ISSUE THREAD

**Issue by pwkey** [tentone/nunuStudio#150]
# Is integration with timeliner still in scope for 0.9.3?

##### Description
Was wondering if integration with timeliner was still in scope for 0.9.3? Noticed you dropped it from the list of changes/improvements for 0.9.3. I have been very much looking forward to this functionality...

**Comment by tentone** [comment]
Hi

Yes i decided to move from integrating an external animation system to developing a dedicated system for nunuStudio, it is actually working already needs some more polishing but should be ready in less than a week.

Sorry for the big delay and thanks a lot for your support. Happy new year!

Cumps
![capture](https://user-images.githubusercontent.com/9158354/34629427-fa7e89a8-f25f-11e7-90e7-a6003529ff5e.JPG)

**Comment by pwkey** [comment]
Excellent! :)

Do you think audio sync would be hard to add to your solution?

Regards,

Peter

**Comment by tentone** [comment]
I can try and add script function calling to the timeline, or as it is currently this can also be easily achieved by creating a boolean value on the timeline and pulling it inside a  script

**Comment by pwkey** [comment]
It would be great if you could do whatever you reasonably can to add the ability to sync in audio segments :) As you may recall, I am really seeing your excellent solution as a practical way to be able to create interactive technical animations with voiceover for HTML5.
I know your main focus is for a game engine, but there does not seem to be very much out there at the moment to fill this use case for technical animation, and it might well be a very good option :).
I really appreciate all that you are doing and your responsiveness!

**Comment by tentone** [comment]
Hi @pwkey 

A beta version of the animation editor is still hasn't support for custom attributes but can be already used for some experimenting.

I try to figure out the best way to integrate your needs into it soon.

Sorry for the delay.

Cheers!

**Comment by pwkey** [comment]
Hi tentone,

Excellent news! Once you publish 0.9.3 I will play around with it and provide feedback. Hopefully I get to the point I can provide some useful input :)

Cheers!
