### ISSUE TITLE
Scripting Window -dockable parallel

### ISSUE THREAD

**Issue by weekendkoder** [tentone/nunuStudio#154]
Scripting Window

##### Description
Currently i am able to start scripting by adding a script-object. Doubleclick on it opens a new tab. So far, so good. But it would be really nice, if i have a splitted viewport, so 2x windows. F.e. left my 3d view window, right my scripting window. This way i am able to see instantly cause-effects, when doing changes in my code.

##### Version
v0.93

##### Platform
windows 8 , NwJS

**Comment by tentone** [comment]
Hi

Thanks a lot for the suggestion totally agree, there is already an issue with this objective.

Not only for script editor but also for other tabs (MateiralEditor, ParticleEditor, etc).

Thanks a lot for the suggestion.

Cheers

**Comment by weekendkoder** [comment]
Ah ok. Cool. You are welcome. As long as i can give hints, or can help ... i will do it again ;-)
