### ISSUE TITLE
docs page not working in chrome

### ISSUE THREAD

**Issue by movAX13h** [tentone/nunuStudio#155]
http://nunustudio.org/docs/ 

The docs page works in firefox. It does not work in chrome, tested with adblock off too.
I'm on win8.1.

![image](https://user-images.githubusercontent.com/1974959/34901247-1aa6d110-f808-11e7-9edb-3dc142341c54.png)

**Comment by tentone** [comment]
Hi @movAX13h 

Can you please check again?

Thanks a lot for reporting this.

Cumps

**Comment by movAX13h** [comment]
Hi @tentone,

I've tried again. Same behaviour. This is the url that causes the problem:
`http://yui.yahooapis.com/combo?3.10.1/oop/oop-min.js&3.10.1/event-custom-base/event-custom-base-min.js&3.10.1/dom-core/dom-core-min.js&3.10.1/dom-base/dom-base-min.js&3.10.1/selector-native/selector-native-min.js&3.10.1/selector/selector-min.js&3.10.1/node-core/node-core-min.js&3.10.1/node-base/node-base-min.js&3.10.1/event-base/event-base-min.js&3.10.1/event-delegate/event-delegate-min.js&3.10.1/node-event-delegate/node-event-delegate-min.js&3.10.1/pluginhost-base/pluginhost-base-min.js&3.10.1/pluginhost-config/pluginhost-config-min.js&3.10.1/node-pluginhost/node-pluginhost-min.js&3.10.1/dom-style/dom-style-min.js&3.10.1/dom-screen/dom-screen-min.js&3.10.1/node-screen/node-screen-min.js&3.10.1/node-style/node-style-min.js`

Weirdly, loading the URL in firefox works just fine (displays js code). When I load it in Chrome if first gets redirected internally (307) and then ends with a 404:
![image](https://user-images.githubusercontent.com/1974959/34911713-28086878-f8d0-11e7-98c3-d75a51af629f.png)

**Comment by tentone** [comment]
Should be fixed
