### ISSUE TITLE
some inspiration - cables.gl

### ISSUE THREAD

**Issue by weekendkoder** [tentone/nunuStudio#156]
Just inspiration

##### Description
Maybe you allready know: cables.gl (https://cables.gl/). I think you can take a look how they
did some stuff. I was just interested into the Visual Programming. They also have some nice
PostEffect Filters in their samples...

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hi 

Thanks a lot for the suggestion for nunuStudio i plan to implement a node based material editor using the already existing NodeMaterial components in three.js.

Thanks a lot for the suggestion.

Cheers

**Comment by weekendkoder** [comment]
I am just glad, if i can help somehow, to improve maybe something. 

This are great news, man !!! A shader editor, for a upcoming version ! Wow ! For me, nunuStudio is the best webGL Editor / GameEngine i´ve used, tested ! As a long Cinema 4D User, i think this could also be interesting for you : https://insydium.ltd/products/cycles-4d/ (they have also a really nice Node-Sys.)
https://www.blendernation.com/wp-content/uploads/2016/08/Cycles_FullUI.jpg.3e5fcff3646416cc89cdf5a6f38a7f4e.jpg

Don´t know if you got my E-Mail from 03.01.2018 ? Just asked you few questions. So i guess you were busy with lot of stuff. Let me know, if you missed it. Thx.

**Comment by tentone** [comment]
What i plan to implement is similar, to the node editor in cycles.

Yeah, i received your email i replied to it, thanks a lot for offering help, i will paste my answer bellow, maybe it went into your spam box?

```
Hi

Thanks a lot for telling your story, hearing this really makes my day.

I have been working on nunuStudio alone (with the help of libraries and other work made by other people), nunuStudio is an open source project, every help is welcome.

Currently I’m trying to focus as much as I can on the features for the upcoming version like the timeline animation system, texture compression etc.

Thanks a lot! Happy new year!

Cheers!

```

Cheers!

**Comment by weekendkoder** [comment]
You are right, it was somewhere deep in a email-folder :-) . But now I got your mail. Thx.

Great, really great you are working on such cool stuff ! To be honest: i tested some nunuStudio Examples on my mobile. And it worked really well right out of the browser. Just impressing. In relation to native-apps it is really close. Other webGL solutions are lagging or don´t work on mobiles. 

Much respect, you are doing everything by your own! Wow.
