### ISSUE TITLE
Render the background as transparent

### ISSUE THREAD

**Issue by jvetulani** [tentone/nunuStudio#158]
# Render the background as transparent

##### Description
 - Trying to figure out how to render just a model with particle effects, lighting and such, while keeping the background transparent, so whatever I have behind the embedded canvas comes through
 - Is it possible? A combination of nunuStudio settings and setting up the html file?

##### Platform
 - Chrome, Edge, Firefox, Safari
 - Windows
 - Linux
-  Mac

**Comment by tentone** [comment]
Hi

Yes its possible to have a transparent background, by default the projects already have a transparent background but just to make sure select the  scene object and click on "Set transparent".

After simply export the project and include it in your page as described here http://nunustudio.org/learn/integration/01_embedding/page.html and the content behing the canvas used should be visible.

Cheers
