### ISSUE TITLE
iOS Fullscreen

### ISSUE THREAD

**Issue by joduffy** [tentone/nunuStudio#162]
# iOS not entering full screen

##### Description
The home page for nunuStudio works on Android and iOS.
But when I navigate to the Learn VR section. I noticed that it doesn't enter in Stereo Mode.

When I use an Android Device, I can get it to enter fullscreen. But it won't display in VR (unless this has not been implemented in the example?)

On iOS, clicking on the fullscreen does nothing. It doesn't enter into a fullscreen mode as the Android version does.

The url I am using is:
[http://nunustudio.org/learn/basics/10_vr/page.html](url)

##### Version
 - <nunuStudio Website> <26th February 2018, 8-9am PT>

##### Platform
 - Web Version [nunuStudio Website]
 - MacOS [10.13.3]
 - iPhone 7 [11.3]
- Lenovo Phab 2 [Tango Android Version 6.0.1]

**Comment by tentone** [comment]
Hi

The stereo mode is achieved using WebVR, it is an API that has to be implemented in the browser. 

iOS still does not have support for WebVR. But it should enter the fullscreen mode. I will check the code to see if i missed something.

WebVR only works when accessing via HTTPS use the following link when testing https://nunustudio.org/learn/basics/10_vr/page.html


Thanks a lot for reporting this problem.

Cheers

**Comment by joduffy** [comment]
Hi,

I still had my original link to the learn vr page open. When I checked it was HTTPS.

I can try and find a different iOS version to test it on. Mine is 11.3.

Jonathan
On Feb 26, 2018, at 3:13 PM, Tentone <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi

The stereo mode is achieved using WebVR, it is an API that has to be implemented in the browser.

iOS still does not have support for WebVR. But it should enter the fullscreen mode. I will check the code to see if i missed something.

WebVR only works when accessing via HTTPS use the following link when testing https://nunustudio.org/learn/basics/10_vr/page.html

Thanks a lot for reporting this problem.

Cheers
