### ISSUE TITLE
Camera Bug

### ISSUE THREAD

**Issue by TTMMIIZZ100** [tentone/nunuStudio#163]
# Camera Glitch

##### Description
When you create a camera and check "use camera," and then delete the camera, the program no longer runs, an error message appears saying "Initialization Failed," I have no scripts in that project. I think this occurs because Nunustudio thinks the camera still exists. Even when I create a new camera, this glitch still occurs.

Another thing I noticed is some slight lag in the editor after the happens.

##### Version
V0.8.9.15 Alpha

##### Platform
 Chrome 64-bit Windows 10

**Comment by tentone** [comment]
Hi

Thanks a lot for reporting this problem.

Fixed it. (Available on the online version).

Cheers
