### ISSUE TITLE
Exported html not ready for mobile

### ISSUE THREAD

**Issue by movAX13h** [tentone/nunuStudio#175]
Exported websites do not render properly in mobile browsers. Retina is not taken into account which leads to low-res rendering and orientation changes are not supported at all.

Also, the generated index.html is not valid html (closing img tag for example).

**Comment by tentone** [comment]
Hi

Thanks a lot for reporting. At some point i might have broken the devicePixelRatio support., Should be fixed now in the dev version, might take a while to get online, check the timestamp)

I have fixed the index problem in the dev version also thank a lot for reporting

Cheers
