### ISSUE TITLE
Loading external shader

### ISSUE THREAD

**Issue by Bethleem** [tentone/nunuStudio#179]
Just a doubt. If I have a shader that works with three.js, is there a way to bring it to nunustudio?
I mean, theres is A LOT of resources avaliable for pure three.js and would love to import one specific water shader a bit more complex than the one in the tutorials. It would make a wonderful tutorial something like "Import your external three.js shit into nunustudio for dummies". :)

**Comment by tentone** [comment]
Hi

I think that you should be able to import your code into nunu direcly as a JS file.

I can write a tutorial on how to do that, can you please indicate which of the water shaders are you using plesae?

Thanks a lot

**Comment by tentone** [comment]
I have just realised that i had already stated writing this tutorial, heres the project for that tutorial xD

I will try to finish the document soon

[sepia.zip](https://github.com/tentone/nunuStudio/files/2211742/sepia.zip)

**Comment by Bethleem** [comment]
Thank you, So it´s getting the js into the project and then just call it. What a wonderfull world of possibilties there. :)
One suggestion: a fps count gadget to throw into the project would be nice. I just link stats.js, but you know, the more features nunuStudio can offer, the faster it spreads.

nunuStudio is kinda the unity for webgl, but working well, not as the fat, slow, inefficient target unity does. Love it more and more.
