### ISSUE TITLE
Particle Editor Bug: Single Editor Affecting Multiple Emitters

### ISSUE THREAD

**Issue by kimballfrank** [tentone/nunuStudio#180]
Particle system editor is really cool. But I noticed a bug where the controls of one editor seem to be adjusting all the particle systems at once, which is not the expected behavior.

I expected to be able to adjust opacity of each particle system individually.

Steps to reproduce:
1. Add a particle emitter to a new scene
2. Duplicate the particle emitter
3. Adjust the opacity settings of the first emitter
4. Note how the opacity settings of the second emitter have also been adjusted

**Comment by tentone** [comment]
Hi

Thanks a lot for reporting this problem, it is now fixed.

Cheers
