### ISSUE TITLE
Feature Request: Export Particle Emitter

### ISSUE THREAD

**Issue by kimballfrank** [tentone/nunuStudio#181]
I really like the particle editor. It would be really valuable to be able to create particle effects using nunustudio, and then export them for use in my other threejs + SPE project.

How hard would it be to export the particle system settings as JSON?

**Comment by tentone** [comment]
Hi

I can add a dropdown option in the project explorer. But you would still need to manually add the import code to your external projects.

The code can be found at https://github.com/tentone/nunuStudio/blob/master/source/core/loaders/ObjectLoader.js

Thanks a lot for the suggestion.

Cheers
