### ISSUE TITLE
Can't load saved file

### ISSUE THREAD

**Issue by shantee** [tentone/nunuStudio#183]
# Error when loading project file

##### Description
 I have a problem when I try to load a saved project file 
 This error message appears (and the file doesn't load)

SyntaxError: Unexpected token in JSON at position 0

 

##### Version
 - 0.9.5

##### Platform
 - Linux [X] (Linux Mint)

**Comment by tentone** [comment]
Hi

Im not being able to reproduce the issue, can you please confirm with the last online version if it still shows a error.

Is it possible to share a file where this happens?

Thanks a lot.

Cheers

**Comment by tentone** [comment]
I was able to load the file you sent, it was missing the ".nsp" extension, witch is required for nunuStudio to know the correct type of file.

![asdasdas](https://user-images.githubusercontent.com/9158354/43403192-60abb162-940c-11e8-9d0c-d88978665c0a.PNG)
