### ISSUE TITLE
ConvexHull error

### ISSUE THREAD

**Issue by Bethleem** [tentone/nunuStudio#184]
Added a dodecahedron in a scene, added convex ConveHull physics attached, saved. Export as web and didnt run. Try to load again in the editor: Error TypeError: c.vsub is not a function.
Added just a dodecahedron without the ConvexHull: runs ok and load ok.
Then added a cube, attached ConvexHull physics instead of box: didn´t run, same load error.

**Comment by tentone** [comment]
This error should be fixed now. Thanks for reporting.
