### ISSUE TITLE
nunu doesn't work anymore

### ISSUE THREAD

**Issue by jozeflukac** [tentone/nunuStudio#185]
# Issue title

##### Description
I'm getting error when trying to use online editor (https://nunustudio.org/editor/editor.html)

Uncaught SyntaxError: Unexpected end of input (nunu.editor.min.js:130)

##### Version
 - Latest from web 9.8.2018

##### Platform
 - Web Version 
 - Linux

**Comment by tentone** [comment]
Hi

Holy s#$%, sorry was my fault i pushed a bad build  to the server.

Updating it right now try again in 10 minutes and it should be working.

Thanks a lot for reporting.

Cheers.

**Comment by jozeflukac** [comment]
Thank you very much. It works again :) Good job! Thanks again.
