### ISSUE TITLE
Is it possible to provide a like Unity3d UI editor

### ISSUE THREAD

**Issue by alipaypay** [tentone/nunuStudio#189]
# Issue title

##### Description
Many features are difficult to develop without a Ui editor

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hi

By UI do you mean buttons, text, radio buttons etc for menus inside lets say a game?

I think i may be able to implement that, but i dont think it is a priority since it is possible to use HTML for all of that.

Thanks a lot for the idea.

**Comment by ikelaiah** [comment]
@tentone 

Do you have a tutorial on how to display HTML text, buttons and radio inside NunuStudio?

Thanks.

**Comment by tentone** [comment]
Yes there is a tutorial, the first script tutorial explains about that.

**Comment by ikelaiah** [comment]
@tentone 

I figured it out. Thanks. It is very flexible that you can leverage CSS for the UI. This is simply amazing.
