### ISSUE TITLE
What is the best way to create a UI Panel?

### ISSUE THREAD

**Issue by ikelaiah** [tentone/nunuStudio#190]
I'd like to create a UI Label/panel to show some text under mouse position.
What is the best way to achieve this in NunuStudio?

Thank you.

**Comment by ikelaiah** [comment]
Sorted. I figured out by looking at this [tutorial](https://nunustudio.org/learn/basics/02_script/page.html).
Amazing. I could use CSS + HTML to create UI. I should try CSS 3D too.

**Comment by tentone** [comment]
Hi

The best to create a interface is to use HTML and CSS yes.

Some people are also using planes with textures and text elements and that works nicely as well.

Thanks a lot!

**Comment by ikelaiah** [comment]
Well, I'm content being able to use CSS for UI. I think the concept of NunuStudio is amazing. Thank you!

**Comment by tentone** [comment]
Happy to help.
