### ISSUE TITLE
Reverting `Orbit` movement

### ISSUE THREAD

**Issue by ikelaiah** [tentone/nunuStudio#191]
I managed to setup the `Orbit` camera by making the camera as a child of the `Orbit`.
Is there a way to reverse the direction of the orbit?
Thanks.

**Comment by tentone** [comment]
Hi

By reverse you mean to move backwards or to look to the outside?

To look to the outside you can simply rotate the camera.

Cumps

**Comment by ikelaiah** [comment]
Hi,

When I put a camera under orbit, when I drag mouse up, camera move up and points downwards.
Is there a way to reverse this so that when I drag mouse up, camera move down and points upwards?
