### ISSUE TITLE
`orbit` has a child `camera` pointing -z upon run, the camera points -x

### ISSUE THREAD

**Issue by ikelaiah** [tentone/nunuStudio#193]
# `orbit` has a child `camera` pointing -z upon run, the camera points -x

##### Description
I'm trying to setup a orbit camera upon run to face the -z direction. The orbit rotation is [0, 0, 0]. The camera's rotation is [0, 0, 0].
![2018-09-12 19_41_10-window](https://user-images.githubusercontent.com/32469901/45416926-5161a880-b6c4-11e8-8995-6a07d62cec30.png)

When I press run, the camera automatically faces -x. Could you help?
![2018-09-12 19_41_40-window](https://user-images.githubusercontent.com/32469901/45416969-6f2f0d80-b6c4-11e8-8caa-de95b70ad8a8.png)

##### Version
 - 0.9.3-beta 201802110023

##### Platform
 - Web Version [X]
 - Windows [X]

**Comment by tentone** [comment]
This bug has been fixe should work already on the web version.

Thanks a lot!
