### ISSUE TITLE
How to achieve the IBL as in the demo?

### ISSUE THREAD

**Issue by ikelaiah** [tentone/nunuStudio#194]
I'm quite impressed with this [demo](https://nunustudio.org/examples/demo.html?isp=files/pbr.nsp).

My question is, how did you achieve that IBL (Image Based Lighting) in that scene?

**Comment by tentone** [comment]
Hi

The effect in that demo was achieved using a cubemap.

Cheers

**Comment by ikelaiah** [comment]
Impressive!
