### ISSUE TITLE
ThreeJs behind the scene? Missing ThreeJs Features Planned (LOD, etc...)?

### ISSUE THREAD

**Issue by 3kynox** [tentone/nunuStudio#197]
Hello and sorry to post this in issues.

I have a question and wasn't know where to post it of.

Does nunuStudio a completely different engine than Three.Js or does it use Three.Js behind the scene?

I mean, I'm pretty impressed by nunuStudio but I wouldn't be in the case I want to use full features of Three.Js (like LOD for example) and it's missing here.

Thanks anyway and hope to join your awesome project here!

**Comment by tentone** [comment]
Hi

It uses threejs underneat, most threejs classes can be acessed in scripts without the THREE. prefix.

I may be able to add support to some of those features in the future.

Fell free to post any suggestions here on the issues page here.

Thanks a lot for your feedback.

**Comment by 3kynox** [comment]
Great to see this project highly active!

For informations, my goal is to make a remake of the first MMORTS with persistent massive universe that was named "Mankind" originally developped by Vibes and bought back by O2OE (a chinese company that simply killed the game), But this time using real 3D and Procedural Generation (which explain why I'm looking for LOD).

I'm mostly a php coder, doing more js on a daily basis and fan of Vue.Js

Thanks again.

**Comment by 3kynox** [comment]
Hmmm, having another question. You say most of the threejs functions can be accessed wthout the THREE prefix, but does we can use THREE prefix as well already?

**Comment by sloothes** [comment]
As I can see in the last hours that I digging the nunuStudio, all the functions and properties (including the THREE object itself ) are placed in the window object. So they are accessable with and/or without the "THREE" prefix.

**Comment by 3kynox** [comment]
Hello, thanks for your answer. That is great, means a cook editor environment for Three now :)

If I can ask an extra question, how is it managed to export project? All examples I see got the loading bar "Nunustudio". Is it possible to export without having that forcibly? Or export the project on pure ThreeJs code.

Thanks anyway, keep up things here!

ps: I'm voting to finish this blueprint PR :)

**Comment by tentone** [comment]
All the example have that loader code that is exported in the default template but you can actually override all of that, or write your own loader for nsp files using the API provided by nunu studio.

Check these two tutorials -> http://nunustudio.org/learn/integration/01_embedding/page.html and http://nunustudio.org/learn/integration/02_communication/page.html

**Comment by 3kynox** [comment]
Perfect, damn fast to answer lol :)

Glad everything from Three can be used now inside the NunuStudio editor.
It have been now chosen for my next long-term space game development :)

Cheers
