### ISSUE TITLE
Cannot adjust 2D view

### ISSUE THREAD

**Issue by user1713952** [tentone/nunuStudio#20]
It seems it only looks in one predefined direction and there is no way to change it

**Comment by tentone** [comment]
Yeah thas true i have to change that, still i find really confusing to contoll the orthographic in the same way we control the perspective one.

I really need to experiment a bit, i would love to change on the fly the project matrix and keep the same camera object, what do you think about this?

**Comment by tentone** [comment]
2D camera can not be rotation using the orientation cube, (still needs som ajustments)
