### ISSUE TITLE
i use nunu studio source code library,but screen is black

### ISSUE THREAD

**Issue by JumpNote** [tentone/nunuStudio#200]
# Issue title

##### Description
![image](https://user-images.githubusercontent.com/10766457/45866712-3bcf3b80-bdb4-11e8-8158-b82a8d9102fd.png)

i use nunu studio source code library,but screen is black
##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by shantee** [comment]
I take the liberty to reply even though i am not an expert . Have you added a material to your object ? a light source ?
