### ISSUE TITLE
use nunustudio source code library,But the viewport size is 1/4 of normal

### ISSUE THREAD

**Issue by alipaypay** [tentone/nunuStudio#201]
# Issue title

##### Description
 
![image](https://user-images.githubusercontent.com/41935990/46211778-f6d47780-c366-11e8-8b43-5d54aa8ef2ba.png)
I use scene.addCamera() function,The result is shown in figure，please help！thank you！！！

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hi

Does the camera get fixed after resizing the window?  Can you please check your window.devicePixelRatio value?

It would be nice if you could share an example.

Thanks a lot for reporting this issue.

Cheers

**Comment by alipaypay** [comment]
I adjusted the aspect value to be width/height in the window.resize event, and called the camera.resize function without any extra processing

**Comment by tentone** [comment]
Oh nice then is was just missing the resize call. I have to figure a better way to remove that aditional step during runtime.

Thanks a lot

**Comment by alipaypay** [comment]
What can I do now to solve this problem

**Comment by alipaypay** [comment]
I printed the value of window.devicepixelratio, and the result is 2.200000047683716. I changed it to 1 and the viewport is correct! How do I set it up better??
