### ISSUE TITLE
The scene data is packaged into arraybuffer data, but the mobile side scene loading is not successful

### ISSUE THREAD

**Issue by alipaypay** [tentone/nunuStudio#203]
# Issue title

##### Description
the scene package partial  data:
 673c 2840 0000 02fc 0867 656f 6d65 7472
79fc 2438 4231 4337 3133 322d 3244 3844
2d34 4443 352d 3933 4434 2d39 4434 3543
3543 3336 3841 37fc 086d 6174 6572 6961
6cfc 2434 4443 3641 3830 362d 3335 4144
2d34 3144 412d 4233 4437 2d46 4445 3845
3436 4443 4131 44f6 07fc 0475 7569 64fc
2433 4636 4141 3832 422d 4446 4341 2d34
4430 322d 3930 3238 2d30 3636 4631 4637
3539 3346 42fc 0474 7970 65fc 044d 6573
68fc 046e 616d 65fc 08e7 9083 e4bd 9320
36fc 066c 6179 6572 7302 fc06 6d61 7472
6978 f710 0200 0000 0002 0000 0000 0200
0000 fb12 e352 3e37 fd3d 4002 fc08 6765
6f6d 6574 7279 fc24 3442 4230 4532 3533
2d45 4432 452d 3430 4541 2d38 3131 422d
4344 3335 3046 4631 4535 4533 fc08 6d61
7465 7269 616c fc24 3142 3731 4446 3546
2d30 4633 302d 3433 3741 2d42 3932 442d
4242 3335 3742 4231 4337 3742 fc0a 6261
636b 6772 6f75 6e64 f603 fc01 7200 fc01
6700 fc01 6200 fc0a 7573 6550 6879 7369
6373 f1fc 0763 616d 6572 6173 f4fc 0577
6f72 6c64 f604 fc07 6772 6176 6974 79f6
03fc 0178 00fc 0179 fb9a 9999 9999 9923
c0fc 017a 00fc 1171 7561 744e 6f72 6d61
6c69 7a65 536b 6970 00fc 1171 7561 744e
6f72 6d61 6c69 7a65 4661 7374 f2fc 0673
6f6c 7665 72f6 02fc 0974 6f6c 6572 616e
6365 fb9a 9999 9999 99a9 3ffc 0a69 7465
7261 7469 6f6e 730e fc0a 636f 6d70 6f6e
656e 7473 f3fc 0773 6372 6970 7473 f3fc
0661 7373 6574 73f6 02fc 0361 6c6c f602
fc02 6964 01fc 0464 6174 61f4 fc07 666f
6c64 6572 73f6 02fc 0269 6401 fc04 6461

PC load successfully,but mobile failed 
##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hi

Cant understand what you want?
