### ISSUE TITLE
camera add SobelPass and set renderToScreen,but the screen is black 

### ISSUE THREAD

**Issue by alipaypay** [tentone/nunuStudio#204]
# Issue title

##### Description
camera add SobelPass and set renderToScreen,but the screen is black
##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hi

Can you please post a screenshot of your post processing config?

Thannks a lot.

Cheers

**Comment by tentone** [comment]
This behavior should be now fixed!
