### ISSUE TITLE
How to do FPS controls collisions

### ISSUE THREAD

**Issue by NothersInGame** [tentone/nunuStudio#205]
# FPS Controls collisions

##### Version
 - Master

##### Platform
 - Windows [X]

**Comment by tentone** [comment]
Hi

Please take a look at the portal game example.

Cumps

**Comment by NothersInGame** [comment]
Hi tentone. Is me again...
Im working in a fork of nunuStudio in which i've implemented a system like blueprints, make grow the post processing and im changing the material editor to make it with nodes, i would like when it be public you can implemente many of these things 😄

**Comment by tentone** [comment]
Fork the repository on github. https://guides.github.com/activities/forking/

Create a branch from that fork on git. Add your own code there.

Open pull requests to suggest adding your code to the main repo.

**Comment by NothersInGame** [comment]
Ok... I'll implement the blueprints and i'll open a pull request
