### ISSUE TITLE
How to use PostProcessing?

### ISSUE THREAD

**Issue by NothersInGame** [tentone/nunuStudio#206]
# How to use PostProcessing?

#### Description
Hello. I'm trying to implement the bloom shader but i dont know how... How can i implement it?

##### Version
 - master

##### Platform
 - Windows [X]

**Comment by tentone** [comment]
Hi.

Please fill the issue with a proper description.

**Comment by NothersInGame** [comment]
Ok

**Comment by tentone** [comment]
Hi

To create a post processing effect double click de camera object and it will open the post processing editor.

Simply add and sort render passes.

**Comment by tentone** [comment]
Please let me know of some of these bugs (some o them i must already know).

**Comment by NothersInGame** [comment]
The camera comes black when i add the SSAO

**Comment by NothersInGame** [comment]
Hey i've cloned nunu...
