### ISSUE TITLE
Camera properties

### ISSUE THREAD

**Issue by user1713952** [tentone/nunuStudio#21]
The default camera does not appear in the object browser.

**Comment by tentone** [comment]
Hi @user1713952 

The default camera is actually not edittable and its added on initialization only if there is none available on the project.

I migth add a default camera to the default scene teplate, would this be better?

Cumps

**Comment by user1713952** [comment]
I was thinking that this could help also for the case of the 2D mode referenced here. It is very convenient to have access to all the elements of the scene from the browser
