### ISSUE TITLE
Camera breaks when using more than one post-processing effect

### ISSUE THREAD

**Issue by vylevylevyle** [tentone/nunuStudio#212]
I've been trying to add multiple effects to no avail....how can we use more than one post-processing effect? Is there a specfic order they must be?

**Comment by tentone** [comment]
Hi

Post processing effects still have some bugs. the limitations you found are bug related.

What were the combinations that dindt work for you?

Thanks a lot

**Comment by tentone** [comment]
Should be now fixed
