### ISSUE TITLE
Mouse wheel doesn't work

### ISSUE THREAD

**Issue by shantee** [tentone/nunuStudio#213]
Hello
I can't scroll in script view with my mouse wheel. and also in the setting windows. I can zoom in and zoom out but i can't do anything else 

##### Version
I am using the latest version 0.9.5 beta

##### Platform
 - Linux [X]

**Comment by tentone** [comment]
Hi @shantee 

This was a problem a few versions ago. It is now fixed i just rechecked everything seems to be okay.

Please download the last version from GitHub. (You can run it using npm install, npm run start).

The NWJS is now automatically downloaded from npm.

Thanks a lot
