### ISSUE TITLE
How to start Nunustudio fullscreen

### ISSUE THREAD

**Issue by shantee** [tentone/nunuStudio#221]
Hello ,

I start nunustudio via the command line  on linux 
nw source 
Now  I wonder how to make it appear full screen (maximized).
Thanks a lot ! Long live Nunu !

**Comment by tentone** [comment]
Hi

I have made some changes recently that allow to run nunu using nw from npm. (npm install, npm star run)

To run nunuStudio in fullscreen change the source/package.json file and add "fullscreen": true inside of window:{...}.

Thaks a lot for your suppot i hope this helps.

Cheers

**Comment by shantee** [comment]
Perfect thanks ! it is working fine
