### ISSUE TITLE
Sample of how to use videoloader class

### ISSUE THREAD

**Issue by jfa257** [tentone/nunuStudio#224]
Hi Tentone,

I would like to see an example case of using the videoloader class, I know this is not properly a nunustudio issue but an example on how to do this is always helpful to the community of nunustudio. 

 About the video loader, I saw it return a json material, I don't understand what to do with this data. Is this the video file dumped on a json? Anyway, on your last added tutorial (thanks for the quick update)  you mentioned its is possible to load the entire video instead of streaming. Can you provide please a code sample on how to achieve this? I'm creating an app with a video player, and stream is working on my computer but not on the device i need to push the app to. So I would like if possible try with the load of the video entirely to rule out what is the issue I'm having, and also it doesn't hurt to know how to do this whole video load in nunustudio as well.

  Thanks

**Comment by tentone** [comment]
Hi


The video loader object is used to decode the nunuStudio serialized video objects. 
To preload the hole video when creating the texture use a Video object instead of a VideoStream
For the code in the tutorial it would be something like this.

```
	var texture = new VideoTexture(new Video("sample.mp4"));
	var material = program.getMaterialByName("default");
	material.emissiveMap = texture;
	material.emissive.setHex(0xFFFFFF);
```

I hope this helps.

Cheers

**Comment by jfa257** [comment]
Hi,

 Thanks for the quick response, I will try that.
