### ISSUE TITLE
 embedding nunu app

### ISSUE THREAD

**Issue by jfa257** [tentone/nunuStudio#227]
Hi,

I'm trying to embed nunu app with the "fast way" you provided on Tutorial:

<body onload="NunuApp.loadApp('app.nsp', 'canvas')">
    <canvas width="800" height="480" id="canvas"></canvas>

and it's working, my only issue is that its appearing on top everything else on the webapp. Any suggestions as to how put it behind the rest of the elements?

Thanks in advance!

**Comment by tentone** [comment]
Hi

Check the z-index CSS value of your canvas. Try to set the z-index values of the other elements in you application higher.

It should solve the problem. https://www.w3schools.com/cssref/pr_pos_z-index.asp

**Comment by jfa257** [comment]
Ok, will try that. Thanks
