### ISSUE TITLE
Editor theming engine

### ISSUE THREAD

**Issue by tentone** [tentone/nunuStudio#23]
This issues is to discuss what things should be themeable inside the editor and what is the better way to do it.

I was thinking to use CSS themes and attribute classes do every different type of UI element.

Another solution is to use JSON files that store some attributes of the UI elements,, it would be faster but not so versatile.

I will not work on this at least until i have a beta versions available. But since there are some issues already open regarding this i decided to create this one.

**Comment by user1713952** [comment]
I think that using CSS is the way to go to start with. Something simple, maybe taking inspiration from some really nice UIs for similar applications. Goocreate is really nice but so is playcanvas. Particularly for font and icon sizes which play a big role in making a UI pleasant to use

**Comment by Headclot88** [comment]
Why not use CSS to modify the theme of the editor and then .JSON to save them so we can share them with other devs on our team?

**Comment by tentone** [comment]
@Headclot88 Im already preparing a set of rules for css theming, to allow people to create and share themes as css files. What do you think of this approach?

**Comment by Headclot88** [comment]
Hey @tentone - As long as I can share my theme files then I am good :)

**Comment by tentone** [comment]
Moved the editor colors and style to CSS so that is can be easily costumized to create new GUI themes!
