### ISSUE TITLE
Expanding support for other input devices

### ISSUE THREAD

**Issue by jfa257** [tentone/nunuStudio#231]
Expanding support for other input devices

Hi,

 I need to either insert new keys in Keyboard.js or create a new input module altogether. The reason why I need to do this, is because I'm creating a webapp for a tizen device, and when I use the input library to register the remote keys it works, but the app freezes, because this key it's not a regular pc keyboard key.

I'm working with nunustudio 0.93 desktop version for windows, target platform is tizen OS.

 So I was considering the following options:
add the key to keyboard.js
create a new input custom module

for either of these options, I need to be able to create a new build for the desktop version. Any help in how to achieve this?
 
thanks in advance!

**Comment by tentone** [comment]
HI

Thanks a lot for reporting this.

You can open a PR with the changes that you need or you can list what are the TIZEN specific keys that you are aware of and i can add them immediatly to nunuStudio.

After that you have to move to the latest version of the editor. Right now it is a lot easier to publish new versions i can move the dev to 0.9.6 and publish 0.9.5 as it is.

Thasnk a lot.

Cheers

**Comment by jfa257** [comment]
Hi,
thanks for the quick reply. here is a list of the case code keys I need:

MediaPlayPause | 10252 |
Menu | 18
MediaRewind | 412 |
Tools | 10135
MediaFastForward | 417
 Info | 457
MediaPlay | 415 
Exit | 10182
MediaPause | 19 
Back | 10009 
MediaStop | 413 
Caption | 10221
MediaRecord | 416
ChannelList | 10073
MediaTrackPrevious | 10232
MediaTrackNext | 10233 
3D | 10199


 Ok, so you are telling me once these keys are added, I should use the web editor correct?

 thanks again!

 Jorge

**Comment by tentone** [comment]
Thanks a lot im adding them now.

Are these device specific? Have you pulled by printing or there is a API?

I will make this available for desktop as well. I have been delaying a new desktop release for a while x)

Thanks a lot

**Comment by jfa257** [comment]
Hi Tentone,

 Please let me know when you have the update available. Looking forward to version 0.9.5! :)

**Comment by tentone** [comment]
Hi

Working on it right now. Will upload it soon.

Thanks a lot!

**Comment by tentone** [comment]
Available for download. I needed to change some things before publishing.
