### ISSUE TITLE
Question: how to use updated builds on source project

### ISSUE THREAD

**Issue by jfa257** [tentone/nunuStudio#232]
followup questions about the tizen interface:

Hi,

  Thanks for adding the Tizenkeyboard class. I would like to ask you a couple of questions:

1. Currently, is this class available in the web editor?

2. I was able to successfully clone and build nunustudio, but don't know which files I need to replace (guessing …/builds/ content?)and where to use the local modified build, whether in the browser or updating the desktop files for example. Could you tell me how to do this?

3. Also , I noticed you deleted a number of keys for the remote that I need on the TizenKeboard class. I saw in the commits you added them in the keyboard class and delete them, so, do you plan on adding them back on the tizenkeyboard class?

 thanks in advance!

 Jorge

**Comment by tentone** [comment]
Hi

Yes it is already available on the web version. Im not able to test it since i dont own a tizen device.

To run the dev version you can download or clone the repository into your computer, install the JAVA JRE and NodeJS and then run "npm install" "npm run start" on your terminal to start it.

I have removed the TIZEN_ from the keys but i think that i have added all of them to the TizenKeyboard class.

Thanks a lot!

**Comment by jfa257** [comment]
Ok, thanks will try that.

**Comment by jfa257** [comment]
Hi,

 I followed your instructions and was unable to run it so far. I plan on investigating this error but maybe you know why didn't ran. Any thoughts? below its a copy of my cmd screen attempt:

 thanks in advance!

 Jorge

E:\nunusource>npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.3.1 (node_modules\7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules\7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 805 packages from 553 contributors and audited 2126 packages in 48.344s
found 11 vulnerabilities (1 low, 8 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

E:\nunusource>npm start

> nunuStudio@0.9.5 start E:\nunusource
> run --with-ffmpeg --mirror https://dl.nwjs.io/ .

Fetching NW.js binary... { platform: 'win32',
  arch: 'x64',
  version: '0.34.0',
  flavor: 'sdk' }

[============================================------] 9859.87KB/s 1.3s

Running with FFmpeg integration is not supported.
Launching NW.js app...
NW.js app exited with 0.

**Comment by tentone** [comment]
HI

Make sure that you have NodeJS 10 installed you can check by using
```
node -v
```

Try to run the following commands.
```
npm update -g npm
npm cache clear -f
npm install
npm run start
```

Thanks a lot

**Comment by jfa257** [comment]
thanks let me try it

**Comment by jfa257** [comment]
Hi,

 When running the app through node js, when using file->export, I get the following error. Any idea why?

![exp_error](https://user-images.githubusercontent.com/16959125/49686334-ece69780-fac0-11e8-9297-75fe0af6bbd5.jpg)



thanks in advance!


Jorge

**Comment by tentone** [comment]
Hi.

Just published a new version on github.

You can now download the latest release for desktop.

Thanks a lot!

**Comment by jfa257** [comment]
Hi,

thanks for the desktop release! works like a charm in regard to the tizen keys. However, this error persist. In any case I can just save the nsp file and manually copy the new nunumin.js into my project, but just letting you know this issue its still present, maybe a small thing on the path string when publishing the runtime resources, specifically vr.png.

  Hope it helps you knowing this error is persisting.

 Thanks!
