### ISSUE TITLE
 How to sort particles in front of sprites and viceversa

### ISSUE THREAD

**Issue by jfa257** [tentone/nunuStudio#234]
Hi,

 Question, I haven't looked into it personally but would like to ask you in case I get stuck:

 I have a particle effect outlining buttons in my app, and in the 0.93 version, sprites where always first in the z layering index, so particles always appeared behind them. But as it turns out, in the new 0.95 version, now particles are in front of the sprites.

 my question is: is there a parameter via script or in the material editor to control the z layering index of sprites and particles?

 thanks in advance!

Jorge

**Comment by tentone** [comment]
Hi

Yes there is just put the depth mode of the sprite to Always and it will always appear no top.

Thanks a lot
![asdasd](https://user-images.githubusercontent.com/9158354/49754443-fbde6d00-fcad-11e8-82a6-23429676c1b0.PNG)

**Comment by jfa257** [comment]
Hi, ok , thanks for the tip!

**Comment by tentone** [comment]
Here to help. Thanks a lot!
