### ISSUE TITLE
is there a way to import morphs/ vertex animation of meshes?

### ISSUE THREAD

**Issue by jfa257** [tentone/nunuStudio#235]
Hi,

   I need to make some optimizations on my app, so I was wondering:

 It's there a way to import vertex animations? Like 3dsmax morphs for example or Maya blendshapes?  I would like to know, even if requires a third party tool in the process, the morphs targets are just an example.

 thanks in advance!

 Jorge

**Comment by tentone** [comment]
Hi

Yes there is using fbx, gltf or dae files its possible to import morph animations into nunuStudio.

Thanks a lot!
