### ISSUE TITLE
Optimization on Animation

### ISSUE THREAD

**Issue by jfa257** [tentone/nunuStudio#236]
Hi,

  I have a question: Lets say I have 10 bushes animated on a scene, being each one a copy of the first I imported on the scene. So each one now is doing his own animation cycle/ iteration. So I am assuming that this translates into having 10 iteration operations running at the same time in the app. So if this is true, A good approach to optimization would be merge the 10 chars in one single mesh, having one skin modifier on 3dsmax in this case, thus being exported in FBX as a single animated model, with the intention of now run only with a single iteration operation the very same 10 meshes animated.

   my question is: is this true, what I just mentioned? If not, please share your thoughts about this, would be greatly appreciated to not invest work in a supposed optimization method which may be in turn for little difference or nothing.

 Thanks in advance!

**Comment by tentone** [comment]
Hi

Yes that is true. Each animation is processed simultaneously. Right now i don't have plan to actually make shared animations in the editor.

But for pose animations a simple way to have a performance improvement is to set the animation to only an object and use a script to copy the transformation matrix to the other objects that need the same animation.

Thanks a lot!.

**Comment by jfa257** [comment]
Thanks, i will try it!
