### ISSUE TITLE
I want nunu.js

### ISSUE THREAD

**Issue by chenxilin951207** [tentone/nunuStudio#237]
# Issue title

##### Description
 - I want nunu.js not nunu.mn.js
 - please

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by shantee** [comment]
rename it  ?

**Comment by tentone** [comment]
Hi

I can add a nunu.js (not minified) build to the repo. Give me a sec.

Thanks a lot.

**Comment by chenxilin951207** [comment]
> I can add a nunu.js (not minified) build to the repo. Give me a sec.

thank you

**Comment by chenxilin951207** [comment]
> Hi
> 
> I can add a nunu.js (not minified) build to the repo. Give me a sec.
> 
> Thanks a lot.

And I found a bug with camera in orbit。when we add the camera into orbit ，and  adjust the camera angle. then i found the camera view is not the runtime view.

**Comment by jfa257** [comment]
Hi,

 In the camera Inspector, there is a property called "use camera" It's a checkbox. It has to be enabled in order for nunu to use that camera view on runtime. 

 Hope it helps,

**Comment by chenxilin951207** [comment]
thanks
