### ISSUE TITLE
orbit has a child camera pointing +z upon run, but When I press run, the camera automatically faces +x

### ISSUE THREAD

**Issue by chenxilin951207** [tentone/nunuStudio#238]
# Issue title

##### Description
I'm trying to setup a orbit camera upon run to face the +z direction. The orbit rotation is [0, 0, 0]. The camera's rotation is [0, 0, 0].

but When I press run, the camera automatically faces +x. Could you help?

##### Version
 - 0.96

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hi.

Im aware of this problem, but i totally forgot to fix it.

Thanks a lot for reminding.

Happy holidays.

Cumps

**Comment by chenxilin951207** [comment]
> Hi.
> 
> Im aware of this problem, but i totally forgot to fix it.
> 
> Thanks a lot for reminding.
> 
> Happy holidays.
> 
> Cumps
14 days passed, please fix this bug

**Comment by chenxilin951207** [comment]
14 days passed, please fix this bug

**Comment by shantee** [comment]
If I may , you have to understand  Nunustudio is  a (great) one person , open source project .  
I imagine the author (Tentone) is doing it during his free time. 
We can't blame him if he decides to take a break or even stop taking care of it (even though that would be a shame because we're all eager to see the next version ^^).

**Comment by chenxilin951207** [comment]
> If I may , you have to understand Nunustudio is a (great) one person , open source project .
> I imagine the author (Tentone) is doing it during his free time.
> We can't blame him if he decides to take a break or even stop taking care of it (even though that would be a shame because we're all eager to see the next version ^^).

Because this bug is too difficult to solve,I just pleaded with the author to fix it.

**Comment by tentone** [comment]
Hi There

Sorry, i have been a bit busy lately and took a small Christmas break.

I will look into i soon.

Thanks a lot. Happy new year.

**Comment by tentone** [comment]
Hello, i added the option to control the initial orientation of the orbit controls object.

Should be enough to fix this problem.

Still figuring out a better way to preview the initial position of the container.

Thanks a lot!

**Comment by chenxilin951207** [comment]
> Hello, i added the option to control the initial orientation of the orbit controls object.
> 
> Should be enough to fix this problem. (Already available on the web version)
> 
> Still figuring out a better way to preview the initial position of the container.
> 
> Thanks a lot!

Thanks  thanks thanks  a lot. Happy new year.
