### ISSUE TITLE
3d model Import bug

### ISSUE THREAD

**Issue by jfa257** [tentone/nunuStudio#239]
3d model Import bug

 Hi,

 Just found out that no matter if its boned or vertex animation on the fbx, if after you import an animated model, you delete the material it creates when imported, and assign another one, properly setting the checkbox in either skinning or morph targets on the material properties, No animation is displayed anymore, neither in the animation tab or when running the project. Right now the working workaround is assign proper resource texture to created material on import, but this should not be happening, that's why I reported it anyways.

version 0.95 desktop
Platform Windows 10

**Comment by tentone** [comment]
Hi

I will have to take a look at this, do you have some fbx test file that i can use?

Thanks a lot.

**Comment by tentone** [comment]
Hello

This bug has been fixed in the last version of the editor.

Thanks  a lot for reporting

![zxczczc](https://user-images.githubusercontent.com/9158354/80810638-322ace00-8bbc-11ea-8a05-3a01f4dfcc6a.PNG)

**Comment by jfa257** [comment]
great!
