### ISSUE TITLE
Interface bug

### ISSUE THREAD

**Issue by jfa257** [tentone/nunuStudio#240]
Hi,

 Also found out a crash bug on the desktop version, when you follow this flow:

File-->Load-->Cancel (after hit ok on the would be lost changes dialog) app exits.

Windows 10, version 095 desktop

thanks in advance! and Merry Christmas!

 Jorge

**Comment by shantee** [comment]
good news ! can't reproduce it on Linux . Merry Christmas all

**Comment by jfa257** [comment]
Lol

**Comment by tentone** [comment]
Please try the new windows release (updated 0.9.5) should be working fine now.

**Comment by jfa257** [comment]
thanks Tentone, appreciate it!
