### ISSUE TITLE
Select multiple material / ressources 

### ISSUE THREAD

**Issue by shantee** [tentone/nunuStudio#241]
Hello 

This is not really an issue but maybe an idea for next update.
Would it be possible to select multiple elements in the materials / resource panel ?
That would be useful in order to delete many things in a single click.

Thanks !

**Comment by tentone** [comment]
Hi

Its already possible to select multiple objects/resources and delete them in a single click.

Just keep the CTRL key pressed while selecting them and then use the DEL key do delete.

Thanks a lot.

Cheers
