### ISSUE TITLE
Can't publish (web) error ENOENT ...

### ISSUE THREAD

**Issue by shantee** [tentone/nunuStudio#242]
Hello 
An other weird error. I don't know what is happening.
I have tried to completely delete nunuStudio , clear npm cache and and update it but I can't publish my project :(
I keep getting this error :
```

Error exporting project
(Error: ENOENT: no such file or directory, copyfil "runtime/vr.png" [....] 
```
Any idea what is wrong ? 

##### Platform
 - Linux [X]

**Comment by chenxilin951207** [comment]
you can edit  ' Editor.runtimePath = "runtime/" '   in  source/editor/Editor.js .
Or edit publish  function

**Comment by shantee** [comment]
Thanks a lot Chenxilin and Happy new year to everybody here !
It helped me solve my problem and also understood that I could also simply save my project directly in the publish folder (no need to "publish" every time) :)
I still don't know why it happened at first (maybe a bug ?)

**Comment by tentone** [comment]
Hi.

This is a bug thanks a lot for reporting. I forgot to change the runtime path.

Cheers

**Comment by tentone** [comment]
Fixed, thanks a lot!
