### ISSUE TITLE
Which physics engine is used by nunu studio?

### ISSUE THREAD

**Issue by chintan-jagad** [tentone/nunuStudio#243]
# Issue title

##### Description
 - Please search the issue list before posting a new issue, to avoid collisions.
 - Explain your problem, suggestion or question.
 - If possible provide information about how to recreate the problem, sample isp project files etc.

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hi

nunuStudio is using cannon.js as  physics engine.

Thanks a lot.

**Comment by chintan-jagad** [comment]
Hi
Me and my friends are trying to create a website similar to nunustudio.
Should I use Physijs or Cannon.js for physics?
And why do you choosed Cannon.js?

**Comment by tentone** [comment]
Hi

Right now i would go for https://github.com/kripken/ammo.js/ which is WASM based, the code is a bit big but it has a really good feature set, is still supported, is based of a great C++ engine (bullet) and is reasonably fast.

BUt if you want a pure JS based engine i would go for CannonJS or https://github.com/lo-th/Oimo.js/ booth are great.

Thanks a lot!

**Comment by chintan-jagad** [comment]
Thanks for your help.
I am not able to find proper documentation or Cannon.js its very difficult to understand can u help me out?
