### ISSUE TITLE
Disable texture resizing at runtime to not look blurry

### ISSUE THREAD

**Issue by jfa257** [tentone/nunuStudio#245]
Hi,

 I would like to know how to disable the resize of the textures at runtime, since its causing mi sprites to look  poor.

 Thanks!
 version: 0.95
 platform: desktop

**Comment by tentone** [comment]
Hi

Texture always need to be resized to fit power of 2 sizes in webgl 1.0, for webgl 2.0 the resizing will be disabled in threejs soon and that will affect nunu as well.

But usually thats not a problem have you tried to fiddle with the texture settings? Sometimes mipmaps are not good for distant texture that contains text for example.

Thanks a lot!

**Comment by jfa257** [comment]
Hi,

Thanks for the tip, definitively modifying the mipmap settings did the trick. True, disabling the resizing request may have been a little bit overkill. But yes, it would be great be able to display NPOT (non power of two for the curious beginner :) ) sprites without the engine enforcing POT.

 thanks!

Jorge
