### ISSUE TITLE
Z layer by index ordering sprites

### ISSUE THREAD

**Issue by jfa257** [tentone/nunuStudio#246]
Hi,
 As the title mention, I would like to know if there is currently a feature enabling me to z-layer-ordering sprites using an integer for example. I know of z-index style property, should I use this or there is something in the engine to achieve this?

 thanks!

**Comment by tentone** [comment]
Hi

I have added support for the render order property in the online editor. If you have depth test disabled for the sprite material you should be able to used this property (accessible on the object inspector) to sort the order.

Thanks a lot for reporting.

Cheers

**Comment by jfa257** [comment]
Ok, cool
