### ISSUE TITLE
Inspector mixed up with Explorer

### ISSUE THREAD

**Issue by kungfooman** [tentone/nunuStudio#247]
Hi, whenever I change a setting in the Inspector (e.g. light intensity) then it breaks the layout. It looks like this then:

![nunu_inspector](https://user-images.githubusercontent.com/5236548/51517379-ca170500-1e1a-11e9-9754-087b00f063ec.png)

Tested the editor version on your website in Chrome

**Comment by tentone** [comment]
Hi

I touth that this bug was fixed a while back. Does it happen on the web online version as well? What version are you running?

Thanks a lot for reporting.

Cumps

**Comment by tentone** [comment]
Hi

Yeah youre right there are still some problems with the editor on some attribute updates.

Will try to fix it as soon as possible. Thanks a lot !

Cumps

**Comment by tentone** [comment]
Hi.

The bug should be now fixed on the last web version.

Thanks a lot for reporting.
