### ISSUE TITLE
Animation of style properties inside nunu scripts

### ISSUE THREAD

**Issue by jfa257** [tentone/nunuStudio#249]
Hi,

I have the following code:

function update()
{
  if(animating){
	  UpdateContentMenu();
  }
}

function UpdateContentMenu()
{
	var content = document.getElementById("contentDayInfo");
	if(animationClock.getElapsedTime() < 15){
		content.textContent = "animation!!! " + animationClock.elapsedTime.toString();
		content.style.opacity = content.style.opacity + 0.1;
	} else {
		animationClock.stop();
		animating = false;
	}
	
}

 then, my goal is to animate the opacity parameter of the text style, the content element. I'm seeing updates on the textcontent property with the elapsedtime, but not seeing updates on the opacity parameter. Any idea why this is happening?

  thanks in advance!

 Jorge

**Comment by tentone** [comment]
Hi

Be carefull CSS styles are always string values.

When you use content.style.opacity + 0.1; youre are actually concatenating strings.

>> var a = document.createElement("div");
undefined
>>a.style.opacity
""
>>a.style.opacity = 0.1
0.1
>>a.style.opacity
"0.1"
>>a.style.opacity += 10;
"0.110"
>>a.style.opacity
"0.11"

**Comment by jfa257** [comment]
ok then I need to parse strings and the browser engine will convert the values for the opacity correct?

**Comment by tentone** [comment]
Yes. You need to parse the values on the style.opactity attribute or simply keep it stored in a variable localy as a number.

**Comment by jfa257** [comment]
Cool thanks!
