### ISSUE TITLE
Orthographic Camera

### ISSUE THREAD

**Issue by eightxiao** [tentone/nunuStudio#250]
#Hi, Why do I set up an Orthographic Camera and still display the 3D effect when running?

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hi 

You have to toggle the option "Use camera" in the object panel in order to actually use that camera when running the application.

Thanks a lot!

**Comment by eightxiao** [comment]
Sorry, in Perspective Camera, I can see the "Use camera" option in the objects panel. But I don't see any of the options in the Orthographic Camera. This is the question that has been troubling me.
![image](https://user-images.githubusercontent.com/10458110/51983644-33121300-24d4-11e9-9d45-92c8bc9107f9.png)
![image](https://user-images.githubusercontent.com/10458110/51983654-3c02e480-24d4-11e9-8875-ea1c39d8d092.png)

**Comment by eightxiao** [comment]
I found that I could see attributes in Web Version, but there were no attributes in desktop version. Thanks！
