### ISSUE TITLE
assign custom font on the editor does not work

### ISSUE THREAD

**Issue by jfa257** [tentone/nunuStudio#251]
Hi,

 Working with text objects right now, noticed I can't assign custom fonts to the text objects on the editor, so now have to initialize the texts and setup fonts by script, can't we have a field to either type the font name as a string or drop the resource font there from the assets tab, like with textures for example?

Version: Desktop 0.95
OS: Windows 10 x64 bit

 thanks!

**Comment by tentone** [comment]
Hi

Its possible to drag and drop ttf, otf fonts into the editor already and apply them to the text elements by drag and drop.

Thanks a lot

Cheers

**Comment by jfa257** [comment]
Yes, I tried that and it does not work for me, maybe its the desktop version.  I have a ccs file where I declare fontface properties, but I wanted to use more than one font, one for certain text objects. Can this be related to the issue?

**Comment by tentone** [comment]
You cannot use the fonts imported to the editor with CSS. I really need to improve the flux with HTML/CSS im currently working on a HTML layer with CSS3D for nunuStudio but still needs a lot of work.
