### ISSUE TITLE
`focus` of Bokeh has no effect

### ISSUE THREAD

**Issue by seven-two-eight** [tentone/nunuStudio#257]
##### Description
I tried ranges of `focus` values for the Bokeh pass of a perspective camera from `0.1` to `1`, from `1` to `10` and from `10` to `100`,
but the blur in the render does not seem to be affected.

test scene: [focus-test.zip](https://github.com/tentone/nunuStudio/files/2849287/focus-test.zip)

##### Version
Version 0.96 Build 201902101516
Web Version

not sure if i'm using Bokeh correctly
thanks for the great work!

**Comment by tentone** [comment]
Hi

The bokeh effet pass is tricky to use since the values are really sensible i will try to add an auto focus point option, should help for people to use it.

Currently it is almost impossible to use it properly.

Thanks a lot.

**Comment by tentone** [comment]
Bokeh effect box includes now a slider for easier adjustment of these parameters.

Thanks a lot.

Cheers
