### ISSUE TITLE
Material not shown

### ISSUE THREAD

**Issue by eightxiao** [tentone/nunuStudio#259]
Hi,
Sorry to bother you. I have a problem.

Why do I import FBX files and add materials that are not displayed?  Texture cannot adjust UV. What shall I do?

version 0.95 desktop
Platform Windows 10

**Comment by tentone** [comment]
Hi

Can you please provide an example FBX file and a screeshot?

Youre missing materials that are in the FBX file correct?

Thanks a lot!

**Comment by eightxiao** [comment]
Hi
 I imported Building.fbx into example.nsp and added the material named Object004. But it did not show. Also import it into C4D, add material can be displayed.
[FBX example.zip](https://github.com/tentone/nunuStudio/files/2862936/FBX.example.zip)

**Comment by eightxiao** [comment]
The problem has been solved, not bug. Thank you.
