### ISSUE TITLE
Support for post-processing effects

### ISSUE THREAD

**Issue by tentone** [tentone/nunuStudio#26]
# Support for post-processing effects

##### Description
 - Support for threejs post-processing effects in nunuStudio
 - Post processing effects can be attached to camera objects
 - Camera Editor tab with test scene for previewing post processing effects for that camera, 
 - Post processing effect objects stored in an array

**Comment by brylie** [comment]
In 3D, animated, or multimedia projects, it is sometimes useful to perform a series of effects or create composite output from several inputs. To support this type of workflow, in an intuitive way, various multimedia applications provide node-based graphical interfaces. 

# Examples
Some examples of compositing or data-flow user interfaces include:

- Blender3D [node-based compositor](https://docs.blender.org/manual/en/dev/compositing/index.html) - create data pipelines for visual effects, etc.
- [NATRON](https://natron.fr/) - node-based compositor, similar to Adobe After Effects 
- [NodeRED](http://nodered.org/) - flow based programming environment

# Related issues
Related to issue #26: Support for post processing effects
Possibly related to issue #27: Parameter graph editor UI

**Comment by tentone** [comment]
Post processing implemented in the camera editor tab
![capture](https://user-images.githubusercontent.com/9158354/33039168-0255d708-ce2f-11e7-8e22-5c84d1366f7d.JPG)
