### ISSUE TITLE
Audio doesn't stop when click on stop 

### ISSUE THREAD

**Issue by shantee** [tentone/nunuStudio#261]
Hello,

I am still having some troubles understanding how to manipulate sound (add a music to a scene etc...), but I think I have found a bug.
When I click "run" the audio doesn't stop when I exit the scene (by clicking "stop") . Is there a method to stop a music ?
Thanks

**Comment by tentone** [comment]
Hi

This is a knwon bug thank a lot for reporting i will fix is as soon as possible.

Thanks a lot!.

Cheers

**Comment by tentone** [comment]
Should be fixed now (web version). Thanks a lot!
