### ISSUE TITLE
Something wrong with Learn Tab

### ISSUE THREAD

**Issue by SomeDoge** [tentone/nunuStudio#262]
So, in your learning tab, there is something wrong with your timeline tutorial, so I don't know how to use it. Please fix it or give me alternative instructions.

**Comment by tentone** [comment]
Hi

The timeline animation was actually empty.

I have just created a first version of the tutorial really simple explaining the basics with an example file. 

Should be enough to explain how to get started with the feature.

Thanks a lot.

Cheers

**Comment by SomeDoge** [comment]
@tentone hey, is there any way to trigger an animation from code?

**Comment by tentone** [comment]
Yes there is i will add a code exampple to the tutorial exaplaining how to play and pause animations.

**Comment by SomeDoge** [comment]
@tentone thanks

**Comment by SomeDoge** [comment]
@tentone by the way, have you heard about lance.gg? Maybe you can add it to the embedded libraries so multiplayer will be so much easier.

**Comment by tentone** [comment]
Yeah i have heard of it before.

You should actually be already able to use it nunuStudio allows for external libraries to be imported into the project. The integrations should be done via script.

I have updated the timeline tutorial to include a simple playback control example.
