### ISSUE TITLE
"include" or "import" ? Difference between "Library Mode"

### ISSUE THREAD

**Issue by shantee** [tentone/nunuStudio#265]
Hello.
In a script when I want to add an external JS file I use 
include("myfile.js);
Should I use import ? 

Also I am wondering what are the different "Library Mode" for a script ?  Which one is "the best" ? 
Shall I use the include mode if I use the keyword include to add a script ?
Thanks

**Comment by tentone** [comment]
Hi

Use the include() method it is the intended to import code.

Library mode controls how that code gets imported to the script. Append mode is the safest is just appends the code to you script and runs everything on that context.  Evaluate uses eval() to evaluate the code on initialization of the script. And include adds the code to the global scope making it available for everything even after the application stops.

**Comment by shantee** [comment]
Thanks a lot !
