### ISSUE TITLE
How to start Nunustudio with a specific file 

### ISSUE THREAD

**Issue by shantee** [tentone/nunuStudio#266]
Hello

I would like to know whether it is possible to start nunustudio with a specific file (for example the program I am working on). 
For example that would be great if we could do :
npm start --file /home/something/myfile.nsp

**Comment by tentone** [comment]
For the desktop version i belive that is already possible to open a project file as argument.

But for dev there is no solution currently. I will try to add it as argument.

**Comment by tentone** [comment]
Hi

Thanks a lot for reporting, this bug has been fixed in the last version of the editor.

Cheers
