### ISSUE TITLE
Very annoying glitch

### ISSUE THREAD

**Issue by SomeDoge** [tentone/nunuStudio#269]
So, with the new update if you make a mistake in update function code, you will be stuck with alerts showing endlessly, so I need to reload the page. Please fix it as soon as possible, thanks

**Comment by tentone** [comment]
Hi

Sorry about. Fixing it right now i should start testing the editor more carefully after these changes :/

Sorry about it. Tahnks a lot for reporting the error.

Cumps

**Comment by tentone** [comment]
Should be fixed now (web version)
