### ISSUE TITLE
Parameter graph editor UI

### ISSUE THREAD

**Issue by brylie** [tentone/nunuStudio#27]
Some scene parameters change over time, such as camera location. nunuStudio can offer a 'parameter graph editor UI' to help animators fine-tune parameter transitions. 

# Examples
## Blender3D
This idea is best illustrated by the Blender parameter graph UI (a.k.a. [F-Curves](https://docs.blender.org/manual/en/dev/editors/graph_editor/fcurves/introduction.html)):
![Blender parameter graph UI](https://docs.blender.org/manual/en/dev/_images/editors_graph_example.jpg)

## Synfig Studio
![peek 2017-03-06 17-13](https://cloud.githubusercontent.com/assets/17307/23615807/58abc934-0290-11e7-914d-4199a9c82725.gif)

**Comment by tentone** [comment]
Hi @brylie 

This would be really neat 👍 

What if i implement this as a animation object that can be used as a normal object (similar to containers) but its possible to controll its position, rotation and size using a graph editor similar to the one above?

It would require me to change the editor UI layout to support the graph editor alongside the scene explorer but it would be totally worth!

Thanks

**Comment by brylie** [comment]
Right on. Is there any way I can help with this feature? I am familiar with JavaScript to a certain extent.

**Comment by tentone** [comment]
I belive there is something similar inside threejs already with support for multiple interpolations i have to check it. If not i will implement it first as a programming API and after i will move it to UI.

If you want i can leave it for you to try to implement something, and i help you with whatever you need!

(Just for reference https://twitter.com/tentonej/status/834563874343022592)

**Comment by brylie** [comment]
Hm, I will start with some research.

**Comment by brylie** [comment]
There are a few of open source UI component libraries, for diagramming, that provide 'bezier' graph UI components, including:

- [Bezier.js](http://pomax.github.io/bezierjs/)
- [JointJS](https://www.jointjs.com/opensource)
- [mxGraph](https://github.com/jgraph/mxgraph)

**Comment by brylie** [comment]
It is also possible to build a UI component using a lower level graphical library, such as:

- [Raphaël](http://dmitrybaranovskiy.github.io/raphael/)
  - [Graffle example](http://dmitrybaranovskiy.github.io/raphael/graffle.html)
  - [Curver example](http://dmitrybaranovskiy.github.io/raphael/curver.html)

**Comment by tentone** [comment]
@brylie Im trying to avoid any libs for the UI, graphs are easy to draw i have already an internal component for that (used in the particle editor)

**Comment by brylie** [comment]
Alright. I am just speculating that a good graph library might be useful for another idea:

https://github.com/tentone/nunuStudio/issues/28

**Comment by tentone** [comment]
@brylie Im thinking to add the animation system as something similar to this https://threejs.org/examples/#misc_animation_authoring what do you think?

**Comment by brylie** [comment]
Looks really cool! Kind of like the keyframes/curves UI.

Relatedly, I also like that it is easy tointeract with the 3D scene on a touchscreen, e.g. moving the cube around by its transform handles.
