### ISSUE TITLE
Switching between scenes

### ISSUE THREAD

**Issue by shantee** [tentone/nunuStudio#270]
Hello
Imagine a project with 2 or more scenes. How can I call (switch to) an other scene and make it start ?
For example in "scene1"  when camera reaches a certain point how can I activate "scene2" (it will contains a different camera)

Thanks a lot!

**Comment by tentone** [comment]
Hi

To start up with scene 2 select the scene in tree and set is as the "Default scene". That makes it the first scene to be loaded when running the program.

Cheers

**Comment by shantee** [comment]
Thank you for your reply.
Yes I understand that.
But how to define the end of the default scene and start the next one ? 
How to "say in a script" : OK now discard the default scene and start playing the next one ?

**Comment by tentone** [comment]
To switch between scene you can use the program.setScene()  method


```
function update(delta)
{
	if(Keyboard.keyPressed(Keyboard.W))
	{
		program.setScene("scene2");
	}
}

```

**Comment by shantee** [comment]
Thanks a lot !  I still haven't had time to try but I will. I believe this is what I needed.
