### ISSUE TITLE
Making a demoscene with Nunustudio ?

### ISSUE THREAD

**Issue by shantee** [tentone/nunuStudio#271]
Hello again,
I love Nunustudio and I also love the demoscene !  I will intent Revision 2019 and I would love to make a demo with Nunustudio. 
A couple of years ago I made a kind of demo (but I did not present it to any demoparty). I used a great tool called GooCreate. Unfortunately this project has been abandoned  and it was not opensource :(
I made this : http://www.shantee.com/cv

So here is my question, do you think I could make something similar (and hopefully better) with nunuStudio ? Are big files problematic ?

**Comment by tentone** [comment]
Hi 

The demo you made on goocreate looks really nice. Goo create was actually purchased by amazon and it now named Amazon Sumerian  (https://aws.amazon.com/sumerian/).

I think that you can do something similar with nunuStudio big files are usually not a problem with nunuStudio, altough everything gets stored as single file and it needs to be downloaded up ahead, during runtime everything should run smoothly.

**Comment by shantee** [comment]
Thanks a lot   ! 
I did not know this. I just tried and I am very disappointed with what they did to the original gooCreate. I loved gooCreate because (amongst other things) it was practical and convenient . You could easily construct your project  inside the interface and export to make it a web page in one click. NunuStudio does that too and it seems it is even possible to export for Android (I still haven't' tried it yet)

The animation you saw is about 15Mb uncompressed and  my demo project should no be over 20Mb
 I ll keep exploring nunuStudio and hopefully I with make something nice with it..
