### ISSUE TITLE
Unable to see nunuStudio page correctly

### ISSUE THREAD

**Issue by ikelaiah** [tentone/nunuStudio#272]
# Unable to see nunuStudio page correctly

##### Description
 - The nunuStudio landing page is not showing correctly. The 3D demo is not showing. 
 - The console shows u.viewport.fromArray is not a function
- Tested with Firefox 65.0.2
- Testes on Chrome 72.0.3626.121 (Official Build) (64-bit)

![2019-03-06 08_32_36-nunustudio](https://user-images.githubusercontent.com/32469901/53839087-bdc1c280-3fea-11e9-913f-b7ffbdc2181c.png)

![2019-03-06 08_38_46-nunustudio](https://user-images.githubusercontent.com/32469901/53839294-493b5380-3feb-11e9-8b1a-01191b8c215e.png)

##### Version
 - Current webpage as for 2019-03-06.

##### Platform
 - Web Version [X]

**Comment by tentone** [comment]
Thanks a lot for reporting! Should be fixed now!
