### ISSUE TITLE
Some bugs in program > inspector panel

### ISSUE THREAD

**Issue by shantee** [tentone/nunuStudio#275]
I found some bugs in the program inspector.
1) When you click (check) on a case the panel will disappear.
2) The tooltip info bubble are displayed on  a single line hence when the text is too long we can't read it.
3) Some options are not readable even when the panel is resized 
 (for exemple : Auto clear ... )

**Comment by tentone** [comment]
Thanks a lot for reporting will try to fix it soon.

**Comment by tentone** [comment]
Fixed the program panel and tool tip bugs.

I have to work on the forms to resize the text area better. Thanks a lot!
