### ISSUE TITLE
Error log 

### ISSUE THREAD

**Issue by shantee** [tentone/nunuStudio#276]
Hello

Is there a way to access some error log of nunuStudio ? 
Sometime the program crashes. It simply closes itself. So it would be interesting to have a clue why it crashes.
I start nunustudio from my terminal (npm start) but even in the console there's no info

**Comment by tentone** [comment]
Hi

Unfortunately sometime NWJS closes because of errors and does not provide any error log or information. 

I still dont have a good way to debug these situations, i tought aboud moving to electron for a while, but there are a couple of good reasons for me to stay in NWJS for now.

Thanks a lot
