### ISSUE TITLE
Import 3D model, plane lost

### ISSUE THREAD

**Issue by eightxiao** [tentone/nunuStudio#278]
Hi,

When I import the 3D model, a plane is lost. The 3D model is an obj file exported from SketchUp. When I open it in C4D, the model is complete. When importing nunuStudio, something is missing.
Attached is my obj file.

Thanks!
![image](https://user-images.githubusercontent.com/10458110/54361342-cb89de80-46a1-11e9-80f8-608e1447dc81.png)

![image](https://user-images.githubusercontent.com/10458110/54361684-80240000-46a2-11e9-97a9-46414a871a86.png)
[Example.zip](https://github.com/tentone/nunuStudio/files/2966675/Example.zip)

version 0.95 desktop
Platform Windows 10

**Comment by jfa257** [comment]
Hi,

 I tried to import your obj in 3dsmax 2017, and it says ERROR: invalid normals index. There is no reason for that to happen unless a specific Cinema4D mesh parameter was enabled at the time of import. Hope it helps clear the issue.


![importError](https://user-images.githubusercontent.com/16959125/54385869-0b36d300-466e-11e9-90b0-c3d400250a01.jpg)

**Comment by eightxiao** [comment]
@jfa257  Thank you very much. The problem has been solved.

**Comment by jfa257** [comment]
you're welcome :)
