### ISSUE TITLE
Unable to export using nunuStudio 0.9.5

### ISSUE THREAD

**Issue by ikelaiah** [tentone/nunuStudio#279]
# Unable to export using nunuStudio 0.9.5

##### Description
 - Unable to publish project to web, ended up with error; `No such file or directory`

Please see screenshot.

![2019-03-19 15_41_27-Window](https://user-images.githubusercontent.com/32469901/54580946-7f062080-4a5e-11e9-9a02-caea699b56cb.png)

##### Version
 - 0.9.5 (201812092016)

##### Platform
 - Windows [X]

**Comment by ikelaiah** [comment]
I got it working by changing the following line in `nunu.editor.min.js`
From ...

```
Editor.runtimePath='runtime/'; 
```

to

```
Editor.runtimePath='source/runtime/';
```

**Comment by tentone** [comment]
Hi

Thanks a lot for reporting the problem it is fixed on last version but i still havent updated the desktop version should probably do a V0.9.6 release soon.

Thanks a lot.

Cheers
