### ISSUE TITLE
Node-based effects pipelining/compositing UI

### ISSUE THREAD

**Issue by brylie** [tentone/nunuStudio#28]
In 3D, animated, or multimedia projects, it is sometimes useful to perform a series of effects or create composite output from several inputs. To support this type of workflow, in an intuitive way, various multimedia applications provide node-based graphical interfaces. 

# Examples
Some examples of compositing or data-flow user interfaces include:

- Blender3D [node-based compositor](https://docs.blender.org/manual/en/dev/compositing/index.html) - create data pipelines for visual effects, etc.
- [NATRON](https://natron.fr/) - node-based compositor, similar to Adobe After Effects 
- [NodeRED](http://nodered.org/) - flow based programming environment

# Related issues
Related to issue #26: Support for post processing effects
Possibly related to issue #27: Parameter graph editor UI

**Comment by tentone** [comment]
@brylie Hi

Lets discuss this on the issue #26 since they are related, i will close this one and quote your comment there!

Thanks
