### ISSUE TITLE
Extremely needed feature

### ISSUE THREAD

**Issue by jfa257** [tentone/nunuStudio#280]
Hi Tentone,

 I don't know if there is currently a way to do this, but, I think you need to implement a search string feature inside the script editor. Right now I have this huge script and it's painful finding things. I know maybe I can distribute code among smaller scripts, but right now this is not the case for me. So if there is any chance you can do this, the sooner the better, I believe the nunu user community and specially myself of course will be really happy with this feature.

 thanks in advance!

**Comment by ikelaiah** [comment]
Great suggestion! This feature would be useful.

In the meantime, on linux I'd use

```
grep -rl "string you want to search" /path
```

On Windows, Powershell; (https://antjanus.com/blog/web-development-tutorials/how-to-grep-in-powershell/)[https://antjanus.com/blog/web-development-tutorials/how-to-grep-in-powershell/]

**Comment by tentone** [comment]
Hi xD

Well we already have this x) i should probably document the editor better or add some buttons to it.

CTRL + SHIFT + F -> Replace Once
CTRL + SHIFT + R -> Replace All
CTRL + F -> Find

I hope this helps. I will try and add this to the documentation.

Thanks a lot!

**Comment by tentone** [comment]
![Capture](https://user-images.githubusercontent.com/9158354/54644651-b8a44f00-4a91-11e9-8659-1c00efe2e068.PNG)

Added an option to editor dropdown menu, should be available soon on the web version

**Comment by jfa257** [comment]
Cool!

**Comment by jfa257** [comment]
Could that be included in 0.9.6 for desktop ? :):)  I tried CTRL + f , but since I've been  working on the desktop version, that's why I found no solution for it. It does work on the web version, just tested it.

 Thanks!

**Comment by jfa257** [comment]
I know google now wants everybody even play online without anything installed on the pc, but old school pros feel more at comfort working on the desktop standalones :), hehe, so I would recommend some update love on the desktop version. Still, great work so far either way. 

thanks for all your great work!

**Comment by tentone** [comment]
Hi

You should already be able to use the CTRL+F on the desktop version, this features has been available pretty much since the first versions of the editor. Try also CTRL + SHIFT + F. I will try and update to 0.9.6 today or tomorrow, will just take some time later today to clean up the animation timeline GUI that is really bad xD
 
I totally agree i also prefer to run my production application locally, is far more convenient for file access and integration with other applications in my opinion.

Thanks a lot for the feedback.

**Comment by jfa257** [comment]
You're most welcome buddy. Ok, if I do  CTRL + SHIFT + F, it says replace,
not find, jfyi and  CTRL + SHIFT + R it's replace all!. Dunno how to use
it, guess will figure it out trying hehe.

Thanks!
