### ISSUE TITLE
nunuStudio exits after pressing cancel button, lightmap support?

### ISSUE THREAD

**Issue by comsyspro** [tentone/nunuStudio#281]
# nunuStudio exits after pressing cancel button

##### Description
1.) When cancelling any of the popup windows (for example textures select and then canceling) the main application nunuStudio exits so that all configurations are deleted.

2.) Is it also possible to use baked lightmap in the material settings? I didn't found there any lightmap option which can be selected. How to do this?

##### Version
nunuStudio_0.9.5_win_x64

##### Platform
 - Windows [X]

**Comment by shantee** [comment]
Yes I also noticed it (#1) on Linux with the npm version.  (that's also why we need an auto save feature :))

**Comment by comsyspro** [comment]
Ok, so this is probably a coding error. And what about the **lightmap texture option** in the materials. Is there a way to set up the lightmap texture or will this come in future and is still in development?

**Comment by tentone** [comment]
There are not lighmap generation support inside of nunuStudio.

The back problem is NWJS im trying on windows i am currently running a older nwjs have to check if that version has any problem on linux.

Thanks a lot!

**Comment by tentone** [comment]
Hi

Thanks a lot for reporting, the problem with the window closing after file dialog cancel has been fixed in the last version of the editor.

Cheers
