### ISSUE TITLE
Using Post Processing Library

### ISSUE THREAD

**Issue by shantee** [tentone/nunuStudio#287]
Hello
Is to possible to use this postprocessing library with Nunusutdio ?  
https://github.com/vanruesc/postprocessing
I can't make it work in Nunustudio.

(I know there several effect on the camera tab but they don't seem to work , I get a black screen most of the time)
Thanks a lot

**Comment by tentone** [comment]
Hi

In theory everything that works with threejs works with nunuStudio sometimes it might be unpractical to use some libs due to the fact that used does not control the renderer directly.

Cheers
