### ISSUE TITLE
How to change material type?

### ISSUE THREAD

**Issue by panbeep** [tentone/nunuStudio#288]
How to change material type?

Hi, is there a way to change a type of a material on already created material? For example I imported a scene that has few hundred objects with the same material and I wanted to change the type of it to another. I can't find the proper option for this.

**Comment by tentone** [comment]
Hi

Currently, there is no option to change the type of materials.

Material properties are usually different. I can add a new option to convert and copy the same attributes between material types, would that be usefull?

Cheers

**Comment by panbeep** [comment]
No, this would not solve the problem. Maybe there could be an option to change the default material type during ore before importing a 3d file?

**Comment by tentone** [comment]
Some 3D files actually specify the type of material that they want to use. There is no default type. Different 3D use the appropriate material to keep the appearance as close as possible to the source.

**Comment by panbeep** [comment]
What would be the preferable import format for PhysicalMaterial? glTF?

**Comment by tentone** [comment]
Yes por PBR i would use gLTF it is the better-supported format.

**Comment by panbeep** [comment]
Ok, thank you for the information.

**Comment by panbeep** [comment]
I exported a 3d model from Blender 2.8 in glTF format with Principled BSDF material in it and in you editor it shows as standard material.

**Comment by tentone** [comment]
Standard material is the basic PBR material in nunuStudio. Principled BSDF is blender specific shading model, it will not be exactly the same but should be close on thesame attributes.

**Comment by panbeep** [comment]
Ok, I see. Thanks!
