### ISSUE TITLE
Does nunuStudio uses the full three.js library ?

### ISSUE THREAD

**Issue by shantee** [tentone/nunuStudio#289]
Hello,

I read a lot of three.js documentation and examples and I noticed that nunuStudio is missing a lot of files compared to three.js
For example : 

https://github.com/mrdoob/three.js/tree/master/examples/js/postprocessing

As you can see in this folder there are a lot of postprocessing effects but they are missing in nunuSutdio ?
Why not including the complete three.js inside nunusutdio that way we could easily add any effect inside scripts ?

**Comment by tentone** [comment]
nunuStudio uses threejs, it does not implement all the "extra" modules of threejs.

The post procesing pipeline of nunuStudio is different from the one in threejs.
