### ISSUE TITLE
Support for scene 3D model export

### ISSUE THREAD

**Issue by tentone** [tentone/nunuStudio#29]
# Support for 3D model export

##### Description
 - Support for obj export using threejs OBJExporter / STLExporter
 - This features can be usefull for some 3D prototyping inside nunuStudio (specially using the web version)

**Comment by tentone** [comment]
Added OBJ exporter to the editor. STL exporter needs some work to support BufferGeometry.

**Comment by brylie** [comment]
Really cool! :smile:

**Comment by tentone** [comment]
Updated STLloader meged into three.js
