### ISSUE TITLE
How to create 2d text other than html elements ?

### ISSUE THREAD

**Issue by jfa257** [tentone/nunuStudio#291]
is this possible right now? If it is, how?

 Thanks!

**Comment by tentone** [comment]
Currently the TextMesh object supports 2D mode without 3D extrusion, i have also in development support for SDF text rendering wich allows for low memory, high quality font rendering for 2D fonts.

Thanks a lot!

![asasd](https://user-images.githubusercontent.com/9158354/55822483-9b462c00-5af7-11e9-9f3e-a1fff2c83eb8.PNG)

**Comment by jfa257** [comment]
Cool!
