### ISSUE TITLE
File is too large.

### ISSUE THREAD

**Issue by eightxiao** [tentone/nunuStudio#292]
Hi，
My 3D model has been put in nunustudio for more than 900M. Now nunustudio always crashes when it is half opened. Is there any way to solve this problem?
Thanks！

**Comment by tentone** [comment]
Hi

The parsers in nunuStudio are not optimized for high memory usage, specially in the browser were the whole files are preloaded into memory is easy to run out of memory.

Unfortunately there is not a lot that i can do to fix this problem. If possible break the model into smaller chunks.

Thanks a lot!
