### ISSUE TITLE
SpriteSheet Bugs

### ISSUE THREAD

**Issue by frankiedelmar** [tentone/nunuStudio#294]
Great work on this awesome software! Unfortunately I found some bugs that have been introduced into this new version :

1. There seems to be an issue with the sprite animations in nunuStudio 0.9.6 (201904021847). The animations no longer play and are effectively just static images. The console log constantly renders the following message "THREE.WebGLRenderer: Texture marked for update but image is incomplete" repeatedly . Here is the link to the tutorial project in question http://nunustudio.org/editor/?isp=https://nunustudio.org/learn/basics/12_animation/spritesheet.nsp

2. In the portal demo after successfully creating a blue and red portal  , and sometimes even without meeting those conditions, the screen only renders a solid gray color. The Console log renders " THREE,WebGLRenderTargetCube: .activeCubeFace has been removed. It is now the second parameter of WEBGLRenderer.setRenderTarget()" repeatedly. http://nunustudio.org/examples/demo.html?nsp=files/portal.nsp

In the previous version these features and examples worked fine.

**Comment by tentone** [comment]
Hello

Thanks a lot for reporting these bugs.

Booth of them have been solved in the meanwhile. Thanks a lot!

Cheers
