### ISSUE TITLE
nunustudio crashes immediately, steps to re-create event is listed. [4 steps]

### ISSUE THREAD

**Issue by BracerJack** [tentone/nunuStudio#299]
Here is how to repeat, 

1: Download portable version of nunustudio.
2: Open program.
3: File save.
4: File->Publish->Web

If you click cancel, program crashes immediately.

If you did not click cancel and click "save", you will get "no such file or directory, copy file "runtime/vr.png"->c:\users\~~~"

**Comment by tentone** [comment]
Hi

Thanks a lot for reporting, this bug has been fixed in the last version of the editor.

Cheers
