### ISSUE TITLE
Multiple active tab support

### ISSUE THREAD

**Issue by tentone** [tentone/nunuStudio#30]
# Multiple active tab support

##### Description
 - Include support for multiple tabs at the same time
 - Allow tabs to be organised by dragging them around

##### References
 - Similar to https://www.golden-layout.com/

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by brylie** [comment]
Cool idea! This is also similar to other design tools such as GIMP and Blender, where users can create custom layouts to match their workflow.
