### ISSUE TITLE
WebVR - Totally broken - Cannot read property 'isPresenting' of undefined

### ISSUE THREAD

**Issue by franadoriv** [tentone/nunuStudio#302]
WebVR - Broken feature

##### Description
The game works fine but when the VR icon is pressed this error can be seen on the console:

nunu.min.js:2676 Uncaught TypeError: Cannot read property 'isPresenting' of undefined
    at nunu.min.js:2676

##### Version
This project is just a default project with VR enabled using the web browser studio version.

I got this info from the JS console.

Nunu.VERSION
"<PLACEHOLDER_VERSION>"

Nunu.TIMESTAMP
"<PLACEHOLDER_TIMESTAMP>"

##### Platform
 - Web Version [X]

**Comment by tentone** [comment]
Hi

Thanks a lot for reporting this problem i will look into it as soon as possible.

Cheers

**Comment by franadoriv** [comment]
Oh! Fast answer Thanks!

**Comment by tentone** [comment]
Hello sorry for the delay.

The problem has been fixed nunuStudio is not compatible with WebXR and legacy WebVR, should be working on most browsers.

Once again thanks a lot for reporting the problem
