### ISSUE TITLE
Does include() get multiply arguments?

### ISSUE THREAD

**Issue by sloothes** [tentone/nunuStudio#306]
# Does include() get multiply arguments?

##### Description
Great IDE. I am serious thinking to switch on it. I have found some minor things that can take improvements but is not the time to discus at the moment.
I have a important question about the include() function. I tried to include in a scene script more than one libraries. I have the suspicion that the function can’t receive more than one argument.
I tried to put more than one arguments inline, in array, even in a string (comma delimited).
But ιn runtime, I get warns like “Error compiling script code TypeError: Cannot read property 'data' of null” and finaly error “Uncaught Error compiling script code”.
I tried to call include() function multiply times with a single argument inside the script. Then in runtime I do not get any error, but… It looks like including only the first library and ignoring the others. Do you have any idea what may I do wrong?

Thank you in advance.

ps. (Sorry for my poor English).

##### Version
 - <0.9.6> <201909191156>

##### Platform
 - Web Version [X]
 - Windows [V]
 - Linux [X]

**Comment by tentone** [comment]
Hi

Thanks a lot for your feedback.

The include() method can only receive one argument, to include multiple scripts you will have to use multiple times the include method.

It is not actually a method, depending on the import model used (check the script docs at http://nunustudio.org/docs/classes/Script.html#attr_APPEND) the code is replaced, evaluated or laoded into global space.

DIfferent libs might required a diferent include solution try them and see if one works for your.

In the meantime i will change the include method to suport multiple libraries at once.

Thanks a lot.

Cheers

**Comment by sloothes** [comment]
Thank you for your (immediately response. 

I tried to call include() function multiply times with a single argument inside the script. In runtime I do not get any error, but… **It looks like recognize only the first library and ignoring the others**. 
I opened the exported app.nsp file in a text editor and all imported libraries was written in the file.
i. Do I have call the include() inside the initialize() ? (because I call it at the top of the code before the initialization).
ii. Which is the safest property for the include? APPEND, EVALUATE or INCLUDE? (I understand that each property have its special scopes and limitations).

Regards DC

**Comment by sloothes** [comment]
Also I have to notice an easy fix and a minor bug.
The easy first: In the "import Text" file input on Asset panel the "multiply" attributte should be set  to "true" for importing multiply file instead of single file each time.
The minor bug: when i dragged and dropped multiply json files in the Asset pane it recognized them as fonts files (or was only the icon?) instead as json/text files. When I used the file input (one by one file) its all ok.

Do you have in your plans to add an include() function for other types of text files (like json/text) for importing data in a script?

That`s for the moment so far.
Regards DC
