### ISSUE TITLE
Webcam Texture

### ISSUE THREAD

**Issue by quadrochave** [tentone/nunuStudio#310]
# Issue title

##### Description
Hi
Firstly I wanna say the nunu Studio seems amazing !!  :)

I'm trying use Webcam Texture feature on editor (web version and desktop on linux). My webcam is detect and the browser (chrome and firefox) ask for permission. Ok, I give the permission, the webcam starts (light on), but the console output this: No webcam avaiable.
What's seems wrong ?
I can work with my webcam with pure javascript and other webgl library like p5.js

##### Version
 - 0.9.6

##### Platform
 - Web Version [X]
 - Linux [X]

**Comment by tentone** [comment]
Hi

Thanks a lot. The webcam feature was broken due to a change in the media API.

I have fixed it, should be available in the web version soon. Thanks a lot for reporting this issue.

Cheers

**Comment by quadrochave** [comment]
Cool !!
That's works now !!
I intend to help as much as i can !
Cheers
