### ISSUE TITLE
VR support

### ISSUE THREAD

**Issue by piepjaquet9** [tentone/nunuStudio#313]
Hello,

I am very interested in investigating how nunuStudio could be used to prototype VR scene and as such I have a few questions.

1) Is there a demo example (working on Oculus Quest) showing a VR environment. I've tried https://nunustudio.org/learn/basics/10_vr/page.html but I am not getting the glasses icon at the bottom right of the screen.

2) How can I display the user hands (or Oculus controller)?

3) Are there any plans to export to a-frame markup?

Thanks. 

Phil

**Comment by tentone** [comment]
Hello

nunuStudio currently supports VR on WebXR and WebVR enabled browsers, should work on oculus go out of the box. Try opening the project of the tutorial in the editor.

To display the user hands you will need to use the controllers available in threejs project page, https://github.com/mrdoob/three.js/tree/dev/examples/js/vr still havent tried those.

A-frame by itself it a totally different project, nunustudio projects cannot be exported to a.frame html objects.

Thanks a lot.
