### ISSUE TITLE
"Run" Doesn't works after GLB import

### ISSUE THREAD

**Issue by FlorentBaudon** [tentone/nunuStudio#314]
Hello, 
I've create a basic project and click on run button, all works, "Run" tab show camera view.
But when I import 3D model (glb or gltf ) i can't run scene anymore, "Run "tab showing nothing.
This issue are on 0.9.6 web and windows version.

Thanks

##### Version
0.9.6

##### Platform
 - Web Version [X]
 - Windows [X]

![nunustudioissue](https://user-images.githubusercontent.com/6053247/70038534-b0a52480-15b8-11ea-8e82-1983cb18c3a3.png)

**Comment by tentone** [comment]
Hello

Thanks a lot for reporting this problem. Would it be possible for you to provide a glb file that i could use to recreate the issue?

Thanks a lot in advance.

Cheers

**Comment by FlorentBaudon** [comment]
Yes of course.
