### ISSUE TITLE
Interact with website the THREE.JS canvas is included in

### ISSUE THREAD

**Issue by 3kynox** [tentone/nunuStudio#315]
Hello everyones, I would like to develop my game while the NunuStudio / ThreeJs app is contained inside a Vue.Js website. After some research, that bridge looks like very interesting:

https://github.com/sascha245/vue-threejs-composer

The goal of this is make the developed game being able to interact with VueJs website.

My question is, when I'm using NunuStudio or, when the game from NunuStudio is exported, is it possible to do by any ways? I tried to find the answer by mylself but this was unfortunate.

Thanks anyway.

**Comment by tentone** [comment]
Hello

Yes this is possible without using any external libraries, check this tutorial where i explain how to communicate with the host page: https://nunustudio.org/learn/integration/02_communication/page.html

**Comment by 3kynox** [comment]
Cool. I'l dig more inside documentation. Thanks!
