### ISSUE TITLE
I love this project!

### ISSUE THREAD

**Issue by zweihander11** [tentone/nunuStudio#316]
Hello everyone.

My apologies if I'm not posting this in the correct place. I sort of looked for a forum or similar but could not find anything but this.

I think this is a neat tool perfectly suited for my needs, coming from a design background I'm just starting to learn how to code and this not only makes it easier to implement but also to learn.

As a beginner it is important to have a place to address questions and get help when one gets stuck.

Thank you!

**Comment by tentone** [comment]
Hello 

Thanks a lot, im glad that the project can be of help to you.

Currently im encouraging people to ask for help / report problems / request features here on the github page to ensure that everything is at one place.

Check the project website there are some tutorials and guides there.

Cheers
