### ISSUE TITLE
Motion blur

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#318]
# Implementing motion blur

##### Description
- ok so since its hard for some ppl to implement motion blur
- could you(tentone) add it as a feature to add the option for users to enable motion blue to the camera

##### Version
 - <0.9BETA> <NULL>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]
 - ALL [X]

**Comment by Hoodgail** [comment]
all thought you dont look like a person that has time to work on small features like this

**Comment by tentone** [comment]
Hello

nunuStudio already has support for motion blur trough the "after image" filter on the camera post-processing pipeline.

Here is an example file for you to test.

**Comment by Hoodgail** [comment]
damn ur so helpful... thank you
