### ISSUE TITLE
Publish bug

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#320]
# publish bug

##### Description
![Bug](https://user-images.githubusercontent.com/45743294/72691187-439e0d80-3ad8-11ea-9ff9-1eba92705c50.png)

 - LMao theres a but when the nunu.min.js when publish is blank with no data inside
 
##### Version
 - <0.9>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello thanks a lot for reporting this bug, i will look into it.

**Comment by tentone** [comment]
Hello i tried the feature on the web version seems to be working correctly are you experiencing this on the latest version?

Thanks a lot
