### ISSUE TITLE
sketchbook api

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#321]
# Not really an issue but

##### Description
- i was thinking if u could add the sketchbook api 
- https://www.youtube.com/watch?v=pirbCsTttQw
- its so F*cki*g good

##### Version
 - <0.9> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
The sketchbook is a framework by itself does not fit into the nunuStudio stack.

nunuStudiio could be used as tool to create something usefull.

**Comment by tentone** [comment]
Closed
