### ISSUE TITLE
SSAO distance

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#323]
# SSAO distance

##### Description
- so i added ssao... it only appears when its far from the camera...
- do you know why?
- and how i can make it appear or render even when its close to the camera

##### Version
 - <0.9BETA> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

The SSAO effect is calculated in screen space using the depth buffer and normals of the objects in the screen, you can improve the SSAO in closer range by either adjusting its parameters  (to match better your preference) or reducing the camera maximum distance (allowing for better resolution by distance on the depth buffer).

Thanks a lot.

Cheers
