### ISSUE TITLE
Mobile or other devices 

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#324]
# Linux,IOS,mobile

##### Description
- ok so I tried my project on an iOS device but it just showed up as a black screen...
- I don’t really need my FPS game on an iOS device but some others might 
##### Version
 - <0.9 BETA> <NOW>

##### Platform
 - Web Version [-]
 - Windows [-]
 - Linux [X]
- IOS [X]

**Comment by tentone** [comment]
Hello 

I will try to test it on a ios device to debug and fix it. Thanks a lot for reporting.

Cheers

**Comment by Hoodgail** [comment]
probably cuz IOS might not support webgl 2 and only webgl 1
maybe

**Comment by tentone** [comment]
Applications are working fine on latest versions of nunustudio and ios.

Closed! Thanks a lot for reporting!
