### ISSUE TITLE
How to include external Terrain library?

### ISSUE THREAD

**Issue by zweihander11** [tentone/nunuStudio#326]
Hello.
Is there a way to use this library inside nunuStudio?
https://github.com/IceCreamYou/THREE.Terrain

 I've tried the usual include method but I get errors once I reach this instance:
terrainScene = THREE.Terrain({});
 
I read the library docs but they are specific for Three.js which I'm still quite unfamiliar with. Maybe I'm missing something else. Any hint on how to use it here would be appreciated.

Thank you!

**Comment by Hoodgail** [comment]
drag to script in to nunustudio
then load it in like this
```js
include('Terrain.js')```

**Comment by Hoodgail** [comment]
i dont think u can include scripts from url...
the script has to be in the program

**Comment by zweihander11** [comment]
Thank you very much for replying. I tried that and get a console message saying 'Script running as Terrain.js'
However I still get a compilation error when trying to instantiate an terrain object as specified in the documentation. Here's the code I've got.
`// Generate a terrain
var xS = 63, yS = 63;
terrainScene = THREE.Terrain({
    easing: THREE.Terrain.Linear,});

function initialize()
{
scene.add(terrainScene);
}`

I apologize if the questions seems trivial but I'm just a beginner trying to figure this out.

**Comment by Hoodgail** [comment]
hmmm try
```js
Terrain({
    easing: =Terrain.Linear,});
```
intead of 
```js
THREE.Terrain({
    easing: THREE.Terrain.Linear,});
```
or 
````js
terrainScene = new Terrain({
    easing: new THREE.Terrain.Linear,});
```
if not tentone will have to help you. hes **VERY** helpful

**Comment by zweihander11** [comment]
Thank you for your help. I removed the  ,  after linear and it works now.
I've been trying to import several libraries lately so your advice might be useful in other cases.

**Comment by tentone** [comment]
Hello

Yes you had a small syntax typo there. Glad that you were able to solve it.

When using external libs you still have to use the THREE. prefix (at least on most of them).

Thanks a lot, i will possible use you case to improve the tutorial page.

Cheers

**Comment by zweihander11** [comment]
Thank you very much for your help and nice work updating the tutorial page with the Terrain example. Eventually I would like to contribute in some way or another and tutorials seem to be a good way to do so. 
I'm now trying to find some kind of UI library to display information. I'm open to suggestions if you happen to have any ideas.

**Comment by tentone** [comment]
You're welcome, i want to have as much information available for users as possible.

Im currently figuring out a good way to se HTML for GUI should be a fairly good and easy way to handle it.

Thanks a lot
