### ISSUE TITLE
how can i use the html feature... and how do i import it

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#327]
# HTML

##### Description
![New Project (2)](https://user-images.githubusercontent.com/45743294/73074801-705f7580-3e88-11ea-8965-10e3498fd389.png)
- whats this.. how can i use it
- how do i import it
##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

Right now we just import the files, still dont have a way to use it im currently working on HTML support for GUI.

Thanks a lot!
