### ISSUE TITLE
include function...

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#328]
# include

##### Description
- i cannot load to scripts at the same time
- like is i use include 2 times only the first one to be called will loaded
- and it looks like if i dont add ``;`` after it it will not load
##### Version
 - <0.9BETA> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

This is a bug i will fix it as soon as possible and report here.

Thanks a lot

**Comment by tentone** [comment]
The editor now supports loading multiple files properly should work.

Thanks a lot!

**Comment by Hoodgail** [comment]
thank you
