### ISSUE TITLE
Material texture and whether to use the checkbox trigger events in Google will produce a lot of texture in the Network

### ISSUE THREAD

**Issue by qwe5788319** [tentone/nunuStudio#33]
Material texture and whether to use the checkbox trigger events in Google will produce a lot of texture in the Network

system: windows 10
browser google 56.0.2924.87 (64-bit)

**Comment by tentone** [comment]
Hi @qwe5788319 

I wasnt quite able to understand exactly what happened, can you please leave an example? Or how to recreate what is happening?

Thanks a lot for reporting,

Cumps

**Comment by qwe5788319** [comment]
change object3d in position
 google network generate so much data:image base64

**Comment by tentone** [comment]
Its expected base64 encoded data occupies more 2/8 of space.

**Comment by tentone** [comment]
Hmmm, i have to check that, thanks a lot 👍

**Comment by qwe5788319** [comment]
After a long time is very card operation

**Comment by qwe5788319** [comment]
[error image](http://chuantu.biz/t5/51/1490263698x2890173740.png)
use texture is the same
