### ISSUE TITLE
TweenJs

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#335]
# TweenJs help

##### Description
- hello can someone/tentone please provide me a tweenjs example with nunustudio please
- from a position to an other

##### Version
 - <0.9BETA> <Now>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

I will add an example to the animation page, there are some example there that i have to review / refactor.

Thanks a lot
