### ISSUE TITLE
[ERRORS] blob / material / threejs

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#336]
# new issues

##### Description
 - idk if tentone made an update but
```js
THREE.Object3D: .getWorldPosition() target is now required
```
if you go to https://nunustudio.org/ 
![image](https://user-images.githubusercontent.com/45743294/74539054-5bb45180-4f0b-11ea-9350-6c30c6e39ca6.png)
- some of the materials are not loading / and in my project
there's a problem with the blob i can't **save** my project
##### Version
 - <*BETA> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

Thansk a lot for reporting, i have fixed the example.

Cheers
