### ISSUE TITLE
New object Suggestion

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#338]
# New geometry object

##### Description
hey tentone could u a geometry with this shape?
for adding object and physics shapes :) that would be cool
![image](https://user-images.githubusercontent.com/45743294/74595303-d82f5900-500d-11ea-90ab-555ac085317c.png)

to 
![image](https://user-images.githubusercontent.com/45743294/74595344-2b091080-500e-11ea-87c2-a0bd4ac45977.png)

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

 I have added this shape in the last version now available on the web version.

Thanks a lot!

Cheers
