### ISSUE TITLE
[BUG] Theta start/end

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#339]
# theta

##### Description
 - every time i change
![image](https://user-images.githubusercontent.com/45743294/74595775-b76a0200-5013-11ea-88d6-d451de82c674.png)
everytime i change one it changes the other to the same value... idk why both can't be diff

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

This was happening of sphere geometries correct? Should be fixed on next release.

Thanks a lot

Cheers

**Comment by Hoodgail** [comment]
it was sphere yes... and maybe others
