### ISSUE TITLE
Support for Grid Snapping and Angle Snap

### ISSUE THREAD

**Issue by Headclot88** [tentone/nunuStudio#34]
##### Description
NuNu Studio needs support for [grid snapping](https://www.youtube.com/watch?v=cjyjchiDi8w) and [angle snap](https://www.youtube.com/watch?v=UP9UgDLcfgU). This will make object placement in NuNu studio much more precise and easier on artists using the tool. Angle Snap should start at 5 degrees and be able to be tweaked by the artist. Grid Snapping should should be able to be adjusted by the artist to fit his or her needs depending on the task at hand.

##### Version
 - v0.8.9.22-alpha

##### Platform
 - Windows

**Comment by tentone** [comment]
Hi there

I think it can be easily implemented. As soon as I get some free time i will take a look at this.

Probably should have some dedicated UI elements to enable and disable grid and angle snaping, without leaving the editor tag.

The snap step i will add to the settings tab.

Thanks a lot

**Comment by tentone** [comment]
@Headclot88 Added support for grid and angle snapping in version V0.8.9.24, (available on the web version already).

Snap mode be activated in the settings menu, i will add later on controls for snapping, changing between local/world transformation and grid control somewhere in the scene editor for easier access.

Thanks a lot
