### ISSUE TITLE
[bug] animation page and maybe others

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#340]
# learn pages

##### Description
![image](https://user-images.githubusercontent.com/45743294/74596518-3ad02700-5005-11ea-83fb-584e336e9ba4.png)

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
I have hidden the tutorial spine example on purpose, should be restore when i fix it.

Thanks a lot for reporting.

**Comment by Hoodgail** [comment]
> I have hidden the tutorial spine example on purpose, should be restore when i fix it.
> 
> Thanks a lot for reporting.

oh ok

**Comment by tentone** [comment]
Animation page is back running with all examples now!
