### ISSUE TITLE
[bug] set animation is not working... and it was removed in the animation page... 

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#341]
# set animation

##### Description

```js
this.gun.setAnimation(0, "idle", false);
```
is not working
its removed in the animation page
i checked view-source:https://nunustudio.org/learn/basics/12_animation/page.html
its just hidden

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

Im currenlty trying to figure out whats wokring and not on the editor to fix/update everything that i can.

Spine animations are broken due to new version of three.js i hid it from the tutorial until it gets fixed.

Thanks a lot!

**Comment by Hoodgail** [comment]
> Hello
> 
> Im currenlty trying to figure out whats wokring and not on the editor to fix/update everything that i can.
> 
> Spine animations are broken due to new version of three.js i hid it from the tutorial until it gets fixed.
> 
> Thanks a lot!

aaah ok thank you for letting me know... yes i had this issue once from upgrading the threejs lib
