### ISSUE TITLE
physic body

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#342]
# physic body scale

##### Description
 - hey how cant i change the physic body scale in js but i can in the editor
##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

When you change the scale of the physics element in the editor youre not actually changing its scale youre changing its body shape size.

Thanks a lot

**Comment by Hoodgail** [comment]
> Hello
> 
> When you change the scale of the physics element in the editor youre not actually changing its scale youre changing its body shape size.
> 
> Thanks a lot

aaaaah ok makes since
