### ISSUE TITLE
Include function

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#345]
# Include function

##### Description
 - ok so i am trying to include the scaldeone api script
 - but the script can not be loaded out of the server so i can only load it  from 
https://cdn.scaledrone.com/scaledrone.min.js
but the problem is that i can only include scripts from the program.. i was wondering if you could do something like 
```js
include("https://cdn.scaledrone.com/scaledrone.min.js","url")
```
##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

I can add suport for external libs yes. Should be able to implement it without the need for the extra parameter.

Thanks a lot for the suggestion.

**Comment by tentone** [comment]
Implemented this feature in the last web version of nunuStudio.
