### ISSUE TITLE
javascript

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#347]
# javascript

##### Description
 - i was wondering if you could add option to script babel script
- so i can use react

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
You mean support for the babel transpiler? That would not help a lot. but could ensure compatibility for scripts in older browsers.

nunuStudio project can already be embeded easily into react or angular projects. Should be fairly easy to create a component wrapper.
