### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#348]
# get some ideas from this shit

##### Description
 - get some ideas from this shit http://editor.babylonjs.com/

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Thanks a lot i will take a look.

Cheers

**Comment by Hoodgail** [comment]
Lmao the ui looks like ass. Excuse my 14yr old language

**Comment by tentone** [comment]
The UI in nunuStudio or the babylon editor? I already knew the project.

Its UI is based on https://golden-layout.com/ i believe.

**Comment by Hoodgail** [comment]
> The UI in nunuStudio or the babylon editor? I already knew the project.
> 
> Its UI is based on https://golden-layout.com/ i believe.

 The Babylon ui is bad... the nunustudio is great

**Comment by ardsmarc** [comment]
Hi! I’m not sure where I should put this as it’s my first time commenting on GitHub. nunuStudio is great and I was wondering if you had any plans to integrate Augmented Reality. Being able to integrate projects like Jeeliz or ARjs within nunu in a WYSIWYG fashion could be amazing.

**Comment by ardsmarc** [comment]
The fact that you have the WebRTC example got my cogs spinning.

**Comment by Hoodgail** [comment]
:)
