### ISSUE TITLE
gltf file support

### ISSUE THREAD

**Issue by Headclot88** [tentone/nunuStudio#35]
##### Description
So the Khronos group is making a new 3d file format for VR and the web called gltf. It has the backing of several major companies with interests in VR. Anyway - Would it be possible to get gltf support in nunu studio? There is already an gltf loader for three.js [here](https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/GLTFLoader.js).

##### Version
 - v0.8.9.22-alpha

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
@Headclot88 Hi there

nunuStudio already has support for GLTF files. Still does not support GLTF2 im waiting for the implementation in three.js to be complete.

Thanks

**Comment by AdsonCicilioti** [comment]
What file formats is soported?

**Comment by tentone** [comment]
nunuStudio currently has support for obj, 3ds, dae, gltf, 3mf, awd, ply, vtk, vrml, fbx, pcd and stl

**Comment by AdsonCicilioti** [comment]
dae returns error for me :(

**Comment by tentone** [comment]
@AdsonCicilioti 

Open a new issue explaining what error are you getting and is possible how to recreate the error.
