### ISSUE TITLE
[BUG] when published to web

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#350]
# when i published to web

##### Description
 exported ``3/4/2020``  ``4:13 PM``
![image](https://user-images.githubusercontent.com/45743294/75923349-def20480-5e32-11ea-9110-a59a8586e48b.png)

#### console errors are
```
Uncaught ReferenceError: CapsuleBufferGeometry is not defined
    at GeometryLoader.parse (nunu.min.js:2816)
    at ObjectLoader.parseGeometries (nunu.min.js:2830)
    at ObjectLoader.parse (nunu.min.js:2828)
    at nunu.min.js:34
    at XMLHttpRequest.f.onload (nunu.min.js:2536)
:8883/favicon.ico:1
 ```
```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

### other
> from nunu studio code
```js
  case "CapsuleBufferGeometry":
        d = new CapsuleBufferGeometry(a.radiusTop,a.radiusBottom,a.height,a.radialSegments,a.heightSegments,a.capsTopSegments,a.capsBottomSegments,a.thetaStart,a.thetaLength);
        break;
//CapsuleBufferGeometry is not defined 
```
##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

Was missing an import on the runtime module. Please retry exporting it with the last web version published on the website.

Thanks a lot

**Comment by Hoodgail** [comment]
thank you for fixing this
