### ISSUE TITLE
Animating objects 360 degrees

### ISSUE THREAD

**Issue by jayvaglio** [tentone/nunuStudio#351]
# Animating objects 360 degrees

##### Description
 - When attempting to animate an object 360 degrees, the user selects object, adds animation markers to timeline for 0* and 360*. Upon playback, the object rotates but not as expected.
- Idea: add tooltips to entry fields (i.e. rotation X) that detail the expected quantity or acceptable range.
- Idea: add tooltip / hover details for the markers on the timeline that describe what the marker is adjusting

##### Version
 - 0.9.6 202003042304

##### Platform
 - Web Version [X]

**Comment by jayvaglio** [comment]
![2_confusingResult](https://user-images.githubusercontent.com/4575630/76006891-c9ccb280-5ed2-11ea-93d9-5d2c9d6cc7c1.png)
![1_entering360](https://user-images.githubusercontent.com/4575630/76006892-ca654900-5ed2-11ea-8c8d-94fb0ebf805e.png)

**Comment by Hoodgail** [comment]
yes it i saw this... 
its like ``180`` or ``90``  = ``1.57`` or ``3.14``

**Comment by tentone** [comment]
Hello

I have added a tab in the settings menu to select the angle units to use on the editor.

Thanks a lot.
