### ISSUE TITLE
nunuStudio community

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#352]
# nunuStudio community

##### Description
 - i suggest making a community for nunustudio

> discord server
> use the discourse to make a forum
> slack
# personally i prefer discord
but this is just a suggestion

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

Thanks a lot for the suggestion currently im trying to keep everything  here on github.

I belive its easier for now since nunuStudio is still a small project.

Cheers

**Comment by Hoodgail** [comment]
ok
