### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#354]
# Issue title

##### Description
![image](https://user-images.githubusercontent.com/45743294/76127210-244b3900-5fcf-11ea-8370-12df684cb9e5.png)
this happens when it loaded outside of the nunustudio editor
![image](https://user-images.githubusercontent.com/45743294/76128138-7ee59480-5fd1-11ea-9e56-dae6c987a058.png)
this works in the editor but not outside of it

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

Yeah that is normal and expected since the File loaders are not available at runtime.

Let met just make a test if that does not increase the runtime size a lot i can just include them.

Otherwise you will have to import them into the project.

Thanks a lot

**Comment by Hoodgail** [comment]
> Hello
> 
> Yeah that is normal and expected since the File loaders are not available at runtime.
> 
> Let met just make a test if that does not increase the runtime size a lot i can just include them.
> 
> Otherwise you will have to import them into the project.
> 
> Thanks a lot

oooooh i forgot about the file size... yep don't worry about it

**Comment by Hoodgail** [comment]
wait can i import scripts like modules?

**Comment by tentone** [comment]
Just include the files in the project should work alright.

**Comment by Hoodgail** [comment]
ok thank you
