### ISSUE TITLE
async... await

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#355]
# async... await

##### Description
 - await and async functions dont work on nunustudio
```js
const json = await fetch('https://image.shutterstock.com/image-photo/beautiful-water-drop-on-dandelion-260nw-789676552.jpg').then(response => response.text());
console.log(json);
```

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

Since the update and iniialize methods need to be syncronized with the rest of the engine they are not async.

You can however define other async methods / classes etc.

Cheers
