### ISSUE TITLE
include [BUG]

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#356]
# include

##### Description
![image](https://user-images.githubusercontent.com/45743294/76154326-96438100-60a8-11ea-8e16-deaac388a9d9.png)
is there a maximum amount of include function ?

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hi

THere was a bug some versions ago that only allowed for one include. 

But it is fixed now there should be no limit in the include

**Comment by Hoodgail** [comment]
> Hi
> 
> THere was a bug some versions ago that only allowed for one include.
> 
> But it is fixed now there should be no limit in the include

no thats not what i mean... you cant include in a script that is being included... you can only include from scripts that is in the scene

**Comment by tentone** [comment]
Oh sorry i misunderstud, yes that it correct you can only include from scripts not from included files.

**Comment by Hoodgail** [comment]
Yes and  i now understand why. thank you
