### ISSUE TITLE
Publish library to NPM

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#357]
# Issue title

##### Description
 - nunustudio in node/npm

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

nunuStudio is not a JS module of any kind, i can publish it on npm but people using it would have to import it as a vanilla js lib

Hmm Let me think about it. Ty

**Comment by tentone** [comment]
Hello

Published nunuStudio to NPM the runtime and editor should be now possible to import trough NPM to other projects.

Booth of them are not ES modules of any kind but should be faily easy to import them globally.

https://www.npmjs.com/package/nunu-studio

Cheers
