### ISSUE TITLE
Scene editor only shows 1/4 screen on 4K monitor

### ISSUE THREAD

**Issue by helzapps** [tentone/nunuStudio#359]
# Issue title
Opening project on 4K monitor causes scene editor to render a 4K version, but only display 1K of the scene in the preview area.

##### Description
On a macOS machine, tested on a 5K iMac as well as a LG 5K monitor, open the https://nunustudio.org/editor/index.html in either Safari or Chrome

Expected Results:
To be able to see the full scene
Actual Results: Only 1/4 of the full scene is displayed in the preview. I cannot find out to change the preview windows scale or rendering settings. Nothing in the settings menu seems relevant and the things I've tried changing do nothing.
I've tried changing the scale of my monitor, rebooting, everything I can think off, but the view shows 1/4 and it makes it really hard to pan and move about because the center of where I'm panning is all off. When I attempt to move objects that touch points are all extremely off and I have to hunt to find where the translated points are.

Here is what is seen when loaded on a HD monitor
![nunu_hd_monitor](https://user-images.githubusercontent.com/1172574/78837319-a650c800-79a8-11ea-81e7-8e9328baa454.png)

Here is what is seen when loading on my LG or MBP monitor
<img width="1678" alt="nunu_retina" src="https://user-images.githubusercontent.com/1172574/78837387-cbddd180-79a8-11ea-9aa9-de7e73fd43a1.png">

I also tried downloading the native macOS client app, but it gives me an error when I tried to open it.

##### Version
 - 0.9.6 4/8/2020

##### Platform
 - Web Version [X]
 - Windows [ ]
 - Linux [ ]

**Comment by tentone** [comment]
Hello

Thanks a lot for reporting this problem, this is caused by the pixelRatio size used by macos.

I will try to solve it as soon as possible. Once again thanks a lot for reporting this issue.

Cheers

**Comment by helzapps** [comment]
No problem, thanks for taking the time to build this software. Let me know if there's anything I can do to help; testing or provide any additional details.

**Comment by tentone** [comment]
Hello

This bug should not be fixed in the last web version. Thanks a lot for your help.

Cheers

**Comment by helzapps** [comment]
Confirmed it is fixed. Thank you so much for the quick turnaround!!!
