### ISSUE TITLE
View port Navigation feels non intuitive

### ISSUE THREAD

**Issue by Headclot88** [tentone/nunuStudio#36]
##### Description
So the view port navigation feels non intuitive and it takes more than a few seconds to pick up. I get that you are trying to replicate movement controls similar to Maya or 3D Studio Max. But It should be simpler than a DCC app navigation. My advice would be the following to improve the experience is as followed.

Using the WASD keys to navigate around the scene similar to a modern FPS or Third person shooter game controls. Using this in conjunction with right click and the mouse to drive the direction of the camera.
- W = Move Forward
- S = Move Backward
- A = Move Left
- D = Move Right
 

Unreal Engine 4 uses this navigation style and it is super intuitive to navigate around a view port.

##### Version
 - v0.8.9.22-alpha

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
@Headclot88 

Hi, thanks a lot for the feedback, i really have to test this, i actually prefer this approach but most people are more familiar with the one i currently have but i can implement this as an alternative.

**Comment by GGAlanSmithee** [comment]
To add to this discussion, I would argue that the left mouse button drag control isn't very user friendly.

As it is now, the center is the editor camera, and you rotate around it. IMO, the better way to control (and the way any other 3d editor that I know of works) would be to rotate around the selected object. See [three js editor](https://threejs.org/editor/) for an example.

**Comment by tentone** [comment]
What abou the 2D mode? The navigation there seems alright? I will add today orbit navigation to nunu.

@GGAlanSmithee I think that the three.js uses the intersection between the camera direction vector projection and the XZ plane as orbit center, for scenes where people dont use the XZ as base for objecti placement the navigation can get a bit odd.

**Comment by GGAlanSmithee** [comment]
@tentone I think it is the standard three orbit controls that's used in the three editor

**Comment by tentone** [comment]
Added support for Orbit navigation mode (Works similarly to the three.js editor navigation) and WASD navigation.

Also added an option to invert navigation. 

(Orbit mode is missing lateral movement i will add it tomorrow, these changes are already live in the web version https://nunustudio.org/editor/editor.html)

**Comment by tentone** [comment]
The options to change navigation mode are in the settings menu. Also added lateral movement to the orbit mode.
![capture](https://cloud.githubusercontent.com/assets/9158354/24836798/74e21c0a-1d1d-11e7-807f-8cb14a3bb5c0.PNG)
