### ISSUE TITLE
Error while running in Mac says, 'The application "nunuStudio" can't be opened.'

### ISSUE THREAD

**Issue by KnightCoder** [tentone/nunuStudio#367]
# Unable to run on Mac

##### Description
 - I downloaded files for Mac from https://github.com/tentone/nunuStudio/releases/download/v0.9.6/nunuStudio_0.9.6_mac_x64.7z 
 - However after extracting it on the Mac it was not executing (by mouse click) instead it was throwing error 'The application "nunuStudio" can't be opened.' 

##### Version
 - version 0.9.7

##### Platform
 - Mac 10.14

**Comment by tentone** [comment]
Thanks a lot for reporting this issue.

I will look into it, Its a bit hard for me to debug these since i dont own any MacOS computer, but i will try to figure out whats happening.

**Comment by tentone** [comment]
Bug closed due to lack of additional information!
