### ISSUE TITLE
Can event handling (mouse click/move, key press/down/up) be done purely using the editor's GUI?

### ISSUE THREAD

**Issue by KnightCoder** [tentone/nunuStudio#368]
# Can event handling (mouse click/move, key press/down/up, etc.) be done purely using the editor's GUI?

##### Description
 - Can events such as click, mouse move, key press, etc. be done only using the GUI of the editor? 
 - Or does it require coding as well? 

##### Version
 - 0.9.6

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]
 - Mac [X]

**Comment by tentone** [comment]
Hello

Input handling has to be done using javascript with a script object. There are some tutorial guides in the nunuStudio webpage that can help you to get started.

https://nunustudio.org/learn/basics/02_script/page.html

Thanks a lot

**Comment by KnightCoder** [comment]
Thanks! I hope to see this feature soon. :)
