### ISSUE TITLE
Pure Nodejs based build system

### ISSUE THREAD

**Issue by GGAlanSmithee** [tentone/nunuStudio#37]
As stated in the docs, the current build system requires windows and java, which I guess is for closure compiler?

Would you consider a pure Node.JS build pipe? This would lower the bar of entry and IMO makes sense since it's a JS project.

My use-case is that I would like to use the eidtor and runtime, but I need to make some changes to the core to integrate it with some other tech. The build requirements are unfortunatley blocking me from doing this as I do not have access to a windows machine. 

I guess closure compiler could still be used to produce final builds, or as an optional step.

**Comment by tentone** [comment]
Hi

The java requirement is because im currently using the closure compiler, but i really need to remove the windows dependency, i was thinking to use nodejs since im already using it to aggregate files and and remove includes etc... 

I also want to include in the build system options to create packages for distribution as well.

For external libraries i might include soon the option to include external files as resources. Would that be usefull?

**Comment by GGAlanSmithee** [comment]
@tentone 

The windows requirement is pureley because of using `.bat` files instead of `.sh` files? Should be fairly easy to get rid of if that's the case.

I Haven't used the closure compiler myself, but I remember reading about google removing the java dependency a while back - maybe this one https://github.com/google/closure-compiler-js? Could possibly be as easy as switching?

> For external libraries i might include soon the option to include external files as resources. Would that be usefull?

Yes! A plugin option would be great.

**Comment by tentone** [comment]
@GGAlanSmithee 

Minification can be an optional step only applied if java is installed on the computer, or maybe i can switch to the JS version of closure (i have to test it, but i assume it is GWT transpiled if this is the case i will try it and switch).

Im not sure about plugins because of the online version, i think that its better to include to libs directly inside projetcts, and probably add the option to get libs from npm directly (to reduce project size)

What do you think?

**Comment by GGAlanSmithee** [comment]
@tentone 

> Im not sure about plugins because of the online version, i think that its better to include to libs directly inside projetcts, and probably add the option to get libs from npm directly (to reduce project size)

Sound like a good idea. In my view, here are some things to consider in the lib vs plugin aspect.

#### Should a user be able to register a lib / plugin without building the application?
1. Registering a lib at compile / build time
    * probably more performant (will be compiled with rest of project)
    * probably more complicated (will require users to build the project)
    * more control (can integrate it to your own liking)
2. Register a plugin at run time
    * increased overhead
    * probably simpler, but would require defined entry hooks, or an interface to implement
    * less control

#### Should there be hookup points for a lib / plugin
1. There are no entry hooks
    * the user will have to integrate a library to his / her own liking, (when to invoke it etc) (or it will be automatically put on the app directly to be globally available?)
    * more control
    * puts more responsibility (burden) on the user
2. There are pre-defined entry hooks (onUpdate, onRender, onInit etc)
    * users registered plugins will be invoked at corresponding entry point
   * subjectively easier
    * less control

So just sharing some thoungts :)

**Comment by GGAlanSmithee** [comment]
@tentone 

Please have a look at #38. Do you want me to open a new issue where we can discuss lib / plugin functionality?

**Comment by tentone** [comment]
Hi

Yeah sure, that would be great, thanks!

**Comment by tentone** [comment]
Hi @GGAlanSmithee nunuStudio build system is now nodejs based, java is still used for closure since the javascript version seems to be a bit slow also added documentation generation to the build script and removed the rmraf dependency, thanks a lot for your code 👍 
```

----------------------------------------------------------------------
                              nunuStudio
                    github.com/tentone/nunuStudio
----------------------------------------------------------------------
                                Editor
----------------------------------------------------------------------
 Joining files
 Optimizing with closure
 Minifyng with closure
 Removing temporary files
----------------------------------------------------------------------
                              Runtime
----------------------------------------------------------------------
 Optimizing with closure
 Minifyng with closure
 Removing temporary files
----------------------------------------------------------------------
                           Updating Webpage
----------------------------------------------------------------------
 Copying runtime build
 Removing old editor files
 Copying editor files
 Copying editor build
----------------------------------------------------------------------
                      Generating documentation
----------------------------------------------------------------------
 Removing old files
 Generating Docs
----------------------------------------------------------------------
                  Done! Press any key to exit
----------------------------------------------------------------------

```
