### ISSUE TITLE
What format is the binary nsp files? 

### ISSUE THREAD

**Issue by arpu** [tentone/nunuStudio#374]
[Question] what format is the binary nsp files?

**Comment by tentone** [comment]
Hi, 

NSP files are PSON (https://github.com/dcodeIO/PSON) encoded files.

Thanks a lot.

**Comment by arpu** [comment]
Hi,
for network transfer i use https://msgpack.org/ would it make sense to use msgpack and not Pson?

**Comment by arpu** [comment]
( unrelated to this question do you have a discord channel or slack? )

**Comment by tentone** [comment]
I have tested and compared some solutions PSON is faster, uses less memory and can get better results than everything else that i have tested.

The trick with PSON is the fact that it can handle properly JS typed array formats and uses them internally to speed thing up.

The downside is that PSON has less support, for mos projects i would say that MsgPack is a good alternative to JSON.

![Czxcapture](https://user-images.githubusercontent.com/9158354/79693555-463d0a00-8263-11ea-9e48-38fc21ac92ea.PNG)

**Comment by tentone** [comment]
Currently the project does not have any discord or slack. Im trying to keep all discussion here on Github for now. Since the community is quite small.

**Comment by arpu** [comment]
make sense, thx for the information and great work on nunustudio!

**Comment by arpu** [comment]
maybe a more maintained format would be https://github.com/google/flatbuffers ?
