### ISSUE TITLE
Error In Saving

### ISSUE THREAD

**Issue by Kenji245** [tentone/nunuStudio#378]
# Error In Saving

I don't know why this keep happening if i imported model from any formats, but it just fine if i didnt import any model.
![Capture](https://user-images.githubusercontent.com/49766940/80507768-65454580-89a1-11ea-952f-e9ad14c5b3a2.JPG)

i was suspect it because my default browser is not chrome but it still happening after i switch my default browser 

anything i did wrong?
thanks in advance
##### Version
 - <0.9.6> <TIMESTAMP>

##### Platform
 - Web Version []
 - Windows [X]
 - Linux []

**Comment by tentone** [comment]
Hello

I believe this bug was fixed in the last web version of the editor.

Can you please provide a file example?

Thanks a lot

**Comment by Kenji245** [comment]
i used the offline version which i downloaded from the official website tho
and here is the model
https://drive.google.com/open?id=1zW8esddHRVtedudhzsncOeS_EGmw7bGc

please let me know if you already downloaded the model(as this model is kinda private) or if you have problem with the model. some moterials are based on solid colors anyways.

thanks in advance

**Comment by Kenji245** [comment]
well, i decided to build from source and its looks like everything is fine and works properly

**Comment by tentone** [comment]
Hi.

Great, i will try to keep the builds updated more often maybe i will consider to publish automatically using github actions.

Thank you.
