### ISSUE TITLE
Chromakey shader with webcam

### ISSUE THREAD

**Issue by quadrochave** [tentone/nunuStudio#379]
# Chromakey shader with webcam

##### Description
Hi !
I intend to use 3d scenes with computer vision, including AR and machine learning.
After playing with p5.js and a-frame I think perhaps I use this technologies with nunustudio, that I love the Graphical Editor,  features and facility

My first question is use chromakey shader with webcam texture for real time chromakey
I tried various algorithms like threex.chromakey 
https://github.com/hawksley/Threex.chromakey
and shadertoys examples, but the best result that I got is javascript library Seriously.js with the chromakey effect

[Seriously.js](https://github.com/brianchirls/Seriously.js)
[Serioulsly.js chroma  plugin](https://github.com/brianchirls/Seriously.js/blob/master/effects/seriously.chroma.js)

I' not sure how the much simple option: using Serioulsy as library imported inside Nunustudio's  script editor  or take the vertex and fragment shader from the chroma.js effect and uses inside Nunustudio's shader editor 

Well, I have good experience with video tutorials and I hope soon to contribute sharing knowledge with my open-source projects

##### Version
 0.9.6 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

This should be faily easy to achieve without any change in the editor. You could just import the library but its is not compatible with the last version of the editor.

So i copied to the code into a script and changed it to be compatible with the last versions. 

Heres and example file. I will add this example to the shader tutorial. Thanks a lot!

![asdadasd](https://user-images.githubusercontent.com/9158354/80868478-c6676480-8c92-11ea-9503-3c7fa26c9671.PNG)

[chromakey.zip](https://github.com/tentone/nunuStudio/files/4567992/chromakey.zip)
