### ISSUE TITLE
frameworks

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#385]
# Issue title

##### Description
 - hey have u thought of working on ur own websocket frame work to work with physics?
 for nunuStudio

##### Version
 - <forEach()> <Date.now()>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

Dont know if i understood the question properly. Do you want to known if i tought of creating a websocket based networked physics system? To maybe sync physics from multiple users?

No. But i have made a tutorial of how people can use websocket to implement a multiplayer game. Copying the physics attributes between player or running the physics system in the server application could be a solution for this problem.

**Comment by Hoodgail** [comment]
ok thank you
