### ISSUE TITLE
physics

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#386]
# Issue title

### have u tought of adding multiple pysics for ppl to use from? for ex 
-physijs
- ammojs 
-etc

##### Version
 - <VERSION> <TIMESTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
I have a issue open to address this. I still don't think that is worth supporting multiple physics back ends at least for now.

Im leaning more towards implementing some sort of editor API for people to add new editor functionality. Anyway it is also possible to import any physics engine into the project.

**Comment by Hoodgail** [comment]
ok thanks for letting me know
