### ISSUE TITLE
SSAO/threejs

### ISSUE THREAD

**Issue by Hoodgail** [tentone/nunuStudio#387]
# Issue title

##### Description
 - the ssao shader  in nunustudio tends to remove -100 fps 
 - but the ssao in the three js examples remove only -10fps
(I'M USING THE NUMBERS AS AN EXPRESSION)
and you should update to the ``r116`` or have u?

##### Version
 - <ALL> <NOW>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
The SSAO shader is the same as the one from current threejs.

There a slight performance penalty inside of the nunuStudio, but when running the exported app the performance should be exactly the same.

Thanks a lo!

**Comment by Hoodgail** [comment]
aaah ok thank you :)
