### ISSUE TITLE
Build failed: Unable to access jarfile compiler.jar

### ISSUE THREAD

**Issue by TheBricktop** [tentone/nunuStudio#389]
# Issue title

##### Description
- i have the latest java installed and updated
- node js installed and updated
- run from admin on win 10
- still getting the error
##### Error text:
Error: Command failed: java -jar ../node_modules/google-closure-compiler-java/compiler.jar --compilation_level SIMPLE --warning_level QUIET --formatting PRETTY_PRINT --language_in ECMASCRIPT6 --language_out ECMASCRIPT5 --js ../build/nunu.editor.js.temp --js_output_file ../build/nunu.editor.js
Error: Unable to access jarfile ../node_modules/google-closure-compiler-java/compiler.jar

##### Version
 - latest github just now fetched

##### Platform

 - Windows [X]

**Comment by tentone** [comment]
Hello

You have to install dependencies using npm install before trying to build the project.

I updated the readme of the project to include this step.

Thanks a lot!

**Comment by TheBricktop** [comment]
After fixing vulnerabilities with npm audit fix it run without any problems
![obraz](https://user-images.githubusercontent.com/3866030/83010159-22b26f80-a018-11ea-99d6-b4b381ec3bbf.png)

**Comment by TheBricktop** [comment]
Should building yield some exe files for windows? 
I cant seem to find one.

**Comment by tentone** [comment]
JAVA is no longer required for build!
