### ISSUE TITLE
Typo in homepage

### ISSUE THREAD

**Issue by itaditya** [tentone/nunuStudio#39]
# Issue title

##### Description
The website https://nunustudio.org/ , has a typo 
![image](https://cloud.githubusercontent.com/assets/15871340/25068759/d343ad90-228b-11e7-98e8-68539e4b6862.png)
Please fix that

PS - Awesome work by the way

**Comment by tentone** [comment]
Hi thanks a lot 👍  fixed it!

(Changes might take a bit to go live)

Cumps
