### ISSUE TITLE
Weird shadow artifacts on Double sided rendered mesh

### ISSUE THREAD

**Issue by TheBricktop** [tentone/nunuStudio#390]
# Moire like artifacts on double sided meshes

##### Description
- if set to double side rendering shadows cast by lights are ugly
- when importing the models from blender (as gltf) all materials are set to double
- its kinda tedious to change all the materials on big scene
- also the lack of quick look up material inspector that allows to change makes the process slow cause switching from material editor to scene view has a 4-5 s lag, (might be because of like 15-20 materials).

##### Version
 - <VERSION>0.9.6 <TIMESTAMP>25.05.2020

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

Can you please provide a screenshot, this is probably [Shadow Acne](https://digitalrune.github.io/DigitalRune-Documentation/html/3f4d959e-9c98-4a97-8d85-7a73c26145d7.htm) is a commom problem with lack or precision in shadow maps.

It can be avoided by applying a smal ammount of bias in the light object shadow. This can be accessed in the inspector panel.

Thanks a lot!

**Comment by TheBricktop** [comment]
Thanks for the response ill try that.

**Comment by TheBricktop** [comment]
yea that looks like shadow acne, the method with bias works

**Comment by tentone** [comment]
Great. I probably should add this later to the lights tutorial. Thanks a lot!
