### ISSUE TITLE
Support for realsense 2 js ?

### ISSUE THREAD

**Issue by TheBricktop** [tentone/nunuStudio#392]
# librealsense2 support

##### Description
after seeing support for leapmotion and kinect, i thought that there are some modern devices that could be used in interesting way in webGL, mainly the realsense series of rgbd cameras and even the experimental tracking camera t265 cause it would add instant slam for almost any device with chromium build.
As for leapmotion being in hiatus for some time and loosing ground for other companies like google with their media pipeline with headtracking and 3d handtracking, also i think oculus released api for handtracking in webxr. 

##### Version
 - all of them

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

I intend at some point to remove booth leap motion and kinect support from the IDE want to move it to extensions when i have those available.

Realsense could also be added as an extesion when that happens.

Thanks a lot!

**Comment by tentone** [comment]
I have released a new version where booth kinect and leap have been removed. I will start working on extensions for the editor soon.

Support for realsense should be attainable as a extension later on. Thanks a lot!
