### ISSUE TITLE
Not getting into VR mode on quest browser

### ISSUE THREAD

**Issue by TheBricktop** [tentone/nunuStudio#394]
# Not getting into VR mode on quest browser

##### Description
-just set up the scene project and the camera to use VR 
- exported the project as html 
- served locally
- pc version correctly shows the vr button
- quest browser shows the site correctly in 2d
- clicked the vr button but its stuck in the black void and the cursed white ring of loading
- uploaded the site to the surge to test it but same result (no immersion mode whatsoever)
- project has like one mesh with two materials and the skybox, sub 8k verts, 2k skybox no fancy shaders.

##### Version
 - <VERSION> 0.97.8<TIMESTAMP>

##### Platform
 - Web Version [X]
 - Oculus Web [X]

**Comment by tentone** [comment]
Hello

This seems to be a bug i will try to fix it ASAP.

Thanks a lot!

**Comment by TheBricktop** [comment]
No problem if You need additional info and testing on device let me know.

**Comment by shantee** [comment]
Same problem here (using oculus quest)

**Comment by tentone** [comment]
Hello

I have been going crazy trying to figure out what is happening here. The app seems to work fine on the webxr spec emulator for some reason is does not work on mobile devices o.O

Will be trying alternative solutions in the next days.

Thanks a lo!

**Comment by TheBricktop** [comment]
this is especially weird cause some of the old examples work without any problems like the rollercoaster.
Maybe because of the old api dunno.

**Comment by tentone** [comment]
After im done with my current task i will start working on this one, to figure out whats going on. It might be related with the post processing stack but i have to test is careful to be sure.

Its weird because i pulled my old oculus DK2 and its seems to work there o.O well i hope i can figure this one out soon. Thanks!

**Comment by tentone** [comment]
Hello

The VR issues have been solver in the new version 0.98.12 available on the web. I have tested them in android with cardboard and on desktop seems to be working fine now.

Thanks a lot for your patience.

Cheers
