### ISSUE TITLE
About the rotation in the inspector

### ISSUE THREAD

**Issue by TheBricktop** [tentone/nunuStudio#400]
# How does the rotation work?

##### Description
- What unit does the object inspector use? Is it rad or deg?  or pure quaterion ?
- For sanity sake i think that it should be in deg.

##### Version
 - <VERSION>0.97.10 <TIMESTAMP>

##### Platform

 - Windows [X]

**Comment by tentone** [comment]
Hello

Internally quaternions are used but in the editor a euler rotation is presented is can be used in rad or degree it is configurable in the settings menu.

By default radians are used.

**Comment by TheBricktop** [comment]
Thank You, didnt noticed that option .

**Comment by tentone** [comment]
No problem here to help. Thanks
