### ISSUE TITLE
3D model with normal map will be black

### ISSUE THREAD

**Issue by eightxiao** [tentone/nunuStudio#403]
Hi，
The 3D model Example.fbx in nunuStudio, the material with normal map becomes black. Other 3D software is normal.
Attached are my model and NSP files
Thanks!
[Example.zip](https://github.com/tentone/nunuStudio/files/4750472/Example.zip)

##### Platform
 - Web Version [X]
 - Windows 10

**Comment by tentone** [comment]
Hello

I tried to open it on booth blender and the 3D visualizer from windows booth of them do not load the any normal map.

The FBX loader from nunuStudio does support most some normal formats from fbx files. But for that file i cannot load them in any of my softwares.

Thanks a lot!

**Comment by eightxiao** [comment]
Sorry, the Example.fbx doesn't have any material. I mean Example.fbx import nunuStudio, create a new phong material, add a normal map, and the model turns black. If you do not select a normal map, it will not.
See attachment for effect.
Thanks！
[file.zip](https://github.com/tentone/nunuStudio/files/4752847/file.zip)

**Comment by tentone** [comment]
The model is actually missing UV's coordinates. Thats why the normal cannot be applied properly.

That is also the case for textures. I applied the same material to the 3D object and to the torusknot. Seems to be a bug in the export.

![asdad](https://user-images.githubusercontent.com/9158354/84168061-e0a11900-aa6e-11ea-8218-c5646e323ada.PNG)


Thanks a lot!

**Comment by eightxiao** [comment]
Thank you very much. I'm glad the problem has been solved

**Comment by tentone** [comment]
No problem Here to help. Thanks a lot!
