### ISSUE TITLE
Scene switching and cameras question (camera not displaying after scene change)

### ISSUE THREAD

**Issue by netro83** [tentone/nunuStudio#413]
# Scene switching and cameras question

##### Description

1. I create a scene (scene1) and an another one (scene2)
2. I create two cameras - one in the scene1 and another one in scene2
3. On the inspector panel, i turn on the Use Camera checkbox (on camera1 and camera2)
4. In the scene1 i create a script (script) and in the update loop i call program.setScene("scene2")

and i see only a **black screen.**

- If i use console.log i see, the script switch between the scenes
- If i turn off the scene2 camera (Use Camera checkbox), i see the scene2 screen
- If i call setScene on the initialize function, the project running normal

reproduction nsp: http://badcoke.com/nunu/test_camera.nsp

what is wrong?

##### Version
 - 0.97.14 202006121739

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [ ]

**Comment by netro83** [comment]
I create an another script in the scene2, and if i call (in scene2 -> initialize function)

`program.app.resize();`

the app looks correct. 

I see the scene2 (camera) scene... (just when if i publish to web and run the exported project with live-server/local webserver (npm live-server) - in the online editor version the program.app object is null )

**Comment by tentone** [comment]
Hello

Sorry i am a bit late this is a bug with the scene change mechanism.

Thanks a lot for reporting. Glad that you found a way around it.

I will try to fix this in the next days.

Cheers

**Comment by tentone** [comment]
The bug has been fixed in last version of the editor! Thanks a lot!
