### ISSUE TITLE
Are you convenient to tell me what materials is used in the car screenshot?

### ISSUE THREAD

**Issue by sherry-min** [tentone/nunuStudio#414]
Hi!

    I see the car screenshot  and want to know what materials is used in the demo, especially the material named paint. I have tried and can't achieve the effect as the car screenshot you provided. Are you convenient to provide demo of car screenshot? 

Thanks a lot!

![1](https://user-images.githubusercontent.com/33304185/87743700-137fbf00-c81c-11ea-9fe8-9ff8ffa7cbbc.png)

**Comment by tentone** [comment]
Hello

There is no need i can share the project file with you so that you can explore it.

[car.zip](https://github.com/tentone/nunuStudio/files/4948987/car.zip)

Thanks a lot

**Comment by sherry-min** [comment]
Thanks a lot.

I found the project file can't run in windows version, but can run in web version. What is wrong?

Version

0.9.6 201904261147

Platform

Windows [10]

![QQ截图20200721093401](https://user-images.githubusercontent.com/33304185/88002733-c9f1e580-cb35-11ea-8c54-33ac60b870a2.png)


Thanks a lot once again.

**Comment by tentone** [comment]
The project has been recently update i will be updated the desktop builds in the next few day that will fix the loading of this file.
