### ISSUE TITLE
Sprite object is broken ('Error While Rendering program' in latest version)

### ISSUE THREAD

**Issue by helzapps** [tentone/nunuStudio#418]
# Getting error with our .nsp file we saved out yesterday (7/21/2020) in the new version of the Editor released today

##### Description
 - Navigate to Web Editor [https://www.nunustudio.org/build/editor/index.html](url)
 - Select File->Load
 - browse to find our file saved out yesterday
 - Select run after it loads successfully

Expected Results: For it to run. _Note: No changes have been made to the file since it was saved yesterday and I actually have the old editor up still in a browser tab and it runs just fine in that Editor_

Actual Results: receive the below error when selecting run.
<img width="451" alt="Screen Shot 2020-07-22 at 3 05 45 PM" src="https://user-images.githubusercontent.com/1172574/88233625-d5740800-cc2c-11ea-8364-63c857c9f7ec.png">

More Info: The reason we're getting this error is in fact because several items have been deleted from the Object graph when uploading the file. See this image:
<img width="1206" alt="Screen Shot 2020-07-22 at 4 00 49 PM" src="https://user-images.githubusercontent.com/1172574/88237641-8500a880-cc34-11ea-9b85-b232751c8d76.png">

##### Version
 - 0.98.5 2020-07-22T12:56:30.059Z

##### Platform
 - Web Version [X]
 - Windows []
 - Linux []

**Comment by helzapps** [comment]
I was able to get it to run by commenting out code that accesses those floor_sprites objects, but the issue is that they were all deleted when importing into the latest editor. We'll have to add them all back now.

**Comment by helzapps** [comment]
The appears to be an even more serious issue as I can no longer add Sprites to the scene. I've tried with just the standard scene that loads:

1. Load default scene
2. From Add Panel select Container -> Container is added to scene
3. From Add Panel select Sprite -> Nothing happens for me

I've tried this across multiple browsers and am having someone try on a Windows machine to rule out OS.

**Comment by andylewisart** [comment]
+1 for not being able to create sprites. Thanks for looking into this!

**Comment by tentone** [comment]
Hello

I have just fixed this bug in the version 0.98.6 that should be already available in the web.

I missed the fact the the sprite object was not getting the Sprite base prototype methods.

Thanks a lot for reporting this error.

Cheers

**Comment by helzapps** [comment]
One other issue is in our script we are doing something like so:
```
    var vs = new VideoStream(
      "./videos/SIRTeX_IllustratedMoGraph_Update_v06_noAudio.mp4"
    );
    if (vs != null) {
      var texture = new VideoTexture(vs);
      ...
    }
```
The null test worked in version 0.97.14 and would bypass actually trying to create the video texture in our editor running. But now in 0.98.5 and today's 0.98.6 that test is failing in that even though that file isn't local in our test runs, the `vs` var is not null and it's attempting to create the `VideoTexture` but then it throws an error (first screen shot in my description). Should this be coded differently or in fact is there a separate bug that should be reported for this issue now? Thanks?

**Comment by tentone** [comment]
This is a bit weird that vs variable should never be null in any situation.

Can you please show what error you are getting when accessing the VideoStream?

I will create a new issue for this problem. Thanks a lot!
