### ISSUE TITLE
Video asset: autoplay + loop

### ISSUE THREAD

**Issue by pedro-fontoura** [tentone/nunuStudio#42]
# Video asset: autoplay + loop

##### Description
 - Need control over autoplay and loop for video assets (as we have over audio assets)
- I have a project with a video file, with audio, and the audio keeps playing ad nauseam

##### Version
 - 0.8.9.21

##### Platform
 - Windows

**Comment by tentone** [comment]
Autoplay and loop options already exist, you're running an outdated version, check documentation before opening issues please.

http://nunustudio.org/docs/classes/VideoTexture.html

Closed!
