### ISSUE TITLE
nunuStudio can not in MacBook Pro 2019 

### ISSUE THREAD

**Issue by yatingkun** [tentone/nunuStudio#424]
# Issue title

##### Description
 when run nunuStudio in mac os an error happened that I can not open nunuStudio

what should I do?

My system version is macOS Catalina 10.15.5

<img width="964" alt="image" src="https://user-images.githubusercontent.com/33242951/88823575-d3471600-d1f7-11ea-8c5e-441b142a113c.png">
##### Version
 - <VERSION> <TIMSTAMP>

##### Platform
 - Web Version [X]
 - Windows [X]
 - Linux [X]

**Comment by tentone** [comment]
Hello

The mac os version is no longer supported.

You can use the web version that should work fine.

Thanks a lot!
