### ISSUE TITLE
What does delta mean in update method

### ISSUE THREAD

**Issue by guocheng0519** [tentone/nunuStudio#426]
#What does delta mean in update method

##### Description
Does delta represent milliseconds or frames?

##### Version
 - <VERSION> <TIMSTAMP>

##### Platform
 - Windows 
![20200804100354](https://user-images.githubusercontent.com/53458147/89244794-f92a4b80-d639-11ea-901e-a132d1086863.png)

**Comment by tentone** [comment]
Hello

Yes delta is the time in ms since the last frame.

Cheers
