### ISSUE TITLE
Viewport issues with older projects

### ISSUE THREAD

**Issue by petepolyakov** [tentone/nunuStudio#437]
was wrong guess. 
If scale up zoom in Chrome it uses just part of the viewport when you press play. This issue I guess is not even issue :-)
Sorry!
![test_3](https://user-images.githubusercontent.com/20783129/95421333-41e8d400-090b-11eb-85c5-5c09a7b022a2.jpg)

**Comment by tentone** [comment]
Hello

What computer are you running this on can you please check your window.devicePixelRatio value on the chrome console?

This is probably related to the pixel ratio.

I will have to check this. Thanks a lot!

**Comment by petepolyakov** [comment]
It was due to I zoomed page (those 125% 150% 200% etc) in Chrome. 
I run it on PC 4790k/32/ssd1tb/2070

**Comment by tentone** [comment]
Thanks a lot for reporting this issue.

It was missing the device pixel ration in the run tab.

It has been fixed in the code branch.
