### ISSUE TITLE
File gets included if it's in a comment

### ISSUE THREAD

**Issue by denkerinteraktivgmbh** [tentone/nunuStudio#438]
# File gets included if it's in a comment

##### Description
- When including a script-file in a script object the script-file get's included even if its commented out.
`//include("reticulum.js");` has the same behaviour like `include("reticulum.js");`

##### Version
 - nunuStudio 0.98.15 Build 2020-08-05T22:19:34.347Z

##### Platform
 - Web Version [X]

**Comment by tentone** [comment]
Hello

Thanks a lot for reporting this issue.

Has been fixed in the code.
