### ISSUE TITLE
Camera stops in the middle of the animation

### ISSUE THREAD

**Issue by petepolyakov** [tentone/nunuStudio#445]
**UPDATE**
**Can be closed, resolved, my fault.**

**I had to read API with attention. The difference was in `if(Mouse.buttonPressed(Mouse.LEFT))` vs `if(Mouse.buttonJustPressed(Mouse.LEFT))`**

/////

WebEditor.

Click on the button (invisible cube) then it calls for a camera animation that moves to the left.
5 times out of 10 Camera Animation stuck somewhere in the middle without any clicks or whatever.
Camera Animation is simple, just X axis, No loop, Enabled. 
Not sure what can be done to improve the experience.

```


var cameraAnimation;
var camera;

function initialize()
{
	cameraAnimation = true;
	camera = scene.getObjectByName("MainCameraOld2");
	console.log(camera);
	camera.mixer.pause();
}


function update(delta)
{
	
	//Check interseted objects - checking all files grouped with the script
	var intersects = scene.raycaster.intersectObjects(self.children);
	
	//Link
	for(var i = 0; i < intersects.length; i++)
	{
		if(Mouse.buttonPressed(Mouse.LEFT))
{
		cameraAnimation = !cameraAnimation;
		
		if(cameraAnimation)
		{
			camera.mixer.pause();
		}
		else
		{
			camera.mixer.play();
		}
	}
}
}

```
![button1](https://user-images.githubusercontent.com/20783129/96288098-e2489380-0fb0-11eb-9da2-6de309a2d583.jpg)

![stuck2](https://user-images.githubusercontent.com/20783129/96287972-b1685e80-0fb0-11eb-9421-2f0a3079827f.jpg)

![animation1](https://user-images.githubusercontent.com/20783129/96288275-2176e480-0fb1-11eb-9fef-974fcf395b52.jpg)

**Comment by tentone** [comment]
Hello

Sorry for my late response.

Glad that you figured this one out.

Cheers
