### ISSUE TITLE
Cannot attach scripts to objects in Project Explorer

### ISSUE THREAD

**Issue by jpryne** [tentone/nunuStudio#45]
# Cannot attach scripts to objects in Project Explorer
##### Version
 - <VERSION> 0.8.9.25 <TIMESTAMP>

##### Platform
 - Web Version [X]

**Comment by tentone** [comment]
Hi i just saw you comment on reddit, to place object inside other you have to drag the object to center, (look for the border on the object box)

When dragging
![dragging](https://cloud.githubusercontent.com/assets/9158354/25559917/1855b9b6-2d3e-11e7-9a3c-60be90610ea4.PNG)

When reordering
![reordering](https://cloud.githubusercontent.com/assets/9158354/25559918/1f461496-2d3e-11e7-91b5-68b1bcfc37bf.PNG)

**Comment by jpryne** [comment]
Sorry, I still have no idea what you're talking about. Tried dragging a script to various points around the name, but the effect is always the same.

**Comment by tentone** [comment]
Im running on desktop (Web Version), are you running on mobile? The editor its not supported on mobile platforms (it works but most of the touch input its not working)

**Comment by jpryne** [comment]
I'm on desktop too, yet when I drag a script onto an object, (in the
Project Explorer,) I still get no result. In the center, off to the side,
nothing..

**Comment by tentone** [comment]
I will have to check this carefully, this might be a bug, are you running on Windows? OSX? Linux? Wich browser are you using? 

Thanks a lot for reporting this i will try to check it (and fix it if it really is a bug) as soon as possible.

**Comment by jpryne** [comment]
I'm using Windows 7 and the Srware Iron browser, which is a fork of Chrome.

**Comment by tentone** [comment]
Hi, tested on Windows 10 with the last version of the Iron Browser and seems to work fine, i recorded a video, check if youre doing it right here

 https://youtu.be/wMPnFJX21YY

It might be just a bad interaction design problem on my side.

**Comment by jpryne** [comment]
Watched the video, and tried it again here on my machine, but still won't
work for me. I could make a video too if it would be helpful. What screen
capture do you recommend?

**Comment by tentone** [comment]
I usually use (Win + R) (in windows 10) to record using the Xbox DVR tool, or camtasia when i need to record something with more quality and do som editing after.

I have used ezvid in the past, its free and uploads directly to youtube.

Can you please open the console (F12) while recording so that i can see if some error is being thrown? :) Thanks a lot!

**Comment by jpryne** [comment]
Ok, I was afk, but I'll give this a try now...

**Comment by jpryne** [comment]
I'm a bit leery of EZVid, but here's a screenshot:
[image: Inline image 1]
Here, I'm dragging the script onto the box, but when I release, it simply
re-orders them so the script is before the box in this list. If this isn't
good enough, I'll find some screen recording software to show this better.

**Comment by topcheese** [comment]
I thought it was just me, but you can copy and paste it over.  I'm on win 10, and it just seems to reorder it.  I will have to check it again.

**Comment by topcheese** [comment]
Seems like only when the script is empty, you can't drag and drop to it.

**Comment by jpryne** [comment]
Yes, I've found that copy and paste works fine, yet even after editing the
script, I still cannot drag it onto a mesh object.

**Comment by tentone** [comment]
@jpryne I could not see the image you took because you're replying from email, can somebody check if there is some error on the console (F12)

**Comment by jpryne** [comment]
I'm getting a warning, though not sure if it relates to this issue at all:

> nunu.editor.min.js:1800 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

I get no error when trying to drag one object onto another. It simply re-orders the items in the Project bExplorer without error.

**Comment by topcheese** [comment]
There is no error, it doesn't seem to want to drop anywhere.  I'm using the windows build, but I'll try a different one.

**Comment by tentone** [comment]
@topcheese @jpryne Just released a new version can you please retest this on the new version?, thanks a for you feedback im trying to find out what is happening there.

**Comment by jpryne** [comment]
Sorry, TenTone, but I'm still having this issue in 8.9.26

**Comment by topcheese** [comment]
I have not tried the new version, but I did just try the web version.  I get the same XMLHttp error.  followed by FileSystem.readFile@nunu.editor.min.js:1800.
MS Edge exhibits the same behavior. It will get focus on mouseover, but it's not acting like a target when empty.

**Comment by topcheese** [comment]
I forgot to say it's no problem.  I just stumbled across this project a couple of days ago, so I really have no clue about what's going on.  I will do what I can to check it out.  Thank you for everything!

    I was wondering can this be ran in a sandbox, I'm beginning to think it is a permissions issue?

**Comment by topcheese** [comment]
And the web version works on my Linux machine, so I'm sure the native version works.  I'll play around with it later.

**Comment by tentone** [comment]
@jpryne @topcheese I have been investigating about this, are you running on a touch enabled device? (Windows laptop or tablet with touchscreen?)

**Comment by topcheese** [comment]
Not on the windows 10 laptop, but I am on the Linux laptop where it does
work.

**Comment by tentone** [comment]
Closed, i tried to investigate the problem but im unable to recreate it on my side.

If somebody else reports this problem i will reopen this issue.
