### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by faviouz** [tentone/nunuStudio#47]
Why not use Electron rather than NW.js? The community is much bigger and it's much nicer to work with Electron. Cross platform desktop builds are also much easier.

I'm bringing this up because I'm on macOS and there's no desktop build available.

**Comment by tentone** [comment]
Hi

There is no specific reason. Electron has been more stable (from time to time nwjs gets broken features) and has a bigger community behind it (being maintained by GitHub is also a bonus) dev tools are also good. I do prefer the way nwjs integrates node and the fact that it is always up to date (chormium and node), but its not a dealbreaker.

By the time i started the project, needed to merge the code base (of one of them) with a experimental chromium branch that had experimental support for webvr and after fidling for a bit with booth i ended up going with nwjs.

I can add support for osx, i dont have any way to properly test it (other than running it inside a VM) but it should be no problem.

Tomorrow i will try to take some time to package it and upload.

Thanks a lot!

**Comment by brylie** [comment]
Just my two cents, but Electron seems to have more active development process.
- https://github.com/nwjs/nw.js/graphs/contributors
- https://github.com/electron/electron/graphs/contributors

However, it might be that NW.js is a better fit for this project. Might Electron a good tool for this type of project?

**Comment by tentone** [comment]
Booth of them work well for this project, the editor can even run as a standalone directly in the browser nunu only uses node for file and clipboard access.

Booth of them have the same objective and are built on the same foundation (chromium and node, although they integrate these technologies differently).

There is no doubt that electron has a more active development community but nwjs is being updated pretty much every two weeks or so, not bad so far.

**Comment by tentone** [comment]
@faviouz 

Added a macos release, but since i wasn't able to test it i don't even know if it is packaged properly, if you test it please let me know 👍 

https://github.com/tentone/nunuStudio/releases/tag/v0.8.9.25-alpha

Thanks a lot!

**Comment by faviouz** [comment]
Nice, thanks for the effort! There are issues with the package, let's continue this over at #49
