### ISSUE TITLE
multiple errors at publish to html from web version: extractpoints, t is undefined, resize is not defined

### ISSUE THREAD

**Issue by j2l** [tentone/nunuStudio#472]
# Description
 I tried [nunu web editor](https://www.nunustudio.org/editor/index.html) and tried to publish to html5
It saved locally and I ran http-server to server index.html
On FF & Chrome I have various errors:
![image](https://user-images.githubusercontent.com/65325/108600448-8c895b00-7397-11eb-8674-a74afc6415eb.png)

![image](https://user-images.githubusercontent.com/65325/108600420-79768b00-7397-11eb-80ee-6fe91b89ff0c.png)

##### Version
 - v0.98

##### Platform
 - Web Version [X]
 - Linux [X]

EDIT : It only happens when using 127.0.0.1:8080 but it's working fine with LAN IP

**Comment by tentone** [comment]
Hello

This might a be a problem with the webserver, just tested using python integrated webserver.

Seems to be working without any problem (try with python -m http.server)

Thanks a lot for reporting.

Cheers
