### ISSUE TITLE
Render freeze after trying to move a object

### ISSUE THREAD

**Issue by Bryceed** [tentone/nunuStudio#473]
# I can't move objects! 

##### Description
Move funcion stop to work after trying to move any object in the world we're editing (*rotate and scale works as expected*). 

Web editor (0.98.28 2021-01-23T18:51:35.009Z) work normally too.

Bug recorded: [Streamable](https://streamable.com/gfccfd)

##### Version
> nunuStudio 0.9.6 (Build 201904261147)

##### Platform
 - Web Version [  ]
 - Windows [X]
 - Linux [  ]

**Comment by tentone** [comment]
Hello

This bug has been fixed in the meanwhile i have to update the deskop version executables.

Thanks a lot for reporting this issue.

Cheers
