### ISSUE TITLE
Can't build / run since version >= 0.98.x

### ISSUE THREAD

**Issue by shantee** [tentone/nunuStudio#475]
Hello ,
I can't build or run nunuStudio. At this point I still don't know whether it is a specific problem with my configuration or something else.
I wonder if anyone is able to make it work by cloning the repo and then with  
npm install / start etc..

Since I can't I have found a little "trick" that I am using for instance. I simply turned the web version of nunuStudio into an "app" .
you need either chrome or chomium.
-> then find the three vertical dots ( ⋮) on the top right corner to access a dropdown menu.
-> click on "more tools' then create a shortcut 
-> tick the checkbox that says " Open as window " and voila !

I know it doesn't make an "app" per se but it is much more convenient than using the web version inside a tab of your browser.

**Comment by tentone** [comment]
Hello

Currently, the project is not working well. I have been quite busy with work and studies (PhD) and I have been trying to get some time to update nunuStudio to ES6 in order to update the three.js version as well to recent versions.

Your solution does not differ that much from what I'm calling "desktop" version if you download the repo and run "npm run start-nwjs" it is still working might be an option for you.

Thanks a lot for your patience, and for reporting many of these issues.

Cheers

**Comment by shantee** [comment]
Well I actually did try this before "npm run start-nwjs" but without success. This is what I get :
```
> nunu-studio@0.98.28 start-nwjs
> webpack --config webpack.dev.js && run --with-ffmpeg --mirror https://dl.nwjs.io/ ./docs/editor

[webpack-cli] Failed to load '/home/noone/logiciels/nunuStudio/webpack.dev.js' config
[webpack-cli] Error: Cannot find module 'webpack'
Require stack:
- /home/noone/logiciels/nunuStudio/webpack.dev.js
```
[... bla bla bla ... ]
```
npm ERR! code 2
npm ERR! path /home/noone/logiciels/nunuStudio
npm ERR! command failed
npm ERR! command sh -c webpack --config webpack.dev.js && run --with-ffmpeg --mirror https://dl.nwjs.io/ ./docs/editor
```
Then there must be something wrong with my system . I guess I 'll have to study this whole mess a little bit :) but its ok for now the "chrome window" solution works kinda well and it's ok for what I am doing. 
I am also "playing" with playcanvas but I love nunuStudio because it integrates threejs and it's definitely the best editor there is for people familiar with threejs.
 
I wish you the best success with your other projects!

**Comment by tentone** [comment]
Have you run npm install before running the npm run start-nwjs command?

Playcanvas is a great solution in my opinion their engine is quite good, it lacks a bit of community support that's were threejs shines.

Thanks a lot!

**Comment by shantee** [comment]
Thanks a lot for the tip. I tried in a new environment (Ubuntu on a VM) and it does work indeed ! 
That's also my thoughts about playcanvas, plus (at my level) I feel more comfy with threejs
