### ISSUE TITLE
sepia post processing example is not working

### ISSUE THREAD

**Issue by j2l** [tentone/nunuStudio#478]
##### Description
https://www.nunustudio.org/learn/basics/postprocessing
tested in FF and Chromium (ubuntu 20.04)
result is just a black screen
if `camera.composer.passes[0].renderToScreen = true;` camera is normal
Console error in Chrome only:
`js.blend.js:273 Uncaught TypeError: _data.slice is not a function
    at parseFile (js.blend.js:273)`

Hope it's an easy fix :smiley: 
##### Version
 - 0.98

##### Platform
 - Web Version [X]

**Comment by j2l** [comment]
UPDATE:
Copying the script and pasting it in a new project (+ uncomment the shader call part at the end and remove the library import at the start) makes it work.

**Comment by tentone** [comment]
Hello

Sorry for the late response:

Yes it seems to be a typo in the example.

I will correct it and reupload the example.

Thanks!

**Comment by tentone** [comment]
Updated example file
[Uploading sepia.zip…]()

**Comment by j2l** [comment]
Oh, great!
I checked the nunu console, the browser console and couldn't find a clue.
I don't know where to look to get the error related to the behavior.

**Comment by tentone** [comment]
It's a bit tricky I will have to add some additional detail to provide better feedback about these errors.
