### ISSUE TITLE
Thank you for your learning section! I'm so happy!

### ISSUE THREAD

**Issue by j2l** [tentone/nunuStudio#481]
It helps me a lot to understand the mechanic of NunuStudio and learn Three.JS
You can close this one after reading :smile: 

https://user-images.githubusercontent.com/65325/110970540-25d5dc80-835a-11eb-9a4e-059fccd4a930.mov

EDIT: Video file is not corrupt, it just doesn't want to play it into the browser.

##### Platform
 - Web Version [X]

**Comment by tentone** [comment]
Hello

Thanks a lot, glad the learning information can be of help.
