### ISSUE TITLE
Can't get gltf texture/material in Run mode, but OK in Editor

### ISSUE THREAD

**Issue by j2l** [tentone/nunuStudio#482]
gltf object is importing just fine (blender glb export with jpg texture compressed)
![image](https://user-images.githubusercontent.com/65325/111322248-02b47100-8669-11eb-812c-e7d095f464d0.png)
But when I hit run, I get non-textured objects:
![image](https://user-images.githubusercontent.com/65325/111322564-5aeb7300-8669-11eb-93e5-02e4e1e3ed3b.png)

I also tried:
- using an internal cube and apply material
- making a standard material using this texture
- dragging the texture upon an internal cube
- FBX, DAE, OBJ (no texture imported)

All failed

 - Web Version [X] 0.98.30

This one is very urgent.
Thank you.

**Comment by tentone** [comment]
Hello

Can you please provide an example file for me to test?

This is probably related with the usage of the blobs that are created to load the texture and are then discarded by the glb loader.

This makes them unusable after the loader finishes its job, they do this to prevent memory leaks.

This is certainly require some code injection into the GLTF loader.

Thanks a lot!

**Comment by j2l** [comment]
Sure, I will. I have a even more urgent post about screenshot first :)

**Comment by j2l** [comment]
Here's the house
[house.nsp.zip](https://github.com/tentone/nunuStudio/files/6159149/house.nsp.zip)

**Comment by j2l** [comment]
Reopening the scene to check, I see that the texture is empty, it wasn't saved with the nsp, so here's the gltf (glb) file to import.
[house.glb.zip](https://github.com/tentone/nunuStudio/files/6159271/house.glb.zip)

**Comment by j2l** [comment]
Sorry to write on this great long week-end :)
Would you please have a look on this one?
I'd need it to build a scene.
Thanks!

**Comment by j2l** [comment]
Hello,
Hope you have time fr this one, I tried all I can to make it work on my own. No luck so far.

**Comment by j2l** [comment]
see above @tentone :)

**Comment by j2l** [comment]
Can you please tell me if you know another way to import & apply texture on imported mesh with UV map?
Thank you very much

**Comment by j2l** [comment]
OK,  I guess it's way too hard to fix. I'll find another way.

**Comment by tentone** [comment]
Hello Well this one is pretty much impossible for me to fix because the blob is discarded after the GLTF loader uploads data to the texture. It would required some sort of code injection into the GLTF loader.

Thi might be achievable with some sorte of witchery using webpack loaders but it will be quite tricky. The best solution would be to convert the file into another format.

**Comment by j2l** [comment]
I don't understand how it is perfectly working in the editor then.
Why does only the run mode discard the texture?

**Comment by difool95** [comment]
Hello, i know it's been a long time since you opened the issue, but did you find a solution for this ?

**Comment by j2l** [comment]
Nope, project, looks like is abandoned unfortunately.

**Comment by tentone** [comment]
Hello

I havent found much time to maintain the project.

Currently the project is pretty much stuck it would require a lot of work since three.js has moved into modules and the entire object system would need to be revised.

**Comment by j2l** [comment]
I understand @tentone . It's a crossroad: capitalize on this great project (1700 stars!) and redo it from scratch or archive it. Depending on your long term plan. Please let us know. 
Your approach with JSON scenes, integrated code editor and effects is great!
If I could, I would start something like this with svelte but I'm more an artist than a coder.

**Comment by zhaoran112** [comment]
Hello
How do I fix this bug?
@tentone @j2l

**Comment by j2l** [comment]
2022, no fix. Good luck
