### ISSUE TITLE
macOS package error

### ISSUE THREAD

**Issue by faviouz** [tentone/nunuStudio#49]
I've downloaded the release, extracted and attempted to open nunu.app but it throws

```
You can’t open the application “nunu” because it may be damaged or incomplete.
```

![image](https://cloud.githubusercontent.com/assets/180382/25954410/20eb5daa-365e-11e7-8689-b275e1e773b8.png)

Potentially relevant issue https://github.com/nwjs-community/nw-builder/issues/346

**Comment by tentone** [comment]
I will try to borrow somebody to let me use a MacOS machine, so that i can check whats going on, but today i will try to take some time to check this more carefully.

I'm not using nw-builder for packaging. 

Thanks for reporting 👍

**Comment by tentone** [comment]
@faviouz 

Hi, i updated the release can you please try it out?

https://github.com/tentone/nunuStudio/releases/download/v0.8.9.25-alpha/nunustudio-0.8.9.25-alpha-macos.zip

Thanks a lot!

**Comment by faviouz** [comment]
I can open it now (unlike before) but it crashes. Here's the report.

https://gist.github.com/faviouz/5e1aa28f378775656c0208afd816dd8d
