### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by unrealfuzzy** [tentone/nunuStudio#494]
Hi, I'm new to the repository and been trying to build the project on both MacOs and Windows, and keep on hitting the same problems with AngularJS

In a freshly checked out repository with this commit:
https://github.com/tentone/nunuStudio/commit/f4a76c117f807cabae65ea118aac1487b270c99a

I run
`npm install`
`npm run build`

and keep on getting one of these:
`An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'`
or
`An unhandled exception occurred: Cannot find module '@angular/compiler-cli'`
or
`You seem to not be depending on "@angular/core" and/or "rxjs". This is an error.`

Tried everything I found on StackOverflow with no luck.

I do have Java installed on each machine.

Windows Config:
Windows 10
node v14.17.4
npm 6.14.14

MacOs Config:
MacOs 12.0.1
node v17.0.1
npm 8.1.0

Please help me get going with the project?

**Comment by tentone** [comment]
Hello

This bug seems to be related with webpage dependencies, since the webpage is build on angular.

Glad you where able to figure those out.

Thanks a lot!
