### ISSUE TITLE
AR availibility

### ISSUE THREAD

**Issue by difool95** [tentone/nunuStudio#495]
# AR on exported projects

##### Description
 - I'm a recent user of nunuStudio, i want to use AR feature, with the help of webXr Api emulator i was able to activate AR on the editor, but when i export projects i get the AR button but when i click nothing happens, isn't that supposed to work on both editor and exported project. thanks in advance

##### Version
 - Using the latest nunuStudio version

##### Platform
 - Web Version

**Comment by helzapps** [comment]
I had a similar issue and found out my webXR projects must be hosted on a secure (https) server in order for them to work and recognize the devices AR/VR capabilities.

**Comment by difool95** [comment]
Yeah i know that WebXr need to work with https, but my problem was something else i figured it out by changing a line of code (i think it's a bug) on the last version of nunuStudio 0.98.33, the name of the script is App.js.
![Capture d’écran 2021-11-19 à 18 03 35](https://user-images.githubusercontent.com/65021359/142662524-48971512-2cad-41ec-8e23-ec2f0a6a831b.png)
![Capture d’écran 2021-11-19 à 18 03 42](https://user-images.githubusercontent.com/65021359/142662534-cd097451-7843-4e9f-8ed1-45dff68f3cff.png)

**Comment by helzapps** [comment]
Well I've _never_ made a copy paste mistake like that in my life 😆. Glad you were able to find and fix your local version.

**Comment by tentone** [comment]
Hello

Glad you figured it out! It is a typo I will fix it.

Thanks a lot!
