### ISSUE TITLE
Run is stopped if switched to a script tab / remember scrolling pos

### ISSUE THREAD

**Issue by faviouz** [tentone/nunuStudio#51]
If you:

1. Run the scene
2. Switch to a script tab
3. Go back to the scene

It appears the scene was stopped, i.e. it's not running anymore.

Is this intentional? I would argue it's a bit inconvenient. At least for me right now, I find myself going back and forth between the two tabs (the scene and the script) and it would be nice if it the scene wasn't stopped so that I can look at it and go back to the code.

**Comment by tentone** [comment]
This is intentional, at the beginning code and object edition was possible but was a bit hard to  handle integrity, history, etc

I totally compreend what you are saying

To speed up things a litle you can use shortcut keys like alt+tab to change tab and F5 to run the program

**Comment by faviouz** [comment]
Can we at least make it so scroll position in code is remembered?

It really kills my productivity having to scroll through code to go back to where I was.

**Comment by tentone** [comment]
Yeah of course i should have done that already , my bad.

Thanks.

**Comment by faviouz** [comment]
Nice! 👍

**Comment by tentone** [comment]
Hi 

Editor updated to keep scrolling position after tab change. (Was actually a really small change)

Thanks a lot!

Cumps

**Comment by faviouz** [comment]
Awesome! ❤️
