### ISSUE TITLE
is there have latest version ?

### ISSUE THREAD

**Issue by sunboy123** [tentone/nunuStudio#513]
thank you for your dedication！！
 I want to use it in my work like unity tool; but I see a lot of bugs, where to see the bugs fixed, is there any plan for the latest version update, and if I want to export the whole project code When I go to the local, I see that there is an nsp file that cannot be opened. How can I see the exported js source code?

**Comment by Bryceed** [comment]
A **changelog** and **milestone** view for this project will be something really nice to follow and help, as developer. 

<details><summary>Example from <a href="https://github.com/ppy/osu">osu! project</a></summary>
<img src="https://user-images.githubusercontent.com/42657376/160746775-57bc9596-0c04-4b41-ada1-d704a0bbb009.png" />
</details>

-------

nunuStudio is unique with the proposal it has, but it's too bad it really has so many bugs to think start to use it as the main development platform - even more harder looking like an abandoned project. 

Web platform `0.98.30` seems to be outdated, and native builds are even more `0.9.6` with bugs that are already fixed on the web version.

![image](https://user-images.githubusercontent.com/42657376/160747239-c968bce9-4f12-4e38-bc96-945e3b5a3d19.png)

**Comment by tentone** [comment]
Hello

Both version are outadet compared to the repository, 

In the last year i have not dedicated a lot of time to the project, To properly keep the project it would require a huge migration to fully use ES6 and ensure compatibility with newer three.js versions.

I can upload new versions of the editor and web version to ensure that users are accessing the latest version.

 @Bryceed  Thanks a lot for the suggestion i will look into it and see if if can alocate some time to reorganize the project.
 
 Cheers
