### ISSUE TITLE
navigation reverse and inverse vertical doesn't work

### ISSUE THREAD

**Issue by 01miaom** [tentone/nunuStudio#515]
# navigation reverse and inverse vertical doesn't work

##### Description
 I meet the same problem with issue 408, when using orbit as camera navigation mode, the movement was reversed. Also the invert vertical in the settings doesn't seem to work. In MacOS, chrome 99.0. I've spent a few hour reading the source code, but haven't figured out what the problem is, the project code or the threejs api. (In threejs editor I tried, the orientation is normal.) [I recorded a video to better describe the problem](https://01miaom.github.io/xiaomiao.github.io/gallery/video.html)
Also, thank you for open-sourcing this amazing project.  

##### Version
 - <0.98.30> <2021-03-11T13:50:22.597z>

##### Platform
- [chrome 99.0] Web Version

**Comment by tentone** [comment]
Hello

In the latest version of the editor a new options to invert movement of the camera in the editor was added under settings.

Please check the latest version from the repository.

**Comment by 01miaom** [comment]
> Hello
> 
> In the latest version of the editor a new options to invert movement of the camera in the editor was added under settings.
> 
> Please check the latest version from the repository.

Thanks for your reply, this new options is working. This is an extremely awesome project and I really like it.
