### ISSUE TITLE
MathUtils.lerp() is not working

### ISSUE THREAD

**Issue by PikabobAlex** [tentone/nunuStudio#518]
# MathUtils.lerp() is not working

##### Description
mainCamera.fov = MathUtils.lerp(mainCamera.fov, new_fov, time)
I'm trying to lerp the current fov to a new fov but the editor keep prompting that the MathUtils.lerp is not a function

##### Version
 - 0.9.6

##### Platform
- [ ] Web Version
- [x] Windows
- [ ] Linux

**Comment by tentone** [comment]
Hello

The MathUtils.lerp() method is avaiable as THREE.MathUtils.lerp()
