### ISSUE TITLE
Web platform becomes unresponsive and crashes

### ISSUE THREAD

**Issue by faviouz** [tentone/nunuStudio#52]
Over time (after a few runs), the web platform (which I'm running on Chrome 58 on macOS) becomes very unresponsive and slow, sometimes even crashing. The scene I'm working on only has a couple of images and the script is nothing out of the ordinary, if that helps.

I realize this is very vague and unhelpful. I'm looking for pointers as to where I should look in order to understand the issue and perhaps come back with more feedback. How can I profile it?

**Comment by tentone** [comment]
Hi im aware of some problems, some of them on external libs i have been patching some of those lately but every help to find and debug those  is appreciated.

To debug you can use the dev tools included with nwjs (or your browser) , console also helps to debug and inject test code (usefull to debug glsl)
