### ISSUE TITLE
How to build and run nunuStudio ?

### ISSUE THREAD

**Issue by Otcpopp** [tentone/nunuStudio#521]
Hello
I am sorry I can't figure how to launch nunuStudio with the latest source from github.
Everything goes well until I run `npm run build`
`Error: Command failed: git rev-parse --abbrev-ref HEAD
fatal: not a git repository (or any of the parent directories): .git`

![image](https://user-images.githubusercontent.com/63579214/182808606-b6cb11f9-44e1-48f6-8a9f-58451622ec0c.png)

Node.js v16.15.0

**Comment by tentone** [comment]
Hello

To run nunuStudio install dependencies with `npm install` and after run `npm run napa`.

To start the editor run `npm run start`.

Thanks a lot!

**Comment by yaakovyitzchak** [comment]
@tentone does that build it as well?

**Comment by tentone** [comment]
To build the editor run `npm run build`

**Comment by pxim** [comment]
> napa
![image](https://user-images.githubusercontent.com/5111701/230295359-6e460358-52bb-44ac-864a-c133c798d1b3.png)

![image](https://user-images.githubusercontent.com/5111701/230295310-db659876-a1cc-4fd1-abe1-f9a0427402e0.png)

why

**Comment by 01miaom** [comment]
You should git clone this repository instead of downloading the zip and then unzipping it
