### ISSUE TITLE
How do I upgrade the three.js version?

### ISSUE THREAD

**Issue by icewizardry** [tentone/nunuStudio#525]
I found that the current version of three. js is 104, and it has been released to 140+, how to upgrade?

**Comment by tentone** [comment]
Hello

The threejs version cannot be upgraded. Newer versions have moved to the usage of ES6 classes that dont work with ES5 inheritance.

Code has to be refactored before three.js can be upgraded.

**Comment by WelinkOS** [comment]
Is there any plan to upgrade

**Comment by WelinkOS** [comment]
@tentone Is there any plan to upgrade

**Comment by tentone** [comment]
No plan to upgrade threejs in the near future.
