### ISSUE TITLE
Inverse horizontal mouse look in the editor

### ISSUE THREAD

**Issue by RednibCoding** [tentone/nunuStudio#526]
# Inverse horizontal mouse look in the editor

##### Description
 - In the settings under: File->Settings->Editor->Navigation for Navigation mode Orbit, there is an option to invert vertical mouse look. It would also be nice to also have the option to invert the horizontal mouse look as well.

**Comment by Bryceed** [comment]
This is definitely necessary, also including a code controller (allowing users to revert it under any "game settings", if preferred)
