### ISSUE TITLE
There will be unlimited new image bugs when creating images

### ISSUE THREAD

**Issue by zyyquanquan** [tentone/nunuStudio#539]
# There will be unlimited new image bugs when creating images

##### Description
When you drag pictures into the material, new picture resources will be generated. Currently, the inability to create folders is also a big pain

##### Version
 0.98.34

##### Platform
Web

**Comment by tentone** [comment]
Hello

Thanks a lot for reporting this issue.

In the meanwhile it was fixed, please test in web version:

Best Regards
