### ISSUE TITLE
Error saving file ReferenceError: Buffer is not defined  

### ISSUE THREAD

**Issue by icoco** [tentone/nunuStudio#545]
# :Error saving file ReferenceError: Buffer is not defined  

##### Description
 clone the code and run , try save project to nsp ( from menu [File]->[Save]) , but  failed , report error :"Error saving file ReferenceError: Buffer is not defined "

another issue while running first, console out warning / error : 'WebGL: INVALID_VALUE: viewport: size < 0'

not sure if this warning  make the 'save' feature failed,   

##### Version
 - 0.98.38,  

##### Platform
- Mac

**Comment by quadro-chave** [comment]
"Error saving file ReferenceError: Buffer is not defined "
I noticed that happening in the web version too

**Comment by DanilLoft** [comment]
A similar problem in the web version, both when saving and publishing :/

**Comment by tentone** [comment]
Hello

This issue is now fixed on web version.

Thanks a lot for reporting this!
