### ISSUE TITLE
Web version isn't working

### ISSUE THREAD

**Issue by faviouz** [tentone/nunuStudio#55]
The web version at https://nunustudio.org/editor/editor.html isn't working, likely due to some bug recently introduced

![image](https://cloud.githubusercontent.com/assets/180382/26496065/e3f3c146-421d-11e7-8e94-5782ae9ccd24.png)

**Comment by tentone** [comment]
HI im aware of this problem, as soon as i get some free time i will patch it.

Thanks a lot for reporting it!

Cumps

**Comment by tentone** [comment]
The editor should be working again, also added autocomplete with documentation (for now only some old threejs docs also used on the official threejs editor)

![capture](https://cloud.githubusercontent.com/assets/9158354/26514136/cf8e71f2-4267-11e7-8a31-2e75ea43c40a.PNG)

Cumps

**Comment by faviouz** [comment]
Autocomplete with documentation is handy, thanks!

**Comment by tentone** [comment]
@faviouz 

Thanks! 👍 Still needs some work nunu specific docs are still incomplete!
