### ISSUE TITLE
Crash when using too many resources

### ISSUE THREAD

**Issue by faviouz** [tentone/nunuStudio#56]
I've been paying attention to resource usage and I've noticed the editor peaks at ~2GB of memory and then crashes the tab.

![image](https://cloud.githubusercontent.com/assets/180382/26552457/1dbe031a-447f-11e7-890a-1e3c5efade2a.png)

Is ~2GB of memory usage expected? Why? What's the bottleneck here?

Last time we talked you mentioned something about not being able to clear WebGL buffers or something. Can you expand on that?

**Comment by faviouz** [comment]
It's worth noting there seems to be a correlation between resource usage and time spent in the editor.

After just a few runs:

![image](https://cloud.githubusercontent.com/assets/180382/26553451/9cc4aa02-4483-11e7-85a8-5b5abcd627ba.png)

After many more runs the situation above eventually kicks in.

**Comment by tentone** [comment]
Hi there

Well i have some good news the last revision of the WEBGL_LOSE_CONTEXT extension (published on 03/02/2017) specifies that on context lose all resources attached to the context should be automatically cleaned off.

I will push a new version that forces webgl context loss on tab close, this should help quite a bit with memory usage, but im still unsure if everybody has implemented this change.

More info here https://www.khronos.org/registry/webgl/extensions/WEBGL_lose_context/

Thanks
