### ISSUE TITLE
Maintain file name when saving

### ISSUE THREAD

**Issue by faviouz** [tentone/nunuStudio#57]
It would be nice if the filename was remembered when you open a file, so that when you save it it prompts you to save it with the same name (rather than the "file.isp" default that is offered). Sounds reasonable?

**Comment by tentone** [comment]
Implemented, should be live soon, CTRL-S now saves with the previous name automatically, and "Save as" allows to select a new name.

**Comment by faviouz** [comment]
Great, thanks! :D
