### ISSUE TITLE
Errors during runs

### ISSUE THREAD

**Issue by faviouz** [tentone/nunuStudio#58]
I think it would be better if errors during runs were logged to the console, rather than be `alert()`ed to the user and disappear once you click OK, which lets you look at it more closely and click on files to further inspect the issue.

![image](https://user-images.githubusercontent.com/180382/27126971-1e57f154-50f1-11e7-9c0e-9f09a611a49a.png)

**Comment by faviouz** [comment]
A simpler alert like "An error occurred in runtime. Check the console" would still be appropriate.

**Comment by tentone** [comment]
Yeah totally agree, error messages on the alert box are not helpfull for debugging, i will change the alert box and also print the error stack to the console.

Thanks!

**Comment by faviouz** [comment]
Awesome!

**Comment by tentone** [comment]
Implemented this, i will have to think about a better way for script debuging sometimes it can be tricky to debug annonymous functions.

**Comment by faviouz** [comment]
By the way, this particular error took me a while to figure out (because the error stack is just internal nunuStudio code, not my activity's code). Turns out it was because I had forgotten to create the materials for the new textures I added.

Rookie mistake, but it could have been pointed out in a more obvious way (i.e. "material not found").
