### ISSUE TITLE
Load file doesn't do anything

### ISSUE THREAD

**Issue by faviouz** [tentone/nunuStudio#59]
Sometimes, on a fresh load of the web version, loading a file doesn't do anything. It only loads successfully on the second time. I've reproduced this many times.

**Comment by tentone** [comment]
Hi

What browser are you running on? Can you provide a way to reproduce this on the browser?

This happens on the desktop version on older versions but was a NWJS realated bug.

Thanks for reporting

**Comment by faviouz** [comment]
I'm running Google Chrome Version 58.0.3029.110 (64-bit) on macOS.

This always happens to me when I sit down to do some work, open nunuStudio and attempt to load a file. The first attempts don't work. The following attempts do.

To reproduce, maybe:

1. Close the web browser
2. Launch the web browser
2. Open https://nunustudio.org/editor/editor.html
3. Attempt to load a file (nothing should happen)
4. Attempt to load a file again (should work now)

**Comment by tentone** [comment]
Hi

I think last commit may fixed this problem.

Im doing some automated tests for this since for me on NWJS is occurs randomly but adding the file chooser to the doc before clicking it seemed to fix it.

Thanks for reporting this.

Cumps
