### ISSUE TITLE
Error loading nsp file

### ISSUE THREAD

**Issue by faviouz** [tentone/nunuStudio#61]
There are issues loading the new NSP file format

![image](https://user-images.githubusercontent.com/180382/27593048-0d42cb2a-5b4e-11e7-859e-0a9263a13053.png)

**Comment by faviouz** [comment]
I'm running Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by tentone** [comment]
Hi @faviouz 

Fixed!, i hope the new format helps a bit with file size and loading times!

Thanks a lot for reporting.
