### ISSUE TITLE
Delete multiple textures/materials

### ISSUE THREAD

**Issue by fabiomaia** [tentone/nunuStudio#65]
Sometimes it would be nice to be able to delete multiple textures/materials at once, by selecting them for example.

**Comment by tentone** [comment]
Hi

I think the hole asset explorer needs a big review, regarding file selection maybe folder organization etc.

Right now im a bit busy (due to work) but as soon as i finish the console and AR implementation i can pick this up.

Thanks a lot for the suggestion.

Cumps

**Comment by faviouz** [comment]
Sounds good!
