### ISSUE TITLE
Default min filter

### ISSUE THREAD

**Issue by faviouz** [tentone/nunuStudio#67]
Why is MIP Linear Linear a texture's default min filter?

![image](https://user-images.githubusercontent.com/180382/28272560-c69d7434-6b03-11e7-9b70-63517839b733.png)

I get much nicer (crispier) results using Linear, which I always switch to.

**Comment by tentone** [comment]
Mipmaps are usual and should for minification provide smother results you can read more about them here https://graphics.ethz.ch/teaching/former/vc_master_06/Downloads/Mipmaps_1.pdf.

**Comment by faviouz** [comment]
Thanks! Interesting stuff.
