### ISSUE TITLE
Fix aspect ratio bug

### ISSUE THREAD

**Issue by faviouz** [tentone/nunuStudio#69]
Given an image that "touches" the edges of the canvas

![image](https://user-images.githubusercontent.com/180382/28366709-c9670f62-6c85-11e7-9463-69f8fec2f6e2.png)

Using fix aspect ratio produces results like

![image](https://user-images.githubusercontent.com/180382/28366730-e0a5ff44-6c85-11e7-8307-7b3b22e51ba9.png)

I'm guessing it's an issue in the underlying algorithm, but I hypothesised that it would work if I fixed the image so that it didn't touch the edge of the canvas. Indeed, moving the image a few pixels around lets me fix aspect ratio as intended. In this specific case, I just needed to move the grapes 2px up and now fix aspect ratio works.

![image](https://user-images.githubusercontent.com/180382/28366913-8ea967de-6c86-11e7-9dbb-d066aec2a8be.png)

**Comment by faviouz** [comment]
This is the original image if you want to try it out directly

![uvas](https://user-images.githubusercontent.com/180382/28366964-c13ecaae-6c86-11e7-97a0-7829c2dbea8e.png)

**Comment by faviouz** [comment]
It's also worth noting that changing the min filter to Linear helps a bit. For example, it may be needed to move the image 4px up, but with the Linear min filter you may only need to move it 2px up for fix aspect ratio to work properly.

**Comment by tentone** [comment]
Hi there

This is just the way opengl/webgl texture repeat mode works, the best way to fix this is to set the y offset to 0, the image will be aligned on the bottom.

https://open.gl/textures

Cumps
