### ISSUE TITLE
Use npm modules

### ISSUE THREAD

**Issue by Keevle** [tentone/nunuStudio#71]
#Use npm modules
##### Description
Would it be possible to have support for using rpm modules in the future?In my case, i needed the socket.io client for my current test project

##### Version
 - 0.9

##### Platform
 - Windows [X]

**Comment by tentone** [comment]
Hi

Yes i think support for NPM modules would be a great adition, but i need to do some testing to figure out the best way to include this.

If i include this modules should be imported by scripts? or should be made available globally?

Thanks a lot for the suggestion.

Cumps

**Comment by Phacanu** [comment]
I would say that they should be available globally to the project

**Comment by tentone** [comment]
The problem with loading them globally is that there is no way for me to unload them after , that would be a problem for the editor unless i start launching test instances on a worker.

Hmmm i have to test it , thanks a lot!

**Comment by tentone** [comment]
(Been exploring the usage os packages from npm might be trycki since we have to deploy to multiple platforms including the web)
