### ISSUE TITLE
Shadow overlaping

### ISSUE THREAD

**Issue by Phacanu** [tentone/nunuStudio#72]
# Issue title

##### Description
![](http://i.imgur.com/FY952xL.png)
The shadows stack up when you add in a lightsource creating this wierd effect,turning off the Cast shadow for the red object cancles all shadows 
##### Version
 - 0.9

##### Platform
 - Windows [X]

**Comment by tentone** [comment]
Hi

This is supposed to happen in real life shadows overlap as well.

But if you want to its possible to turn off shadows casted by the sky object. Select it and toggle th "Cast shadow" option.

I hope this helps.

Thanks

**Comment by Phacanu** [comment]
Ahhk thank you
