### ISSUE TITLE
Script editor ES6 support

### ISSUE THREAD

**Issue by MonkBliss** [tentone/nunuStudio#73]
# ES version

##### Description

Update code mirror to es6?

##### Version
 - 0.9

##### Platform
 - Windows [X]

**Comment by faviouz** [comment]
That'd be nice

**Comment by tentone** [comment]
Sorry this is totally my fault since im used to write ES5 code i dindt notice that i forgot to enable ES6 in JSHint, 

Since im at it i will add a menu in the settings tab to configure hint and lint settings for the code editor.

Thanks a lot

**Comment by Phacanu** [comment]
np

**Comment by tentone** [comment]
Support for ES6 code added along with some Linting options in the settings menu.

Thanks!
