### ISSUE TITLE
Movement speed

### ISSUE THREAD

**Issue by Phacanu** [tentone/nunuStudio#75]
# Movement speed

##### Description
It's just a comfort request, but adding the ability to control your movement speed while inside of the editor  can also be a sweet addition to the Es5/6 toggle

##### Version
 - 0.9

##### Platform
 - Windows [X]

**Comment by tentone** [comment]
@Phacanu By speed you mean keyboard cursor speed?

**Comment by Phacanu** [comment]
@tentone yes, it's hard to do small edits when it comes to detail when the player/camera movement is so fast

**Comment by tentone** [comment]
Added options to ajust movement sensitivity in settings tab
