### ISSUE TITLE
Socket.io client implimenation

### ISSUE THREAD

**Issue by Keevle** [tentone/nunuStudio#76]
# Socket.io client

##### Description
Would it be possible to get socket.ios client implemented as an optional module that you have the choice of including within your project?

##### Version
 - 0.9

##### Platform
 - Windows [X]

**Comment by tentone** [comment]
Yes, right now if you want to you can import it into the editor by using the Project/ExecuteScript option inside the editor and including it along with the nunuruntime when you deploy your application.

But i will implement that when i start  working on the NPM module import implementation (maybe this weekend)

**Comment by Phacanu** [comment]
Ahhh wow that's a great feature to hear about,thank you

**Comment by MonkBliss** [comment]
Any eta on node modules implementation?

**Comment by tentone** [comment]
(There is not a tutorial for socket based communication using WebSockets)
