### ISSUE TITLE
Delete materials

### ISSUE THREAD

**Issue by Keevle** [tentone/nunuStudio#78]
Delete materials

##### Description
It would be nice if there was a setting that you can toggle on or off to enable the ability for the user to seamlessly delete objects from a scene and delete the corresponding material

##### Version
 - 0.9

##### Platform
 - Windows [X]

**Comment by tentone** [comment]
Hi

I have to check this, i think i dont think is worth to add a option to make this be the default behavior but i can add an option to "Delete and clean" that removes the object and all resources that are not being used by anyone else.

What do you think?

Thanks a lot for the suggestion.

Cumps

**Comment by Phacanu** [comment]
Yea that would be great,My only problem was having the obj viewer cluttered with things that i deleted

**Comment by tentone** [comment]
Added possibility of selecting all objects from a material and delete all!
