### ISSUE TITLE
Choose File time is very long in Google brower

### ISSUE THREAD

**Issue by qwe5788319** [tentone/nunuStudio#8]
Add this line :
     chooser.accept = filter;

**Comment by tentone** [comment]
Hi there

The chooseFile method already has that, there is no need to set accept value if no filter is passed to the function.

```
if(filter !== undefined)
{
	chooser.accept = filter;
}
```

What version of chorme are you using?

**Comment by qwe5788319** [comment]
System: Windows 10
Google Brower Version: 56.0.2924.87 (64-bit)
Solve the  of load time long need delete for "chooser.accept = filter;"

**Comment by tentone** [comment]
I cant actually delete that, since that line is used to configure the file chooser to only display certain types of files.

Still, thanks for you feedback 👍
