### ISSUE TITLE
Integrate OpenSoundControl input with osc.js

### ISSUE THREAD

**Issue by hitmuri** [tentone/nunuStudio#82]
##### Description
nunuStudio provides Leap and Kinect input for interacting with the 3D scenes. However, a more generic input system such as OpenSoundControl would allow for using any input devices. 
This could be done by adding the osc-browser.js script from https://github.com/colinbdclark/osc.js to the libraries included in nunuStudio. From scripts, one would then be able to connects to a websocket and receive/send OpenSoundControl messages, for example to move objects inside the scene such as : 

```javascript 
var port = new osc.WebSocketPort({url: "ws://127.0.0.1:8211"});

port.on("message", function(oscMessage) {
    var split = oscMessage.address.split("/");
    if(split[1]=="input") {
		if(split[2]=="fingers") {
			if(split[3]=="index") {
        		    self.position.x=oscMessage.args[0];
			    self.position.y=oscMessage.args[1];
			    self.position.z=oscMessage.args[2];
			}
		}
	}
});
```

**Comment by tentone** [comment]
Hi

I think that OpenSoundControl can be easily used in scripts inside nunuStudio i dont see any advantage to integrate it into the editor.

I decided to include support for leap and kinect because i was already testing with them and they were the most used. It was a nice addition (specially leap  motion). 

But i might be wrong, its open for discussion.

Thanks a lot for the suggestion.

Cumps

**Comment by hitmuri** [comment]
Hi,

Thanks for you reply, and thank you very much for all the work you have done on nunuStudio, it is quite impressive.

I am curious how OpenSoundControl can easily be used in scripts.  One still need websocket and osc libraries right ? And for example adding the script i mentioned earlier using the execute script feature does not seem to work.. 

I agree about the Leap motion device is useful but for example the Kinect device integrated in nunuStudio only works on windows ... whereas an OSC input would allow for the Kinect skeleton to be used on any platform (with an openni to osc converter). 
I think having the library inside nunuStudio just makes it easier to try out things, and to publish projects.

Regards,

Florent

**Comment by tentone** [comment]
Hello

I will close this issue since its something that can be achieved fairly easily with script.

Thanks a lot for the suggestion.

Cheers
