### ISSUE TITLE
Tweaked Platformer Example

### ISSUE THREAD

**Issue by ViktorHura** [tentone/nunuStudio#83]
# Improvement to the platformer example

##### Description
When checking out the platformer example I noticed that the movement of the player is very weird.
The player cube is rotating and gets stuck to a wall if you keep pushing against it.
I made a minor improvement by changing the player model to a sphere with a radius of 0.5;
Then I added a little line of code to teleport the playermesh to the sphere ( instead of making it a child, which rotates the cube aswell when the sphere is moving). 
I also increased the angular damp of the player to decrease the sliding.
This together makes the controls feel more familiar to a classic platformer.

[scene img](http://i.imgur.com/1s1nKiC.png)
[code img](http://i.imgur.com/NkbLlk7.png)

[nsp file](http://s000.tinyupload.com/download.php?file_id=40042565628268084286&t=4004256562826808428610863)
  

##### Version
 - nunuStudio V0.9.2 Beta Build 201709031928

**Comment by tentone** [comment]
Hi viktor

Thanks a lot it does feel better.

When i was writing that tutorial i actually had planned to have the player collider as a sphere but i kinda feels "cool" to see the cube tumbling around.

I think that it would be nice to add this as an extra step in the tutorial "Tweaking player collider" what do you think? 

Cumps

**Comment by ViktorHura** [comment]
Hello,

I have made a pull request, where I have added the extra step to the tutorial.
I don't know if it fits the rest of the the tutorial but you can take a look at it.
#86 

-Viktor

**Comment by tentone** [comment]
Thanks a lot viktor.

PR was merged.

I have changed it a bit (hope that you don't mind).

Cumps.
