### ISSUE TITLE
ObjectLoader.js parse scene.background CubeTexture not support!

### ISSUE THREAD

**Issue by qwe5788319** [tentone/nunuStudio#9]

**Comment by tentone** [comment]
Hi @qwe5788319 

Im working on it, please include a proper description next time.

Cumps

**Comment by tentone** [comment]
@qwe5788319 

Implemented this today, thanks for the suggestion! 👍 

Cumps

**Comment by qwe5788319** [comment]
oh，Im so sorry,  Describe the problem clear next time!
