### ISSUE TITLE
Remove and dispose objects from the scene when you stop a run

### ISSUE THREAD

**Issue by faviouz** [tentone/nunuStudio#99]
When you stop a run, are all objects (and respective geometries and materials) removed from the scene and its references eliminated in order to free memory? See

- https://stackoverflow.com/questions/40694372/what-is-the-right-way-to-remove-a-mesh-completely-from-the-scene-in-three-js
- https://stackoverflow.com/questions/21851349/freeing-memory-in-three-js

Is this being done?

Perhaps this would fix the crashes that I have been dealing with for a while now since #52. I notice it a lot in projects where I create lots of objects dynamically, which I guess uses a lot of memory after a couple dozen of runs, at which point I have learned to just quit the browser and open everything again.

**Comment by tentone** [comment]
Hi

Yes everything is being disposed on stop, every object in nunuStudio implements the disposed method and disposes all resources attached to itself.

Currently the only big memory problem in nunuStudio is related to WebGL context not being disposed properly (nothing i can do directly on this) and huge temporary objects are also a mess, they take a while to be cleaned off memory.

Cumps
